### ISSUE TITLE
Mac OSX installation issues

### ISSUE THREAD

**Issue by mbharadwaj** [pipelinedb/pipelinedb#1025]
I am using Yosemite 10.10.4.

I got the latest (0.7.7) from the download site. The package install did not create anything in /Applications or in /usr. Googled around and found a thread on hackernews (https://news.ycombinator.com/item?id=9848746) and got to the binaries.

I see the following error now when I run init:

> /usr/lib/pipelinedb/bin/pipeline-init -D data                                                                                                                                       
The files belonging to this database system will be owned by user "****".
This user must also own the server process.

The database cluster will be initialized with locale "en_US.UTF-8".
The default database encoding has accordingly been set to "UTF8".
The default text search configuration will be set to "english".

Data page checksums are disabled.

creating directory data ... ok
creating subdirectories ... ok
selecting default max_connections ... 100
selecting default shared_buffers ... 128MB
selecting dynamic shared memory implementation ... posix
creating configuration files ... ok
creating template1 database in data/base/1 ... ok
initializing pg_authid ... ok
initializing dependencies ... ok
creating system views ... ok
loading system objects' descriptions ... ok
creating collations ... ok
creating conversions ... ok
creating dictionaries ... ok
setting privileges on built-in objects ... ok
creating information schema ... ok
loading PL/pgSQL server-side language ... ok
loading PipelineDB extensions ... FATAL:  could not load library "/usr/lib/pipelinedb/lib/pipelinedb/postgis-2.2.so": dlopen(/usr/lib/pipelinedb/lib/pipelinedb/postgis-2.2.so, 10): Library not loaded: /Users/pipelinedb/pipelinedb/pkg/osx/build/usr/lib/pipelinedb/lib/libgeos_c.1.dylib
	  Referenced from: /usr/lib/pipelinedb/lib/pipelinedb/postgis-2.2.so
	  Reason: image not found
STATEMENT:  CREATE EXTENSION postgis;

child process exited with exit code 1
pipeline-init: removing data directory "data"

**Comment by derekjn** [comment]
Sorry about that, it looks like your system isn't recognizing a newly installed library. Try adding the new library to your `DYLD_LIBRARY_PATH`:

    export DYLD_LIBRARY_PATH=$DYLD_LIBRARY_PATH:/usr/lib/pipelinedb/lib

and then running `pipeline-init` again. If that works, you'll probably want to put that in your `~/.bash_profile`.

Let us know if that works!

**Comment by mbharadwaj** [comment]
I also had to install libraries with brew:

json-c, freexl, libgeotiff

looks like the installation expects to find things already installed.

**Comment by loadzero** [comment]
That looks a bit funny:

Library not loaded: /Users/pipelinedb/pipelinedb/pkg/osx/build/usr/lib/pipelinedb/lib/libgeos_c.1.dylib

```
$ otool -L /usr/lib/pipelinedb/bin/pipeline
/usr/lib/pipelinedb/bin/pipeline:
	/Users/pipelinedb/pipelinedb/pkg/osx/build/usr/lib/pipelinedb/lib/libpq.5.dylib (compatibility version 5.0.0, current version 5.7.0)
	/usr/lib/libedit.3.dylib (compatibility version 2.0.0, current version 3.0.0)
	/usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1213.0.0)
```

We may have to rejigger the mac build with ```install_name_tool``` or similar

**Comment by mbharadwaj** [comment]
This was the error I saw as well and as mentioned in earlier response, used
brew to install three packages to get going.

**Comment by derekjn** [comment]
Fixed by #1035. We can close this out as soon as the new OSX package is published.

**Comment by Paxa** [comment]
Worked for me:
```
brew install json-c freexl libgeotiff
pipeline-init -D /var/lib/pipelinedb
pipeline-server -D /var/lib/pipelinedb
```

**Comment by hooopo** [comment]
@Paxa Thanks， this works for me.
