### ISSUE TITLE
Ubuntu packages need to mention dependancies

### ISSUE THREAD

**Issue by jberkus** [pipelinedb/pipelinedb#1028]
The Ubuntu 14.04 package depends on libxml2 and libcurl3.  These dependencies need to be named in the installation docs.

Also, we should add this note:

libcurl3 package metadata has been updated upstream, so you may need to run "apt-get update" and "apt-get upgrade" first in order to get the library to install correctly.

**Comment by derekjn** [comment]
These libs are pretty small so it would probably be simpler if we just statically linked to them when building packages.

**Comment by jberkus** [comment]
That seems like a really bad precedent.  Then we become responsible for things like security updates to libcurl.

**Comment by derekjn** [comment]
Added both dependencies to Debian and RPM packages.
