### ISSUE TITLE
Ubuntu packages should create user, data directories

### ISSUE THREAD

**Issue by jberkus** [pipelinedb/pipelinedb#1029]
The Ubuntu packages should do the following to make them consistent with the PostgresQL packages:

1. create a "pipeline" user with its homedir at PIPELINEDATA
2. create a data directory (at /var/lib/pipeline/main)
3. create a configuration directory (at /etc/pipeline/main)
4. create upstart scripts
5. start pipelinedb

**Comment by dPeS** [comment]
Any chance to stay as it is?

**Comment by derekjn** [comment]
Hi @dPeS , can you elaborate?

**Comment by dPeS** [comment]
@derekjn Well times changed. Doing setups where >service< confs are part of project's repo, infra is part of scrum flow. This means service launched from local user supervisor like circusd, pm2 or sth. In that scenario if rpm or deb is starting service... everything blows. For me all I need is binary in path.

**Comment by ztane** [comment]
BTW, who's responsible for the deb package in packagecloud.io? that package *definitely* is not ubuntu-worthy. I thought it being for "trusty" would be that it would run nicely *with* the common Debian/Ubuntu postgresql cluster/multi setup, but instead it crippled the entire development server that I tried to install it to, **despite** the deb install actually **failing** and nothing getting installed?

The package should take the recipes from postgresql pgdg .deb packages and make the pipeline db just another *version* of PostgreSQL.

**Comment by derekjn** [comment]
Hi @ztane. I'm sorry that you had issues installing the Debian package. If possible, it would be helpful if you could send us any [lintian](https://lintian.debian.org/) errors that suggest the package you downloaded is not Ubuntu-worthy. That particular Debian package has been installed many thousands of times without issue, so it seems like something strange is going on here and we'd like to help you get to the bottom of it if possible.

Thanks!

**Comment by ztane** [comment]
This was a development server that had an already running PostgreSQL instance from pgdg (the official upstream PostgreSQL repository); the installation did overwrite files like /usr/bin/psql before bailing out.
