### ISSUE TITLE
Add configuration option that enables silently dropping events that no continuous views are reading from 

### ISSUE THREAD

**Issue by derekjn** [pipelinedb/pipelinedb#1036]
Currently an error is thrown if no continuous views are reading from a stream that a client writes to. In some cases it may be preferable to just silently ignore such insertions rather than having to deal with errors.

**Comment by usmanm** [comment]
This probably only makes sense for typed streams?

**Comment by derekjn** [comment]
I'm going to close this one out for now, it doesn't seem like it's that common and it's pretty easy to work around by just creating a "/dev/null" CV.
