### ISSUE TITLE
dereference of null pointer in stream.c

### ISSUE THREAD

**Issue by ker2x** [pipelinedb/pipelinedb#1048]
Commit 239febed introduced TupleDesc desc = NULL;

At https://github.com/pipelinedb/pipelinedb/blob/master/src/backend/pipeline/stream.c#L229 you dereference desc, a null pointer.

**Comment by usmanm** [comment]
Oops, I think that was me. Weird that none of the tests broke though... Do you have some repro script that triggers a segfault?

**Comment by derekjn** [comment]
I've got a fix coming shortly.

**Comment by usmanm** [comment]
@derekjn Is this code path even used? We have tests that perform prepared stream insertions and they must not be calling this function to still be passing.

**Comment by derekjn** [comment]
There's an extended protocol that clients can use that actually does end up on this code path. I used Java + JDBC to repro this.

**Comment by usmanm** [comment]
Interesting. We should probably try to add a test for that.

**Comment by derekjn** [comment]
Yes, we should start adding test suites in different languages using different drivers as we do with the pytests.

**Comment by usmanm** [comment]
There should be a way we can use the extended protocol without JDBC?

**Comment by derekjn** [comment]
Merci @ker2x, all good now!
