### ISSUE TITLE
evaluating unititialized value in pipeline_stream.c

### ISSUE THREAD

**Issue by ker2x** [pipelinedb/pipelinedb#1053]
https://github.com/pipelinedb/pipelinedb/blob/master/src/backend/catalog/pipeline_stream.c#L190
is_inferred is declared uninitialized.

at https://github.com/pipelinedb/pipelinedb/blob/master/src/backend/catalog/pipeline_stream.c#L213
RangeVarIsForStream(rv, &is_inferred); is called

https://github.com/pipelinedb/pipelinedb/blob/master/src/backend/catalog/pipeline_stream.c#L640
if rel == NULL then return false. without setting a value to is_inferred.

back to https://github.com/pipelinedb/pipelinedb/blob/master/src/backend/catalog/pipeline_stream.c#L216 (after RangeVarIsForStream returned false) is_inferred is evaluated with an undefined value

Same problem if (rel != NULL) but (relkind != RELKIND_STREAM) then false is returned without assignment to is_inferred.
https://github.com/pipelinedb/pipelinedb/blob/master/src/backend/catalog/pipeline_stream.c#L646

**Comment by derekjn** [comment]
@ker2x thanks!
