### ISSUE TITLE
Add VACUUM FULL support to CVs

### ISSUE THREAD

**Issue by usmanm** [pipelinedb/pipelinedb#1055]
Rough sketch:

- Create temp matrel
- Instruct combiners to write to temp matrel
- VACUUM FULL primary matrel
- Instruct combiners to write to primary matrel
- Merge temp matrel into primary matrel
- Remove temp matrel

**Comment by jberkus** [comment]
Do we really want a manual command for this?  

What about the idea of having CVs automatically recreate themselves periodically?

**Comment by usmanm** [comment]
I think for now we're trying to make sure that the auto-vacuumer works good enough that the disk usage is constant if the size of the materialization table is not increasing. Having `VACUUM FULL` support is good if someone wants to make read perf better using a sledge hammer.

But I really like the idea of having an automatic periodic full vacuum. That process would be resource intensive so maybe putting it behind a flag would be better, in case someone doesn't have a super beefy box.

**Comment by jberkus** [comment]
well, I'm thinking more that you'd have some form of auto-rotation.  that is, you'd initialize a new filehandle, and gradually copy all new stream data into that.  eventually, you'd drop the old filehandle.

**Comment by usmanm** [comment]
Something akin to https://github.com/reorg/pg_repack?

**Comment by jberkus** [comment]
See issue #1066 for more discussion of how we ought to do this.
