### ISSUE TITLE
pipeline shell (psql) default port doesn't works when postgresql is installed

### ISSUE THREAD

**Issue by ker2x** [pipelinedb/pipelinedb#1057]
When postgresql client/common is installed on the system, or more specifically the libpq is installed system-wide then pipeline try to connect to port 5432 or use the default postgresql .s.PGSQL.5432 unix socket.

The thing is : the default port/socket/everything are hardcoded in libpq.

It also try to use my ~/.pgpass and all stuff from http://www.postgresql.org/docs/9.4/static/libpq-envars.html

I guess a choice need to be done somehow : 
- use all defaults from postgresql
- or change everything (including default env var, default file, etc)

pipeline --help say : 
>  -p, --port=PORT          database server port (default: "6543")

but running pipeline : 
>   pipeline: could not connect to server: Aucun fichier ou dossier de ce type
>   	Is the server running locally and accepting
>   	connections on Unix domain socket "/var/run/postgresql/.s.PGSQL.5432"?

and pipeline -h 127.0.0.1 :
>   pipeline: could not connect to server: Connexion refusée
>   	Is the server running on host "127.0.0.1" and accepting 
>   	TCP/IP connections on port 5432?

pipeline -h127.0.0.1 -p6543 -d pipeline :
> pipeline (9.4.4)
> Type "help" for help.
>
> pipeline=#

**Comment by derekjn** [comment]
The problem here is that `pipeline` symlinks to `/usr/bin/psql` upon installation. I think the correct thing to do here is just to link `/usr/bin/pipeline` to `<install directory>/bin/psql` instead of the system-wide binary.

**Comment by ker2x** [comment]
hummm nope. not in my case. i used --prefix to install it to a development directory and it used the pipeline version of psql : 

> ker2x@lily:~/build/bin$ pipeline --help
> pipeline is the PipelineDB interactive terminal.
> 
> Usage:
> [...]
> Connection options:
>  -h, --host=HOSTNAME      database server host or socket directory (default: "local socket")
>  -p, --port=PORT          database server port (default: "6543")
>  -U, --username=USERNAME  database user name (default: "ker2x")
>  -w, --no-password        never prompt for password
>  -W, --password           force password prompt (should happen automatically)
> 
> For more information, type "\?" (for internal commands) or "\help" (for SQL
commands) from within psql, or consult the psql section in the PostgreSQL
documentation.
> 
> Report bugs to <eng@pipelinedb.com>.

**Comment by derekjn** [comment]
You're definitely right @ker2x. And we'd rather maintain seamless compatibility so don't want to have our own special clients. I think the best thing to do here is to just use PostgreSQL's defaults. We originally chose `6543` specifically to not conflict with an existing installation, but this is a conflict anyways :)

It's probably more likely that a user will have a system-wide `libpq` installed than it is that they'll have an existing PostgreSQL server running on the same hardware as PipelineDB. If that were the case, I believe any port conflicts that would cause would be more obvious to that user anyways.

So adding to @ker2x 's suggestions, I see three options:

1) Use all PostgreSQL defaults
2) Use our own client with its own environment vars
3) Keep our own defaults and force clients to explicitly override them:

    psql -p 6543 ...

@usmanm do you have any thoughts on this?

**Comment by ker2x** [comment]
Well, if you really want to keep 6543 and make it behave as expected (6543 as default, as said in the --help) you can easily add :
>    if (!options->port)
>        options->port = DEF_PGPORT_STR;

at the end of : 
> static void
> parse_psql_options(int argc, char *argv[], struct adhoc_opts * options)

to override libpq default.

**Comment by usmanm** [comment]
I'm going to side with 1 (2 is a no go, and 3 are not ideal either). But does changing defaults also mean that we change the default database name etc? I think I like @ker2x's idea of just overriding `libpq` in the code.

**Comment by derekjn** [comment]
Yep, I like that approach too.

**Comment by ker2x** [comment]
**yay! \o/**

**Comment by ker2x** [comment]
Forget about my patch, it sux. I don't see how it can be done without patching libpq.

**Comment by derekjn** [comment]
We're just going to use standard defaults.
