### ISSUE TITLE
Single matrel for multiple sliding window queries

### ISSUE THREAD

**Issue by usmanm** [pipelinedb/pipelinedb#1058]
In cases where the only thing that is different is the window size

This ties into the general need to re-use existing matrels where possible.

**Comment by derekjn** [comment]
I think it might make sense to just let users create views on top of SW CVs if they want to reuse matrels. There are legitimate reasons for wanting separate CVs (such as read latency). And as you mentioned @usmanm, this conflicts with #1120 which is probably more useful anyways.
