### ISSUE TITLE
pipeline-init does not seem to pick up locale from environment

### ISSUE THREAD

**Issue by jberkus** [pipelinedb/pipelinedb#1065]
For the pipelinedb docker image (0.7.7), I created a debian install with a defined UTF8 locale.   For regular Postgres, pg_createcluster and/or initdb would normally pick this up and create databases as UTF8 by default.  For some reason pipeline-init doesn't; it still creates a SQL-ASCII installation, which of course causes issues.

**Comment by derekjn** [comment]
@jberkus I can't reproduce this. Can you check the output of `locale` on the Docker image to verify that the UTF8 locale is indeed the default? Note that the environment must be reloaded if you changed the locale to UTF8 from something else.

```
# ASCII
$ sudo update-locale LANG=POSIX
$ # Kill session and start a new one to reload environment
$ pipeline-init -D data

The files belonging to this database system will be owned by user "ubuntu".
This user must also own the server process.

The database cluster will be initialized with locale "C".
The default database encoding has accordingly been set to "SQL_ASCII".
The default text search configuration will be set to "english".
...
```

```
# UTF8
$ sudo update-locale LANG=POSIX
$ # Kill session and start a new one to reload environment
$ pipeline-init -D data

The files belonging to this database system will be owned by user "ubuntu".
This user must also own the server process.

The database cluster will be initialized with locale "en_US.utf8".
The default database encoding has accordingly been set to "UTF8".
The default text search configuration will be set to "english".
...
```

**Comment by jberkus** [comment]
Hmmmm.

So, after some testing, this issue is specific to the stripped-down linux environment inside Docker.  As such, closing.
