### ISSUE TITLE
Automatic periodic VACUUM FULL

### ISSUE THREAD

**Issue by usmanm** [pipelinedb/pipelinedb#1066]

**Comment by jberkus** [comment]
Given that a CV isn't a regular table, there's no reason why we should have a user-interrupting activity like vacuum full or repack.  Instead, we should approach this as buffer rotation.

However, I'd like to hammer this out in person; it's complicated considering all of the things a user can do in a CV, and I'm not clear on how row append/replacement works currently.

**Comment by joshk0** [comment]
Without manually calling VACUUM FULL, is the net result a monotonic increase in disk space? In other words, does the standard autovacuum not reclaim disk space in the way that we would expect it to?

We're finding that we can easily fill up our 1TB database and that a VACUUM FULL is required for it to go back down in size (usually to about 20-30GB), so for now we're assuming that autovacuum is ineffective and that we need to schedule a VACUUM FULL like twice a week.

**Comment by usmanm** [comment]
In certain cases when the system is being pushed too hard, the autovacuumer can't reclaim the disk fast enough. Have you tried to make the autovacuumer tuning parameters more aggressive? Can you also share your workload so I can take a look at it and see what's going on?

**Comment by joshk0** [comment]
Reviving this issue.

I think the issue is that autovacuum does not do 'VACUUM FULL' only 'VACUUM'. Either way, because of this we currently don't use the autovacuum support.

Has there been any progress on this front since the last time this issue was active? Basically it seems like the best approach would be an amortized incremental vacuum that gets folded into normal request traffic. Don't have good PostgreSQL perspective to know whether that's a legit way forward or not.

**Comment by usmanm** [comment]
Hey @joshk0, `VACUUM FULL` is now supported by continuous views so you can manually call it to reclaim disk space. It will however block the combiner processes because it acquires an `AccessExclusiveLock` on the relation. 

We are currently figuring out a non-blocking version of `VACUUM FULL` which works with continuous views. Are you experiencing disk space leak?

**Comment by joshk0** [comment]
Yeah, for all our largest continuous views we had to VACUUM FULL them almost daily. We've largely stopped using CVs now because of this issue. If the autovacuum process can incrementally expire dead rows the way VACUUM FULL does, it would be a good change

**Comment by derekjn** [comment]
#1482 is the right solution to this.
