### ISSUE TITLE
Sliding-window aggregation rework

### ISSUE THREAD

**Issue by derekjn** [pipelinedb/pipelinedb#1068]
There are a few complexities and non-ideal performance issues that our current sliding-window implementation has. Namely, we have to store a row for each window step and aggregate a final time at read time. This can be slow for readers, and it also requires that we perform garbage collection for expired rows.

@usmanm and I discussed how we could improve this, and we've come up with a design that we like more. Overall, here's how it works:

* There is only one row per window per output row
* One raw value per step is stored in each aggregate's transition state
* Aggregate transition state is an array of aggregate input values, its size is `(window width) / (step size)` (refs #979)
* Relevant values are combined at read time via a view over the matrel that uses `unnest` on the transition state
* No garbage collection is required!
* Reads should be much more efficient

**Comment by usmanm** [comment]
Maybe we should also get #623 in as well, as part of this rework? Keep one extra element in the array which is never removed and represents values for tuples out of the window but still valid? The only enforcement we'll need from the analyzer would be to make sure there's just a single sliding window clause. I can get changes for that in when I get to the analyzer's rework.

**Comment by derekjn** [comment]
I've been thinking about how what the worker, combiner, and user queries would look like for this. I'm thinking something like the following:

**worker**

**Comment by usmanm** [comment]
Yea, this makes sense. Just a few comments:

- The combiner should have a filter too, so it discards out of window transition states each time it commits to disk. And I'm not sure if we need an `ORDER BY`.

  ```
  SELECT <window-sized group>, array_agg(x) AS tstate FROM
    (SELECT <step-sized group>, combine(x) FROM
      (<worker batch> UNION (SELECT <window step>, windowed_unnest(tstate) FROM matrel))
      WHERE window_predicate(window_step)
      GROUP BY <step-sized group>)
  ```
- The user view shouldn't need a `GROUP BY` clause.

**Comment by derekjn** [comment]
Good call, edited.

**Comment by usmanm** [comment]
One thing that this makes tricky is that now the `TupleDesc` of the worker plan is not the same as the `TupleDesc` of the materialization table.

**Comment by derekjn** [comment]
Call `array_agg` on the worker and just unnest on the combiner to eliminate `TupleDesc` conflicts.

**Comment by derekjn** [comment]
Refs #1080

**Comment by usmanm** [comment]
As discussed offline, this idea is being shelved for now.
