### ISSUE TITLE
can only reference arrival_timestamp once per CV defintion

### ISSUE THREAD

**Issue by jberkus** [pipelinedb/pipelinedb#1091]
Apparently, if your CV definiton contains more than one reference to the arrival_timestamp pseudo-column, you get a completely bogus error:

pipeline=# \d seenstream
      Special relation "public.seenstream"
      Column       |            Type             
-------------------+-----------------------------
 user_id           | integer
 page_id           | integer
 ts                | timestamp with time zone
 arrival_timestamp | timestamp(0) with time zone

pipeline=# create continuous view seenfeed as select user_id, page_id, arrival_timestamp as ts from seenstream where arrival_timestamp >= ( clock_timestamp() - interval '90 minutes' );
ERROR:  column "arrival_timestamp" does not exist
LINE 1: ...id, arrival_timestamp as ts from seenstream where arrival_ti...
                                                             ^
pipeline=# create continuous view seenfeed as select user_id, page_id from seenstream where arrival_timestamp >= ( clock_timestamp() - interval '90 minutes' );
CREATE CONTINUOUS VIEW
pipeline=# 

Being able to access and store the arrival_timestamp is pretty vital to most practical uses of streams; fix?

**Comment by usmanm** [comment]
We're doing some major refactoring on the analyzer. This should be fixed once that gets in.
