### ISSUE TITLE
Smarter timestamp truncation for sliding windows

### ISSUE THREAD

**Issue by usmanm** [pipelinedb/pipelinedb#1097]
Rather than defaulting to second, so that we minimize the fan in size on the read path and decrease the cardinality of the mat rel.

**Comment by derekjn** [comment]
It's probably reasonable to just make the step size one unit of granularity lower than the window's unit. e.g. an n-day window has a step size of 1 hour, n-hour window has a step size of 1 minute, etc.

**Comment by usmanm** [comment]
Makes sense. Will submit a PR in a little bit.
