### ISSUE TITLE
File permissions in rpm packages

### ISSUE THREAD

**Issue by dev1ant** [pipelinedb/pipelinedb#1129]
After installing `pipelinedb-0.8.0-centos6-x86_64.rpm` you are not able to initialize the database because everything inside `/usr/lib/pipelinedb/` has 700 permissions with root owner:
```
root@pgtest03h ~ # ls -ld /usr/lib/pipelinedb/*
drwx------ 2 root root 4096 Aug 24 10:37 /usr/lib/pipelinedb/bin
drwx------ 5 root root 4096 Aug 24 10:37 /usr/lib/pipelinedb/include
drwx------ 6 root root 4096 Aug 24 10:37 /usr/lib/pipelinedb/lib
drwx------ 4 root root 4096 Aug 24 10:37 /usr/lib/pipelinedb/share
root@pgtest03h ~ #
```

So you can't execute `/usr/lib/pipelinedb/bin/pipeline-init` from any user except root, but root is of course prohibited to do that.

**Comment by derekjn** [comment]
Confirmed that it only happens on CentOS 6. All CentOS versions use the same packaging script, so `rpmbuild` on CentOS 6 must have different defaults or arguments. Should be fixed shortly.
