### ISSUE TITLE
Instructions for installation on OSX not complete

### ISSUE THREAD

**Issue by mindreframer** [pipelinedb/pipelinedb#1133]
I had to install following brew packages to initialize the data folder: 

    brew install json-c
    brew install freexl
    brew install geos
    brew install libgeotiff

maybe this can be included in the readme or docs...

**Comment by usmanm** [comment]
Done: http://docs.pipelinedb.com/installation.html#os-x

**Comment by mindreframer** [comment]
awesome! :+1:
