### ISSUE TITLE
Issue with subselects in continuous view's target list

### ISSUE THREAD

**Issue by derekjn** [pipelinedb/pipelinedb#1139]
ERROR: could not open file "base/14081/16394": No such file or directory
WARNING: 2 registered snapshots seem to remain after cleanup
WARNING: snapshot 0x1ce3270 still active
with the following code (basically a select from another view in a continuous view)
https://www.dropbox.com/s/o5fr27l8sx1shna/pipelinedb.ipynb?dl=0

The problem seems to be a result of selecting from a continuous view in a continuous view's target list:

```
CREATE CONTINUOUS VIEW prediction_snapshots AS
SELECT  id, item_id, tracked_user_id, mood_config_id, created, (SELECT user_profile FROM test t WHERE t.item_id = item_id)
FROM item_mood_action
```

**Comment by usmanm** [comment]
This can probably be written as a stream-table join?

**Comment by derekjn** [comment]
Yea, or by selecting in the insert statement. We just need to throw an error to prevent breakage.

**Comment by derekjn** [comment]
Actually it seems like subselects in the TL should just be supported. It might not always be the best way to do something, but it should probably still work properly.

**Comment by derekjn** [comment]
Let's disallow this for now, for a couple of reasons:

* It would significantly complicate the analyzer
* This behavior can already be achieved cleanly with a stream-table join
* It could get a continuous view into a nasty state, because `SELECTs` in target lists are already restrictive. For example, they can only return a single column and row
