### ISSUE TITLE
Optimize HLL unions and HLLs for low cardinalities

### ISSUE THREAD

**Issue by usmanm** [pipelinedb/pipelinedb#1154]

**Comment by derekjn** [comment]
We should probably just store actual values up until a certain size, and only degrade to an HLL representation after that. For `varlena` types, 32-bit hashes would probably be sufficient.

**Comment by usmanm** [comment]
Yea, that probably is a good idea. We can store up to 3k raw values before upgrading to an HLL (12k). A simple insertion sort routine should probably be enough as well. The only problem is that we use 64 bit hashes in our HLL so to work with that we might have to store 64 bit hashes instead of 32 bit ones.
