### ISSUE TITLE
SELECT COUNT(DISTINCT field) results wrong

### ISSUE THREAD

**Issue by Degola** [pipelinedb/pipelinedb#1181]
Hey guys,

we found an issue with SELECT DISTINCT(field) where 1,000 single inserts with unique values result into slightly different counts (in 3 repeated tests between 0.4% and 1.2%).

The following test scenario we have:

```SQL
CREATE STREAM events_heartbeat (
  product_id VARCHAR(24),
  unique_user_id VARCHAR(24),
  insert_date TIMESTAMP WITH TIME ZONE
);
```

from which we create the following continuous view:
```SQL
CREATE CONTINUOUS VIEW
  statistics__user_activity__hourly
AS SELECT
  product_id::VARCHAR(24) AS value__product_id,
  DATE_TRUNC('hour', insert_date) AS date__year_month_day_hour,
  COUNT(DISTINCT unique_user_id) AS count_distinct__unique_users,
  COUNT(*) AS value__unique_users_events
FROM
  events_heartbeat
GROUP BY
  value__product_id,
  date__year_month_day_hour;
```

We did 1,000 insert operations:
```SQL
PreparedStatement stmt = connection.prepareStatement("INSERT INTO events_heartbeat (product_id, unique_user_id, insert_date) VALUS (?, ?, ?)");
stmt.setString(1, event.getProductId());
stmt.setString(2, event.getUniqueUserId());
stmt.setTimestamp(3, new Timestamp(event.getTimestamp().getTime()));
stmt.execute();
```

We ensured that the value for unique_user_id are 1,000 unique values.

We got the following results (from 2 different runs):
```
# select * from statistics__user_activity__aggregation_hourly;
    value__product_id     | date__year_month_day_hour | count_distinct__unique_users | value__unique_users_events
--------------------------+---------------------------+------------------------------+----------------------------
 55f1e4ee9ac25e7b037b23c7 | 2015-09-21 09:00:00+00    |                         1004 |                       1000
(1 row)

# select * from statistics__user_activity__aggregation_hourly;
    value__product_id     | date__year_month_day_hour | count_distinct__unique_users | value__unique_users_events
--------------------------+---------------------------+------------------------------+----------------------------
 55f1e4ee9ac25e7b037b23c7 | 2015-09-21 10:00:00+00    |                          990 |                       1000
```

Before testing the database server was restarted and the database freshly initialized.

We're using Ubuntu 14.04.3 LTS, for pipelinedb we use the packagecloud.io repository and the latest version (today morning freshly installed):
```bash
# dpkg -s pipelinedb
Package: pipelinedb
Status: install ok installed
Priority: optional
Section: database
Installed-Size: 84055
Maintainer: PipelineDB <packaging@pipelinedb.com>
Architecture: amd64
Version: 0.8.1-1
Depends: libc6 (>= 2.17), libgcc1 (>= 1:4.1.1), libreadline6 (>= 6.0), libstdc++6 (>= 4.6), libxml2 (>= 2.7.4), zlib1g (>= 1:1.2.2)
Description: streaming SQL database
 PipelineDB is a streaming SQL database that runs SQL queries continuously
 on streams, incrementally storing the results in tables.
Homepage: http://pipelinedb.com
```

Is that an expected behavior and/or a configuration problem on our side or is that a bug?

Best,

Sebastian

**Comment by usmanm** [comment]
You mean `SELECT count(DISTINCT ...)`?

**Comment by derekjn** [comment]
Hi @Degola,

`COUNT(DISTINCT ...)` internally [uses HyperLogLog](http://docs.pipelinedb.com/aggregates.html#general-aggregates), which is expected to have a small margin of error. Are the inputs you're using across different test runs identical? If they are different in any way, then a slightly different margin would be expected.

**Comment by Degola** [comment]
@usmanm: sorry, yes, of course, I meant SELECT COUNT(DISTINCT ...).
@derekjn: I missed that part in the documentation. We experienced different results but 0.2% error rate was the best we achieved, right now we get around 1% error rate with 1,000 values. is there a way to decrease the error rate by pipeline configuration?

**Comment by derekjn** [comment]
The error rate should converge on about 0.2% as the number of unique values seen increases. Do you expect to never add more than 1,000 unique values?

We've been thinking of adding an `exact_distinct` function for this use case.

**Comment by derekjn** [comment]
Actually @Degola the error rate will converge on about 0.8%, so 99.2% accurate.

**Comment by Degola** [comment]
Hey, the exact_distinct function sounds great and would be lovely to have that. 
The problem with COUNT(DISTINCT *) is, that we also using grouping with it, e.g. how many unique users spent revenue in within the last 7 days by country and marketing partner where this inaccuracy can become misleading.

**Comment by derekjn** [comment]
Thanks for the feedback @Degola. I've created an issue for this: https://github.com/pipelinedb/pipelinedb/issues/1201

Any further feedback or input would be greatly appreciated!
