### ISSUE TITLE
Matrel columns should not have pseudo-types

### ISSUE THREAD

**Issue by usmanm** [pipelinedb/pipelinedb#1187]
```
usmanm=# \|
                    List of continuous views
 id | schema | name |                   query                    
----+--------+------+--------------------------------------------
 14 | public | v    |  SELECT array_agg(x::integer) AS array_agg+
    |        |      |    FROM ONLY stream
(1 row)

usmanm=# \d+ v_mrel0;
                          Table "public.v_mrel0"
  Column   |   Type   | Modifiers | Storage  | Stats target | Description 
-----------+----------+-----------+----------+--------------+-------------
 array_agg | anyarray |           | extended |              | 
Options: fillfactor=50
```

**Comment by derekjn** [comment]
I'm not sure that this is really an issue. `array_agg` actually uses a `transout` function because its transition type is an internal `ArrayBuildState`, so this is pretty much the same thing as how we serialize other internal transition states as `bytea`.

**Comment by usmanm** [comment]
The problem is that this doesn't play well with `pg_dump` and `pg_restore`.

**Comment by derekjn** [comment]
Ah gotcha, so maybe we're better off just serializing these as `bytea`. The alternative is to dynamically select the correct type whenever we look at the combine's state type, which seems less maintainable.

**Comment by usmanm** [comment]
`bytea` should work, but then our `finalize` function becomes different and will have the signature `array_out(bytea)` rather than `array_out(anyarray)`. Selecting the type dynamically has the same problem in the sense that the finalize function will need to have a signature like `array_out(int[])`. Arrays in general are pretty half assed in Postgres. We could fix `pg_dump` and `pg_restore` but that would mean our stuff's incompatible with vanilla Postgres which is far from ideal. Not entirely sure what the best way to fix this is.

**Comment by derekjn** [comment]
Well it would be `array_out(combinein(bytea))` which is fine, right?

**Comment by usmanm** [comment]
You're right! `bytea` transition state makes sense to me.
