### ISSUE TITLE
Derived streams

### ISSUE THREAD

**Issue by derekjn** [pipelinedb/pipelinedb#1200]
It would be great to have a "derived streams" abstraction in order to provide further processing on a stream without having to define that processing in the continuous view definition. This can become repetitive, particularly for JSON unpacking. Consider the CV:

```
CREATE CONTINUOUS VIEW v0 AS
    SELECT f0, f1, COUNT(*) FROM
        (SELECT 
            (payload->>'k0')::integer AS f0,
            (payload->>'k1')::integer AS f1 FROM stream)
    GROUP BY f0, f1;
```
It is often the case another CV will perform similar unpacking on the same stream, which would require some duplication of the unpacking. A better approach would be something like:

```
CREATE STREAM unpacked AS 
    SELECT
        (payload->>'k0')::integer AS f0,
        (payload->>'k1')::integer AS f1 FROM stream;

CREATE CONTINUOUS VIEW v0 AS
    SELECT f0, f1, COUNT(*) FROM unpacked GROUP BY f0, f1;
CREATE CONTINUOUS VIEW v1 AS
    SELECT max(f0), sum(f1) FROM unpacked;
...
```

**Comment by geon** [comment]
Also useful for cleaning up ugly data, like substituting magic numbers with enums or converting units.

**Comment by geon** [comment]
It seems to me, that if they support SELECT, WHERE, UNION and window functions, you would have pretty much complete stream processing.

**Comment by derekjn** [comment]
Yep, `UNION` would also be interesting for derived streams. We have that on the roadmap: #1033. Thanks for the feedback!

**Comment by geon** [comment]
Cool!

JOIN on tables (including continuous views) would probably be crucial to clean up data that originally expected s diffrent database structure.

 Lets say you import a product list  with a category id,  but you were data structure  use  tags.  You would have to join in a table with translations from category id to  multiple tag ids, and emit  multiple rows for each product.

**Comment by usmanm** [comment]
We should combine this with the continuous transforms feature.
