### ISSUE TITLE
Add support for exact distincts counting

### ISSUE THREAD

**Issue by derekjn** [pipelinedb/pipelinedb#1201]
Since `COUNT(DISTINCT ...)` implicitly uses HLLs, we should provide users a way to explicitly use exact distinct counting when needed. Since we've talked about adding a set type, there is probably some overlap there:

    SELECT exact_count_distinct(x), ...
    SELECT set_cardinality(set_agg(x)), ...

It would probably be best to implement this generically with a `set` type with associated aggregates and functions. `exact_count_distinct(x)` could then simply be rewritten to `set_cardinality(set_agg(x))`. We also might want to add analogous bitmap set functionality for cases in which users know they'll be working with small integers.

**Comment by usmanm** [comment]
Don't think we need this for 0.8.2?
