### ISSUE TITLE
Allow indexes to be created directly on continuous views

### ISSUE THREAD

**Issue by EliSnow** [pipelinedb/pipelinedb#1206]
Currently if someone wants to index their continuous view they have to add an index on `<continuous view name>_mrel0`. This has two downsides: 1) It's not intuitive and 2) it is impossible to index a column represented by a transition state.

**Comment by EliSnow** [comment]
An alternative fix for point 2 above would be to expose a public function which would take a transition state from the `_mrel` table and return the consumable output.

**Comment by usmanm** [comment]
Hey @EliSnow, you can use the `finalize` function to transform the transition state into the actual value of the aggregate. But you wouldn't be able to `combine` the finalized.

**Comment by usmanm** [comment]
Also, is this urgent for you guys? I can mark it as high priority and get it out soon.

**Comment by EliSnow** [comment]
No, not urgent at all. I will look at the `finalize` function. I guess I missed that one.

**Comment by usmanm** [comment]
I think we might just have not documented it--oops.
