### ISSUE TITLE
first and last aggregates

### ISSUE THREAD

**Issue by dev1ant** [pipelinedb/pipelinedb#1210]
Something like the following:
https://wiki.postgresql.org/wiki/First/last_%28aggregate%29
https://github.com/wulczer/first_last_agg.git

**Comment by usmanm** [comment]
This is tricky because the ordering of tuples is undefined in streams.

**Comment by dev1ant** [comment]
Doesn't arrival_timestamp provide ordering?

**Comment by usmanm** [comment]
Yea, if that's what you had in mind, then we can support these aggregates.

**Comment by dev1ant** [comment]
Yep, thats it. Thanks in advance.

**Comment by usmanm** [comment]
No worries. Will get it in sometime today.

**Comment by derekjn** [comment]
I'm thinking a signature such as: `first(ts timestamp, value any)` and `first(value any)` for implicit arrival ordering.

**Comment by usmanm** [comment]
We could even have something like `first(cmp_value any, value any)` which would behave the same way as `first(value any) ORDER by cmp_value`.

**Comment by derekjn** [comment]
@dev1ant the way we ended up implementing this is with keyed min/max aggregates. So for first and last arrival, you can now do:

    ...
    SELECT keyed_min(arrival_timestamp, value), keyed_max(arrival_timestamp, value)
    FROM stream
    ...

Obviously this lets you use any field you want to provide ordering. Thanks for the useful feature request!

**Comment by dev1ant** [comment]
Cool, thanks. Will try it soon.
