### ISSUE TITLE
make world error

### ISSUE THREAD

**Issue by digoal** [pipelinedb/pipelinedb#1217]
test_tdigest.o: In function `run_tdigest_test_on_distribution':
test_tdigest.c:(.text+0x444): undefined reference to `ck_assert_int_lt'
test_hll.o: In function `test_card_caching':
test_hll.c:(.text+0xa96): undefined reference to `ck_assert_uint_eq'
test_hll.o: In function `test_murmurhash64a_varlen':
test_hll.c:(.text+0x1391): undefined reference to `ck_assert_uint_eq'
test_hll.c:(.text+0x13be): undefined reference to `ck_assert_uint_eq'
test_hll.o: In function `test_murmurhash64a':
test_hll.c:(.text+0x1441): undefined reference to `ck_assert_uint_eq'
test_hll.c:(.text+0x146e): undefined reference to `ck_assert_uint_eq'
test_hll.o:test_hll.c:(.text+0x14a9): more undefined references to `ck_assert_uint_eq' follow
test_bloom.o: In function `test_false_positives':
test_bloom.c:(.text+0xe6): undefined reference to `ck_assert_int_le'
collect2: error: ld returned 1 exit status
make[2]: *** [unit_tests] Error 1
make[2]: Leaving directory `/opt/soft_bak/pipelinedb/src/test/unit'
make[1]: *** [all-test/unit-recurse] Error 2
make[1]: Leaving directory `/opt/soft_bak/pipelinedb/src'
make: *** [world-src-recurse] Error 2

**Comment by derekjn** [comment]
Hi @digoal , do you have `libcheck` installed? Can you show us the output of `./configure`?

**Comment by digoal** [comment]
yes , i install libcheck, make it's ok,but when i make install contrib/

there is some error, Makefile has files set 
DATA = citext--1.0.sql citext--1.1.sql citext--1.0--1.1.sql \
       citext--1.1--1.0.sql citext--unpackaged--1.0.sql

but some files not exists in contrib/citext.

make[1]: *** No rule to make target `citext--1.0.sql', needed by `installdata'.  Stop.
make[1]: Leaving directory `/opt/soft_bak/pipelinedb/contrib/citext'
make: *** [install-citext-recurse] Error 2

**Comment by derekjn** [comment]
Somehow that particular contrib module was out of sync with upstream. I pushed a fix to `master` so `make install` should work properly now.
