### ISSUE TITLE
Combiner should combine as many times in memory as possible before committing

### ISSUE THREAD

**Issue by derekjn** [pipelinedb/pipelinedb#1224]
Flush everything to disk after a configurable amount of time has passed, or if the amount of memory consumed exceeds the combiner's limit.

**Comment by usmanm** [comment]
Let's use a config param called `continuous_query_commit_interval`.

**Comment by derekjn** [comment]
The existing branch for this got too far out of sync with all of the new changes to the cont executor, so it needs to get rewritten.

**Comment by usmanm** [comment]
Do you still have the existing branch? I can prolly port over the changes pretty easily because prolly the conflicts are mostly in the new `cont_execute` stuff.

**Comment by derekjn** [comment]
I don't actually have it anymore. It would probably be easiest to just rewrite it to fit the new `cont_execute` design anyways. It was only ~200 lines of changes or so...

**Comment by usmanm** [comment]
This change doesn't seem to play well with the group cache. I think we can just rip that out since we won't be looking up tuples already in-memory anyway. Thoughts @derekjn?

**Comment by derekjn** [comment]
Let's rip the group cache out with this change.
