### ISSUE TITLE
cann't use all CPU  in my environment

### ISSUE THREAD

**Issue by digoal** [pipelinedb/pipelinedb#1226]
HI,
   I test pipelinedb in a machine with 2 CPU: E5-2650 v2 @ 2.60GHz
   There are 32 cores, but when i use pgbench test pipelinedb's performance , i found CPU 92% IDLE,
   And this time about 60W rows calculated per second . 
   When I init 10 instances, and start 10 pipelinedb instance in the machine, and use pgbench test the 10 instances at the same time, there will about 600W rows calculated per second.

   is it a pipelinedb performance problem?

**Comment by usmanm** [comment]
Have you increased the values for config params `continuous_query_num_combiners` and `continuous_query_num_workers`?

**Comment by digoal** [comment]
也是，continuous_query_num_combiners and continuous_query_num_workers increased to 32 , the performance also equal to default set。

**Comment by usmanm** [comment]
Can you share your workload with us?

**Comment by digoal** [comment]
CREATE CONTINUOUS VIEW v0 AS SELECT COUNT(*) FROM stream; 
CREATE CONTINUOUS VIEW v1 AS SELECT sum(x::int),count(*),avg(y::int) FROM stream; 
CREATE CONTINUOUS VIEW v001 AS SELECT sum(x::int),count(*),avg(y::int) FROM stream1;
CREATE CONTINUOUS VIEW v002 AS SELECT sum(x::int),count(*),avg(y::int) FROM stream2; 
CREATE CONTINUOUS VIEW v003 AS SELECT sum(x::int),count(*),avg(y::int) FROM stream3;

activate;

pdb@digoal-> vi test.sql
insert into stream(x,y,z) select generate_series(1,1000),1,1;
insert into stream1(x,y,z) select generate_series(1,1000),1,1;
insert into stream2(x,y,z) select generate_series(1,1000),1,1;
insert into stream3(x,y,z) select generate_series(1,1000),1,1;

pdb@digoal-> /opt/pgsql/bin/pgbench -M extended -n -r -f ./test.sql -P 1 -c 10 -j 10 -T 100000
progress: 1.0 s, 133.8 tps, lat 68.279 ms stddev 58.444
progress: 2.0 s, 143.9 tps, lat 71.623 ms stddev 53.880
progress: 3.0 s, 149.5 tps, lat 66.452 ms stddev 49.727
progress: 4.0 s, 148.3 tps, lat 67.085 ms stddev 55.484
progress: 5.1 s, 145.7 tps, lat 68.624 ms stddev 67.795

with parallel. 
pipeline-init ..... 10 instance.
and then:

/opt/pgsql/bin/pgbench -M extended -n -r -f ./test.sql -P 1 -c 10 -j 10 -T 100000 -p 1950 &
/opt/pgsql/bin/pgbench -M extended -n -r -f ./test.sql -P 1 -c 10 -j 10 -T 100000 -p 1950 &
/opt/pgsql/bin/pgbench -M extended -n -r -f ./test.sql -P 1 -c 10 -j 10 -T 100000 -p 1950 &
/opt/pgsql/bin/pgbench -M extended -n -r -f ./test.sql -P 1 -c 10 -j 10 -T 100000 -p 1950 &
/opt/pgsql/bin/pgbench -M extended -n -r -f ./test.sql -P 1 -c 10 -j 10 -T 100000 -p 1950 &
/opt/pgsql/bin/pgbench -M extended -n -r -f ./test.sql -P 1 -c 10 -j 10 -T 100000 -p 1950 &
/opt/pgsql/bin/pgbench -M extended -n -r -f ./test.sql -P 1 -c 10 -j 10 -T 100000 -p 1950 &
/opt/pgsql/bin/pgbench -M extended -n -r -f ./test.sql -P 1 -c 10 -j 10 -T 100000 -p 1950 &

**Comment by derekjn** [comment]
This is probably related to #1223. @digoal can you show us the output of `SELECT pipeline_version()`? If you haven't already, you should download the latest nightly build.

**Comment by usmanm** [comment]
The query you're running also isn't parallelizable for combiners because there's only a single row in the materialization table (there are no groups). As a result all writes to it are handled by a single process. That obviously doesn't hold true anymore when you run 10 separate instances of the same query.

**Comment by digoal** [comment]
pipeline=# select pipeline_version();
                                                                          pipeline_version                                                                          
--------------------------------------------------------------------------------------------------------------------------------------------------------------------
 PipelineDB 0.8.1 at revision e708e9dee317970e0c60b18a9ffac90093fc3d2f on x86_64-unknown-linux-gnu, compiled by gcc (GCC) 4.4.7 20120313 (Red Hat 4.4.7-11), 64-bit
(1 row)

**Comment by usmanm** [comment]
You're on an older version without the fix that @derekjn mentioned. Can you download the nightly build from https://www.pipelinedb.com/download and try again?

**Comment by digoal** [comment]
OK, thanks. 
the old version use this test case, also can't use all CPU.

CREATE CONTINUOUS VIEW vv0 AS SELECT COUNT(*) FROM stream0; 
CREATE CONTINUOUS VIEW vv1 AS SELECT COUNT(*) FROM stream1; 
CREATE CONTINUOUS VIEW vv2 AS SELECT COUNT(*) FROM stream2; 
CREATE CONTINUOUS VIEW vv3 AS SELECT COUNT(*) FROM stream3; 
CREATE CONTINUOUS VIEW vv4 AS SELECT COUNT(*) FROM stream4; 
CREATE CONTINUOUS VIEW vv5 AS SELECT COUNT(*) FROM stream5; 
CREATE CONTINUOUS VIEW vv6 AS SELECT COUNT(*) FROM stream6; 
CREATE CONTINUOUS VIEW vv7 AS SELECT COUNT(*) FROM stream7; 
CREATE CONTINUOUS VIEW vv8 AS SELECT COUNT(*) FROM stream8; 
CREATE CONTINUOUS VIEW vv9 AS SELECT COUNT(*) FROM stream9; 

vi t0.sql
insert into stream0(x) select generate_series(1,10000);
vi t1.sql
insert into stream1(x) select generate_series(1,10000);
vi t2.sql
insert into stream2(x) select generate_series(1,10000);
vi t3.sql
insert into stream3(x) select generate_series(1,10000);
vi t4.sql
insert into stream4(x) select generate_series(1,10000);
vi t5.sql
insert into stream5(x) select generate_series(1,10000);
vi t6.sql
insert into stream6(x) select generate_series(1,10000);
vi t7.sql
insert into stream7(x) select generate_series(1,10000);
vi t8.sql
insert into stream8(x) select generate_series(1,10000);
vi t9.sql
insert into stream9(x) select generate_series(1,10000);


/opt/pgsql/bin/pgbench -M extended -n -r -f ./t0.sql -P 1 -c 10 -j 10 -T 100000 &
/opt/pgsql/bin/pgbench -M extended -n -r -f ./t1.sql -P 1 -c 10 -j 10 -T 100000 &
/opt/pgsql/bin/pgbench -M extended -n -r -f ./t2.sql -P 1 -c 10 -j 10 -T 100000 &
/opt/pgsql/bin/pgbench -M extended -n -r -f ./t3.sql -P 1 -c 10 -j 10 -T 100000 &
/opt/pgsql/bin/pgbench -M extended -n -r -f ./t4.sql -P 1 -c 10 -j 10 -T 100000 &
/opt/pgsql/bin/pgbench -M extended -n -r -f ./t5.sql -P 1 -c 10 -j 10 -T 100000 &
/opt/pgsql/bin/pgbench -M extended -n -r -f ./t6.sql -P 1 -c 10 -j 10 -T 100000 &
/opt/pgsql/bin/pgbench -M extended -n -r -f ./t7.sql -P 1 -c 10 -j 10 -T 100000 &
/opt/pgsql/bin/pgbench -M extended -n -r -f ./t8.sql -P 1 -c 10 -j 10 -T 100000 &
/opt/pgsql/bin/pgbench -M extended -n -r -f ./t9.sql -P 1 -c 10 -j 10 -T 100000 &

**Comment by digoal** [comment]
Use the nightly rpm, have another problem

progress: 1.0 s, 130.0 tps, lat 217.263 ms stddev 25.914
progress: 2.0 s, 145.0 tps, lat 218.884 ms stddev 32.425
progress: 3.0 s, 148.0 tps, lat 220.116 ms stddev 34.192
progress: 4.0 s, 144.0 tps, lat 219.519 ms stddev 34.267
progress: 5.0 s, 145.0 tps, lat 219.749 ms stddev 33.316
progress: 6.0 s, 148.0 tps, lat 219.895 ms stddev 37.619
progress: 7.0 s, 142.0 tps, lat 220.435 ms stddev 31.989
progress: 8.0 s, 41.0 tps, lat 226.084 ms stddev 35.553
progress: 9.0 s, 0.0 tps, lat -nan ms stddev -nan
progress: 10.0 s, 0.0 tps, lat -nan ms stddev -nan
progress: 11.0 s, 0.0 tps, lat -nan ms stddev -nan
progress: 12.0 s, 0.0 tps, lat -nan ms stddev -nan
progress: 13.0 s, 0.0 tps, lat -nan ms stddev -nan
progress: 14.0 s, 0.0 tps, lat -nan ms stddev -nan
progress: 15.0 s, 0.0 tps, lat -nan ms stddev -nan
progress: 16.0 s, 0.0 tps, lat -nan ms stddev -nan
progress: 17.0 s, 0.0 tps, lat -nan ms stddev -nan
progress: 18.0 s, 0.0 tps, lat -nan ms stddev -nan
progress: 19.0 s, 0.0 tps, lat -nan ms stddev -nan
progress: 20.0 s, 0.0 tps, lat -nan ms stddev -nan
progress: 21.0 s, 0.0 tps, lat -nan ms stddev -nan
progress: 22.0 s, 0.0 tps, lat -nan ms stddev -nan
progress: 23.0 s, 0.0 tps, lat -nan ms stddev -nan

**Comment by usmanm** [comment]
Using the same workload as you described previously?

**Comment by digoal** [comment]
yes
