### ISSUE TITLE
Missing init.d scripts for debian/ubuntu

### ISSUE THREAD

**Issue by robertobarreda** [pipelinedb/pipelinedb#1248]
Debian package doesn't provide init scripts.

https://github.com/pipelinedb/pipelinedb/blob/master/contrib/start-scripts/linux 
doesn't work and there isn't any documentation.

Also pg_ctl alias is missing

**Comment by derekjn** [comment]
Hi @robertobarreda,

We don't currently include `start-script` analogues with PipelineDB. Can you elaborate on what you mean when you say there is no documentation?

Instructions on how to install and run PipelineDB can be found here: http://docs.pipelinedb.com/installation.html#running-pipelinedb

**Comment by robertobarreda** [comment]
@derekjn sorry, my issue description was not very clear about that.
I meant that the start-script example I mentioned above isn't exactly compliance with the documentation (it uses the standard pg tools), but even changing the paths is not working on ubuntu/debian.

Are you planning to provide these scripts or do you officially recommend any way to keep the service running between reboots?

**Comment by derekjn** [comment]
We will include a version of these scripts that work with PipelineDB. We don't have any official recommendation about automatic startup after reboot, but `start-scripts` should work fine for the time being if you create a symlink from `pg_ctl` to `pipeline-ctl`.

Alternatively, you can set `PGCTL` to `/path/to/pipelinedb/bin/pipeline-ctl`. Let me know if either of those approaches works. Thanks!

**Comment by derekjn** [comment]
#1029

**Comment by robertobarreda** [comment]
@derekjn we can close this issue as duplicate of #1029
