### ISSUE TITLE
Installing failure on OS X with El Capitan

### ISSUE THREAD

**Issue by jamesthompson** [pipelinedb/pipelinedb#1249]
I'm getting 
```
This package is incompatible with this version of OS X and may fail to install.
```
notifications and an error when I try to install the latest OS X version from the download page.

Trying the `install anyway` option results in 
```
The Installer encountered an error that caused the installation to fail. Contact the software manufacturer for assistance.
```

I'm running: OS X El Capitan 10.11 (15A284)

Would love to be able to run this natively on the Mac instead of in a docker container so I can more straightforwardly try out the `pipeline_kafka` plugin.

Thanks a lot in advance for your help!

**Comment by simion** [comment]
Still failing, same error, OSX El capitan 10.11.2 (15C50)

**Comment by derekjn** [comment]
We just updated the OSX package to work with El Capitan. The new package is now available as a nightly release on our downloads page:

https://www.pipelinedb.com/download
