### ISSUE TITLE
rule or trigger cann't used on merge table & continue view?

### ISSUE THREAD

**Issue by digoal** [pipelinedb/pipelinedb#1252]
HI,
   I like to use trigger or rule to partition the merge table or continue view.
   This is the thinking:
   I should store the origin data and store statistic data at same time ,so i create a continue view for origin and some rela statistic continue view for purpose.
   CREATE CONTINUOUS VIEW imps2_origin AS SELECT id::int,arrival_timestamp FROM imps_stream;
   CREATE CONTINUOUS VIEW imps2_c1 AS SELECT count(*),date(arrival_timestamp) FROM imps_stream group by 2;
   ...... 
   pipeline=# insert into imps_stream (id,x) values (1),(2);
INSERT 0 2
pipeline=# select * from imps2_origin;
 id |       arrival_timestamp       
----+-------------------------------
  2 | 2015-11-04 14:10:25.085172+08
  1 | 2015-11-04 14:10:25.085145+08
(2 rows)

pipeline=# select * from imps2_c1;
 count |    date    
-------+------------
     2 | 2015-11-04
(1 row)

and then:
pipeline=# create table imps3(like imps2_origin);  -- this is can a partition table , there i ignore the so many code. 
CREATE TABLE

pipeline=# create or replace function tg1 () returns trigger as $$
 declare
 begin
 insert into imps3(id,arrival_timestamp) values (new.id,new.arrival_timestamp);
 return null;
 end;
 $$ language plpgsql;

pipeline=# create trigger tg1 before insert on imps2_origin_mrel0 for each row execute procedure tg1();
CREATE TRIGGER

pipeline=# insert into imps_stream (id,x) values (1),(2);
INSERT 0 2

the trigger not trigged . 
pipeline=# select * from imps2_origin_mrel0 ;
 id |       arrival_timestamp       
----+-------------------------------
  2 | 2015-11-04 14:10:25.085172+08
  1 | 2015-11-04 14:10:25.085145+08
  1 | 2015-11-04 14:13:31.090223+08
  2 | 2015-11-04 14:13:31.090347+08
(4 rows)

pipeline=# select * from imps3
pipeline-# ;
 id | arrival_timestamp 
----+-------------------
(0 rows)

So, what can i do ,if i should store origin data into my partition table?
thanks

**Comment by derekjn** [comment]
@digoal currently it is not possible to use triggers on streams, continuous views or materialization tables. What it seems like you're trying to do here is store all events from a stream in a continuous view, and then replicate them out to a partitioned table, is that correct?

If so, you can probably write tuples directly to the partitioned table and use a trigger on it that then writes to the stream. Would that work?
