### ISSUE TITLE
DROP STREAM error

### ISSUE THREAD

**Issue by derekjn** [pipelinedb/pipelinedb#1257]
```
DROP STREAM foo_bar;
ERROR: unrecognized object type: 36
```

**Comment by usmanm** [comment]
@icylisper When you get the chance, can you put the repro steps here?

**Comment by icylisper** [comment]
Hmm, if I enable continuous_queries_adhoc_enabled=on, that is when I get the error.

**Comment by derekjn** [comment]
Strange, I can't repro this. @icylisper can you try to repro this from a fresh database (`pipeline-init -D`) and let us know the exact steps you took?

Also, can you show us the output of `SELECT pipeline_version()`?

**Comment by icylisper** [comment]
pipeline=> select pipeline_version();
                                                                     pipeline_version                                                                      
-----------------------------------------------------------------------------------------------------------------------------------------------------------
 PipelineDB 0.8.3 at revision ae8d8c83a4ab6c1acb0f97453476e38a593159a4 on x86_64-unknown-linux-gnu, compiled by gcc (Ubuntu 4.8.2-19ubuntu1) 4.8.2, 64-bit
(1 row)
CREATE STREAM foo_stream (
       time  TIMESTAMP,
       util FLOAT
);

pipeline=> DROP STREAM foo_stream;
ERROR:  unrecognized object type: 36

Did not matter if continuous_queries_adhoc_enabled was enabled or not.

**Comment by usmanm** [comment]
Is it possible for you to send us the binary you're using?

**Comment by icylisper** [comment]
I have emailed the tar to @derekjn .

**Comment by usmanm** [comment]
Thanks!

**Comment by derekjn** [comment]
Confirmed that this isn't an issue with the latest release.
