### ISSUE TITLE
0.8.4 results into start-up error

### ISSUE THREAD

**Issue by Degola** [pipelinedb/pipelinedb#1279]
We try to build a new docker image for the latest pipelinedb 0.8.4 version but we experience the following error:

LOG:  starting background worker process "worker0 [pipeline]"
LOG:  continuous query process "worker0 [pipeline]" running with pid 63
LOG:  continuous query scheduler process (PID 62) was terminated by signal 7: Bus error
LOG:  terminating any other active server processes
LOG:  unregistering background worker "worker0 [pipeline]"
WARNING:  terminating connection because of crash of another server process
DETAIL:  The postmaster has commanded this server process to roll back the current transaction and exit, because another server process exited abnormally and possibly corrupted shared memory.
HINT:  In a moment you should be able to reconnect to the database and repeat your command.
FATAL:  the database system is in recovery mode
.FATAL:  the database system is in recovery mode
.FATAL:  the database system is in recovery mode
.FATAL:  the database system is in recovery mode
.FATAL:  the database system is in recovery mode
.LOG:  all server processes terminated; reinitializing

We installed it with ubuntu14.04 debootstrap as source, added libxml2 library and took the .deb file from pipelinedb.com.

**Comment by derekjn** [comment]
@jberkus any idea what might be going on here?

**Comment by jberkus** [comment]
Nope.  Can I see your dockerfile and scripts?

**Comment by jberkus** [comment]
FYI, the public docker will go up when I am back in SF.  Right now I'm travelling and don't have good internet connectivity.

**Comment by usmanm** [comment]
This might have something to do with using dynamic shared memory segments.

**Comment by EliSnow** [comment]
I am getting this bus error as well with the following Dockerfile:

```
FROM debian:jessie

ENV PLDB_VERSION 0.8.4

ENV LANG en_US.utf8
ENV PGDATA /var/lib/pipeline/data

VOLUME /var/lib/pipeline/data

RUN groupadd -r pipeline && useradd -r -g pipeline pipeline \
  && apt-get update \
  && apt-get -y install wget ca-certificates locales libxml2 \
  && wget https://www.pipelinedb.com/download/${PLDB_VERSION}/debian8 -O /tmp/pipeline.deb \
#  && wget https://www.pipelinedb.com/download/nightly/debian8 -O /tmp/pipeline.deb \
  && localedef -i en_US -c -f UTF-8 -A /usr/share/locale/locale.alias en_US.UTF-8 \
  && dpkg -i /tmp/pipeline.deb \
  && rm /tmp/pipeline.deb \
  && apt-get remove -y --purge wget \
  && apt-get clean \
  && apt-get autoremove -y \
  && rm -rf /var/lib/apt/lists/*

EXPOSE 5432
```

**Comment by jberkus** [comment]
This appears to be a bug in PipelineDB.  You can test it by changing the version of PipelineDB in the pkg/docker/ to 0.8.4.  The built version of PipelineDB will fail to start:

LOG:  continuous query process "worker0 [pipeline]" running with pid 119
LOG:  continuous query scheduler process (PID 118) was terminated by signal 7: Bus error
LOG:  terminating any other active server processes
LOG:  unregistering background worker "worker0 [pipeline]"
WARNING:  terminating connection because of crash of another server process

So the contquery worker is crashing, and corrupting shared memory in the process.

**Comment by usmanm** [comment]
Thanks @jberkus; will look into this now.

**Comment by jberkus** [comment]
It's possible that this is a docker privs issue; does the new contquery worker require any special network access?

**Comment by usmanm** [comment]
We started using dynamic shared memory segments. My guess is that's what is causing this failure. We might have to play around with the `--ipc` option (https://docs.docker.com/engine/reference/run/)

**Comment by EliSnow** [comment]
I found a related issue [here](https://github.com/aptible/docker-postgresql/issues/14) with a link to a relevant discussion on the [PostgreSQL mailing list](http://www.postgresql.org/message-id/20140526072447.GL18867@alap3.anarazel.de).

**Comment by usmanm** [comment]
Thanks for sharing this @EliSnow! I'm installing Docker right now to see what's up.

**Comment by jberkus** [comment]
I tried docker run --privileged=true, and it still crashes.  Will contact docker project.

**Comment by usmanm** [comment]
I think the problem is that the default shared memory size if 64mb which is pretty small for us. We need to increase it using this build option: https://github.com/docker/docker/blob/master/api/client/build.go#L62. I have Docker 1.9.1 on my machine but it doesn't expose the -shm-size parameter. We might have to wait for the next release...

**Comment by EliSnow** [comment]
@usmanm, would mounting the host's `/dev/shm` in the container work?

**Comment by EliSnow** [comment]
Something like [this](http://stackoverflow.com/a/29177045)?

**Comment by usmanm** [comment]
That seems to fix it! 

`docker run -v /dev/shm:/dev/shm pipelinedb/pipelinedb`

**Comment by EliSnow** [comment]
@usmanm, when the `--shm-size` flag is introduced in the [next version](https://github.com/docker/docker/pull/16168) of docker, what would be a good size for PipelineDB?

**Comment by usmanm** [comment]
Each background process creates a shared memory segment of `continuous_query_ipc_shared_mem` size (defaults to 32mb). The total number of background processes running is `continuous_query_num_combiners + continuous_query_num_workers` per database. Right now there is no way to disable continuous queries on a database level, so each database will spawn that many workers even if they're just idling. We're fixing that in the next release which should be out sometime this or early next week.
