### ISSUE TITLE
Creating continuous views from continuous views

### ISSUE THREAD

**Issue by vighiosif** [pipelinedb/pipelinedb#1286]
I have a stream <s1> from which I am creating a continuous view <cv1>.
I also have a continuous view which has a structure similar to this:

```
CREATE CONTINUOUS VIEW cv2
AS SELECT [fields]
FROM s1 AS s1
JOIN cv1 AS cv1 ON s1.id = cv1.id
WHERE [condition]
```

The problem is that when I insert something in the stream, the first view cv1 is populated, but cv2 is not.

However, cv2 is populated at the second/third insert AFTER the first view has some data on which the second view is dependent upon.

**Comment by usmanm** [comment]
Hey @vighiosif, this would be a little complicated to implement under our current architecture. Could you maybe describe the problem you're trying to solve at a slightly more high-level and maybe we can figure out a workaround?

**Comment by derekjn** [comment]
Closing this out for now, we can revisit at some point if necessary.
