### ISSUE TITLE
Assertion failure when planning multiple create view statements

### ISSUE THREAD

**Issue by usmanm** [pipelinedb/pipelinedb#1293]
From @sangli00 on Gitter

I find a big bug.
if i used pgadmin3 login pipelineDB and execute sql script.
like this :
create continuoux view x1 as select xxxxxx from stream;
create continuous view x2 as select xxxxxx from stream;
...
create continuous view x10 as select xxxxxx from stream;
I need created more cv.
now ,I execute all sql script.
pipelineDB is break,is down ....
error log:
TRAP: FailedAssertion("!(list_length(parsetree_list) == 1)", File: "cont_plan.c", Line: 417, PID: 35223, Query: (null))
TRAP: FailedAssertion("!(list_length(parsetree_list) == 1)", File: "cont_plan.c", Line: 434, PID: 35222, Query: (null))
parsetree_list = pg_parse_query(view->query); we will need parse this query.
if run this sql script , a view query is so much subquery. what the fuck.....
Assert(list_length(parsetree_list) == 1); this is false . list_length(parsetree_list) = 10.
I don't know ,maybe is pgadmin3 problem,maybe pipelineDB used flex & bison create object is wrong.

**Comment by sangli00** [comment]
@usmanm  thinks . 
sometimes ,I used pgadmini3 run sql script, pipelineDB is down.
I need modify source , modify ContinuousQueryWorkerMain &ContinuousQueryCombinerMain 
add   "sleep(60);"
restart pipelinedb.  quick login pipeline and drop this continuous view.
I used \i /path/xx.sql created is OK.
I copy create script in command ,is OK.

**Comment by derekjn** [comment]
Hi @sangli00, if possible can you paste a .sql file here that reproduces this error on the `master` branch? Thanks!

**Comment by derekjn** [comment]
I haven't been able to reproduce this on `master`, closing for now.
