### ISSUE TITLE
Feature request: combine_transition_state aggregate

### ISSUE THREAD

**Issue by EliSnow** [pipelinedb/pipelinedb#1305]
From gitter, I asked:

> I have a continuous view that I was testing and I want to merge it's data into another continuous view. I could just copy data from the old continuous view's `_mrel` table into the new continuous view's `_mrel` table but then I could have duplicate aggregate data when there should be only be one row per aggregate period. Are there any functions available to merge the underlying data in the `_mrel` tables?
This is similar to using `combine` except with `combine` I'd have to do it every time I query the continuous view. I want to merge the underlying data so `combine` isn't necessary.

@usmanm, responded:

> currently there's no public interface to do this, but there's no reason it wouldn't be possible. Maybe we should add a `combine_transition_state` aggregate?

**Comment by usmanm** [comment]
@EliSnow: Turns out this should just work. If you run `combine` against the materialization table, it'll combine the transition states but not finalize them.

```
usmanm=# CREATE CONTINUOUS VIEW v AS SELECT x::int, avg(y::int) FROM stream GROUP BY x;
CREATE CONTINUOUS VIEW
usmanm=# INSERT INTO stream (x, y) VALUES (1, 4), (1, 8);
INSERT 0 2
usmanm=# INSERT INTO stream (x, y) VALUES (2, 12);
INSERT 0 1
usmanm=# SELECT * FROM v;
 x |         avg         
---+---------------------
 1 |  6.0000000000000000
 2 | 12.0000000000000000
(2 rows)

usmanm=# SELECT combine(avg) FROM v;
      combine       
--------------------
 8.0000000000000000
(1 row)

usmanm=# SELECT combine(avg) FROM v_mrel;
 combine 
---------
 {3,24}
(1 row)
```

**Comment by usmanm** [comment]
@EliSnow: Added a `pipeline_combine_table` function which should help with this. See https://github.com/pipelinedb/pipelinedb/blob/master/src/test/py/test_pipeline_funcs.py#L8.

**Comment by EliSnow** [comment]
Woah, cool!
