### ISSUE TITLE
How to turn the parameter of "continuous_queries_enabled" on?

### ISSUE THREAD

**Issue by vnnw** [pipelinedb/pipelinedb#1310]
I downloaded PIPELINEDB rpm 0.85 for Centos 6 and installed it according to the installation instruction.
I started the server, created a stream, and tried to insert some values. Then I got the warning as below:

```
pipeline=# INSERT INTO test_stream (payload) VALUES ('key test');
ERROR:  cannot insert into stream test_stream since continuous queries are disabled
HINT:  Enable continuous queries using the "continuous_queries_enabled" parameter.
```

I tried to modified "pipelinedb.conf", but the parameter seems already turned on by default.
What would be the mistakes I made here? My OS is CentOS release 6.7 (Final).

**Comment by usmanm** [comment]
Oops, need to fix that hint. You can enable continuous queries using 'ACTIVATE'.

https://www.pipelinedb.com/blog/pipelinedb-0-8-5

**Comment by vnnw** [comment]
Thank you for the lightning fast reply.
