### ISSUE TITLE
How do I create continuous view within date?

### ISSUE THREAD

**Issue by yoavlt** [pipelinedb/pipelinedb#1311]
Hi.

I want to aggregate events from 3 days ago to 10 days ago. But I couldn't implement it. How do I create the view something like that?

I tried the below.
```
create continuous view v as
select event_id, count(*)
from stream
where (arrival_timestamp > clock_timestamp() - interval '10 days') and
 (arrival_timestamp < clock_timestamp() - interval '3 days')
```

But it failed because it uses `clock_timestamp()` twice.

Thanks.

**Comment by derekjn** [comment]
Hi @yoavlt,

The easiest thing to do here would be to just create the continuous view for the last 10 days, and then create a regular view on top of that. Sliding-window continuous views expose a special `arrival_timestamp` column, so you can do this:

```
create continuous view v as
select event_id, count(*)
from stream
where (arrival_timestamp > clock_timestamp() - interval '10 days')
```
And overlay it with a regular view:

```
create continuous view overlay as
select * from v where arrival_timestamp < clock_timestamp() - interval '3 days');
```

Let us know if that works!

**Comment by yoavlt** [comment]
@derekjn Thank you for your answer. Unfortunately, it also failed. Error message is below.

Error: To include a relation in a continuous query, JOIN it with a stream.

**Comment by usmanm** [comment]
Try `CREATE VIEW overlay AS SELECT * FROM v WHERE arrival_timestamp < clock_timestamp() - interval '3 days');`. You don't need the `CONTINUOUS` keyword for overlay views.

**Comment by yoavlt** [comment]
It works! Thank you so much @usmanm :pray:
