### ISSUE TITLE
Silent data drop failure

### ISSUE THREAD

**Issue by usmanm** [pipelinedb/pipelinedb#1312]
Just this with integer instead of bigint
SELECT count(*) AS impressions,
avg( (jstimestamp::bigint/1000) - (connectStart::bigint/1000) ) AS avg_time,
min( (jstimestamp::bigint/1000) - (connectStart::bigint/1000) ) AS min_time,
max( (jstimestamp::bigint/1000) - (connectStart::bigint/1000) ) AS max_time,
percentile_cont(0.99) WITHIN GROUP (ORDER BY ( (jstimestamp::bigint/1000) - (connectStart::bigint/1000) )) AS p99_time
FROM js_stream;
then insert values like 2342342342423,999123123123123 which I just randomly picked to test out by hand and couldn't figure out why it wasn't working.

via @efrazier

**Comment by derekjn** [comment]
This isn't going to be possible without significant rework because the error happens in the stream scan, not the insert process. The error is stilled logged in the logs, which isn't ideal but at least it's not completely silent. If this issue begins to comes up frequently, we can revisit.
