### ISSUE TITLE
Custom primary key column 

### ISSUE THREAD

**Issue by dev1ant** [pipelinedb/pipelinedb#1315]
In d7846e1b45ce8e3274063b3bcebc1515db0c965d primary keys were added. What for was it made? Seems, like they are not used anywhere. Is there a way to redefine the field(s) for PK? Actually, I do add UNIQUE INDEX on matrel after creating CV for improving speed for SELECTs and would like to use it as PK if possible.

**Comment by derekjn** [comment]
Hi @dev1ant,

The purpose of adding primary keys is to lay the groundwork for future functionality. In particular, support for BDR, which requires primary keys. The PK we added is fairly small (8-byte integer), so it shouldn't affect performance meaningfully and you can still use your unique index.

Please let us know if you have any further questions about this. Thanks!

**Comment by EliSnow** [comment]
BDR is coming to vanilla pipelinedb or just enterprise?

**Comment by derekjn** [comment]
Probably both. Our philosophy is that if it works in PostgreSQL, it should work in vanilla PipelineDB.

**Comment by EliSnow** [comment]
As I understand it, BDR in it's current form requires custom code/modules to be included in the source at build time and is not expected to be built in to PostgreSQL until, at the earliest 9.6. Do you intend on including those modules in with Pipeline before they are included in PostgreSQL master?

**Comment by derekjn** [comment]
No we do not.

**Comment by usmanm** [comment]
We'll add a storage parameter that allows using an existing column as the primary key in the next release.

**Comment by EliSnow** [comment]
Another option could be if the CV has a `GROUP BY` clause, and the `SELECT` clause includes the same fields (I'm not sure why someone would not include the same fields in the `SELECT` clause, but it's possible), make those fields the PK.

**Comment by dev1ant** [comment]
`Another option could be if the CV has a GROUP BY clause, make those fields the default PK.`
+1
