### ISSUE TITLE
Continuous transforms

### ISSUE THREAD

**Issue by derekjn** [pipelinedb/pipelinedb#1317]
Users want to be able to continuously transform incoming data without storing it, and then write the transformation result out to some external datastore. This can be accomplished by storing a non-aggregate query in a catalog table `pipeline_transform`, along with a function that receives the transformation's output row as an argument:

```
CREATE CONTINUOUS TRANSFORM t AS SELECT x, func(y), foo(z) FROM stream
    THEN EXECUTE PROCEDURE external_write(output_row); 
```

If users want to do batching or something similar, we could use some kind of hearbeat parameter that would call the function periodically regardless of whether or not any new rows have arrived:

```
CREATE CONTINUOUS TRANSFORM batched_t WITH (hearbeat='5 seconds') AS
    SELECT x, func(y), foo(z) FROM stream THEN EXECUTE PROCEDURE external_write(output_row); 
```

**Comment by derekjn** [comment]
I think we should just use derived streams for this because we're adding them anyways so it wouldn't require any new syntax.

**Comment by usmanm** [comment]
But then we lose the ability to do other things then simply writing to a stream, e.g. push to Kafka etc. Maybe we should use transforms in place of derived streams?

**Comment by derekjn** [comment]
Why would we lose that ability? Functions in the target list can do whatever they want. Alternatively we can add `EXECUTE PROCEDURE` functionality to stream selects. I guess I just don't really like the idea of adding a completely new abstraction when a similar and familiar one already exists...

**Comment by derekjn** [comment]
As a random thought, after we introduce transforms it's probably going to be pretty useful to have some way to describe a system-wide stream-transform-continuous view topology. It could probably be expressed in the same way that query plans are with `EXPLAIN`

**Comment by usmanm** [comment]
We need to think of a keyword different from `TRANSFORM`, Postgres added it in 9.5 so users might get confused.

http://www.postgresql.org/docs/9.5/static/sql-createtransform.html

**Comment by loadzero** [comment]
Filter perhaps?

**Comment by usmanm** [comment]
`FILTER` is also a keyword that's already used. And a `TRANSFORM` could be a simple projection without any filtering, so it might not be the best nomenclature to adopt.
