### ISSUE TITLE
first_values ordered set aggregate

### ISSUE THREAD

**Issue by EliSnow** [pipelinedb/pipelinedb#1333]
I would like the ability to get the top n ranked rows in a CV. In vanilla Postgresql it is accomplished with:

```sql
CREATE TEMPORARY TABLE s (name text, part text, value int);
CREATE OR REPLACE VIEW v AS
SELECT
  name,
  part,
  value,
  rank
  FROM (
    SELECT
      name,
      part,
      value,
      dense_rank() OVER (PARTITION BY name, part ORDER BY value) AS rank
    FROM s) AS x
  WHERE rank <= 3;

INSERT INTO s VALUES ('foo', 'stuff', 7), ('foo', 'blah', 18), ('foo', 'jar', 8),
  ('foo', 'stuff', 123), ('foo', 'blah', 6), ('foo', 'jar', 199),
  ('foo', 'stuff', 63), ('foo', 'blah', 63), ('foo', 'jar', 9),
  ('foo', 'stuff', 44), ('foo', 'blah', 26), ('foo', 'jar', 909),
  ('foo', 'stuff', 9), ('foo', 'blah', 61), ('foo', 'jar', 2),
  ('foo', 'stuff', 1), ('foo', 'blah', 996), ('foo', 'jar', 0);
  
SELECT * FROM v;
```

PipelineDB does not allow window functions in a subquery and reports:

`subqueries in continuous views cannot contain window functions`

Perhaps PipelineDB can allow certain window functions in a subquery.

**Comment by EliSnow** [comment]
A possible solution for my use case would be to create an ordered-set aggregate (perhaps called `top_n`) which returns an array of the top *n* sorted values. I would create this aggregate myself in `sql`/`plpgsql` but I have never created an ordered-set aggregate before and with it being a relatively new feature of Postgres I'm not finding too many examples when I google it.

**Comment by usmanm** [comment]
Something like: `SELECT name, part, top_n(3) WITHIN GROUP (ORDER BY value) GROUP BY name, part`?

`top_n` might be confusing with top-K/heavy hitters which we support using Filtered Space Saving. Maybe we should use `first(n)` and `last(n)`.

**Comment by EliSnow** [comment]
That looks about like what I envisioned, though I'm not sure if the names `first` and `last` would make the most sense. Simply changing the `ORDER BY value` to `ORDER BY value DESC` would determine whether you got the first or the last.

**Comment by EliSnow** [comment]
How about `first_n` instead?

**Comment by usmanm** [comment]
Yea, `first_n` is probably better. Or maybe `first_values` akin to Postgres' `first_value` window function. 

http://www.postgresql.org/docs/9.4/static/functions-window.html

**Comment by EliSnow** [comment]
I like `first_values`

**Comment by usmanm** [comment]
Cool, we'll add this aggregate soon.

**Comment by usmanm** [comment]
This also obviates the need for `keyed_min` and `keyed_max`.

**Comment by usmanm** [comment]
It's on master now. Try it out and lemme know if it works as expected. Currently for continuous queries having multiple sort expressions don't work because of the way how Postgres orders anonymous complex (record) types.

**Comment by EliSnow** [comment]
Looking at the usage from your regression tests, this looks awesome! I won't be able to test it out for at least a week.

Can you clarify what you mean by the multiple sort expressions not working? Does that mean you cannot use multiple ordered set aggregates in the same CV?

Does `first_values` only select the value for the field being sorted or can you grab one field and sort by another field?

**Comment by usmanm** [comment]
By multiple sort expressions I mean something like: `SELECT x, first_values(2) WITHIN GROUP (ORDER BY y, z) FROM first_values_t GROUP BY x`. This works on tables right now, but not in continuous views. It's fixable, just needs a little bit of hackery. I can do it if it's needed. 

Yes, it only selects the value of the fields being sorted on.

**Comment by EliSnow** [comment]
Not having multiple sort expressions won't be a problem for me.

However, I must apologize for failing to notice the absence of two parameters in your [previous sample example](https://github.com/pipelinedb/pipelinedb/issues/1333#issuecomment-172512598), but my use case requires selecting a field which is different from the one being sorted. Something like `SELECT x, first_values(2, z) WITHIN GROUP (ORDER BY y) FROM first_values_t GROUP BY x`. I hope it doesn't take too much work to add that in :worried: .

If possible it would be nice if the second parameter would be of type `ANY` so composite types could be stored as well.

**Comment by usmanm** [comment]
Hm, I'll look into it, unsure if ordered-set aggregates even allow that. I don't think they do.

**Comment by usmanm** [comment]
You might want to look at `keyed_min` and `keyed_max` that we added a few releases ago: https://www.pipelinedb.com/blog/pipelinedb-0-8-3.

**Comment by EliSnow** [comment]
I don't think `keyed_min` and `keyed_max` fit what I'm seeking after. The window expression used in the first comment most closely demonstrates my use case.

Currently `first_values` grabs the field being sorted on. If it did support multiple sort expressions, would it then grab all of those fields?

**Comment by usmanm** [comment]
Yes multiple sort expressions means that it would grab a `record` for all those fields in the same order. See: https://github.com/pipelinedb/pipelinedb/blob/master/src/test/regress/expected/first_values.out#L39.

**Comment by EliSnow** [comment]
If the two parameter suggestion is not possible, I think multiple sort expressions would work.

**Comment by usmanm** [comment]
Ok, ticket for that is #1351.
