### ISSUE TITLE
explain continuous view syntax

### ISSUE THREAD

**Issue by guanqun** [pipelinedb/pipelinedb#1354]
Now we use ``explain continuous view (verbose on) v`` instead of the standard ``explain (verbose on) continuous view v``.

http://www.postgresql.org/docs/9.5/static/sql-explain.html

Just curious should we use the standard one?

**Comment by usmanm** [comment]
The syntax is `EXPLAIN CONTINUOUS VIEW ( options ) <view_name>`.
