### ISSUE TITLE
Join of result of a continuous view and a stream fails

### ISSUE THREAD

**Issue by LinaSchad** [pipelinedb/pipelinedb#1372]
With the following streams and continuous views and queries I never get any result, though I should.

CREATE STREAM stream1(id integer, x integer);
CREATE CONTINUOUS VIEW cv1 AS SELECT id FROM stream1 WHERE x > 5;
CREATE STREAM stream2(id integer, y integer);
CREATE CONTINUOUS VIEW cv2 AS SELECT y FROM (SELECT id FROM cv1) AS cv JOIN stream2 ON stream2.id = cv.id;"

INSERT INTO stream1(id,x) VALUES(1,10);
INSERT INTO stream2(id,y) VALUES(1,15);

When I run SELECT id FROM cv1 alone, I get a correct answer and it should be possible to join from my point of view. I hope you are able to help me, thanks :)

**Comment by derekjn** [comment]
Hi @LinaSchad, try this for `cv2`:

```
CREATE CONTINUOUS VIEW cv2 AS SELECT stream2.y FROM cv1 JOIN stream2 ON stream2.id = cv1.id;
```

That seems to work as expected.

**Comment by LinaSchad** [comment]
Hi @derekjn I tried that, but the result of `SELECT * FROM cv2` is still empty, even though I made sure of having data in both streams that could be joined. The query `SELECT * FROM cv1` results 
`id `
`1`
and a helping continuous view `CREATE CONTINUOUS VIEW cv3 AS SELECT id, y FROM stream2;` and the query `SELECT * FROM cv3` gives me
`id | y`
`1 | 20`

I would expect to get the result 
`y`
`20` 
with those intermediate results.

**Comment by derekjn** [comment]
Hi @LinaSchad, what version are you running? (`SELECT pipeline_version()`)

Here is the output that I'm seeing:

```
derek=# CREATE STREAM stream1(id integer, x integer);
CREATE STREAM
derek=# CREATE CONTINUOUS VIEW cv1 AS SELECT id FROM stream1 WHERE x > 5;
CREATE CONTINUOUS VIEW
derek=# CREATE STREAM stream2(id integer, y integer);
CREATE STREAM
derek=# CREATE CONTINUOUS VIEW cv2 AS SELECT stream2.y FROM cv1 JOIN stream2 ON stream2.id = cv1.id;
NOTICE:  consider creating an index on cv1.id for improved stream-table join performance
CREATE CONTINUOUS VIEW
derek=# 
derek=# INSERT INTO stream1(id,x) VALUES(1,10);
INSERT 0 1
derek=# INSERT INTO stream2(id,y) VALUES(1,15);
INSERT 0 1
derek=# 
derek=# SELECT * FROM cv1;
 id 
----
  1
(1 row)

derek=# SELECT * FROM cv2;
 y  
----
 15
(1 row)
```

As far as I can tell this is correct, right? If you could tell me your version and paste the verbatim output of your session that would be helpful. Thanks!

**Comment by usmanm** [comment]
If `synchronous_stream_insert` is not enabled, then what @LinaSchad is seeing could happen. The combiner process commits every `continuous_query_commit_interval` so it's possible that when you inserted into `stream2` the changes to `cv1` made by inserting into `stream1` have not been committed.
