### ISSUE TITLE
having trouble loading the kafka extension

### ISSUE THREAD

**Issue by cmollis** [pipelinedb/pipelinedb#1387]
create extension pipeline_kafka;
ERROR:  could not load library "/usr/lib/pipelinedb/lib/pipelinedb/pipeline_kafka.so": /usr/lib/pipelinedb/lib/pipelinedb/pipeline_kafka.so: undefined symbol: SSL_get_error

 Ubuntu 14.04.3 LTS

I didn't build from source, the shared object is actually there.. (but owned by root.. is this a problem?).. and I loaded libssl1.0.0  package.

Is there something that I'm doing wrong?  

thanks

**Comment by derekjn** [comment]
Hi @cmollis , can you show us the output of `SELECT pipeline_version()`?

**Comment by cmollis** [comment]
PipelineDB 0.8.6 at revision 356a33e7a5fd7b87ea6e87a81633aa4c423414f5 on x86_64-unknown-linux-gnu, compiled by gcc (Ubuntu 4.8.4-2ubuntu1~14.04) 4.8.4, 64-bit

what's weird is that I installed it exactly the same way on a Ubuntu 12 box and it worked fine.. (loading the pipeline extension)..

Do you guys link the executable with a particular version of libssl?   maybe it's looking for those .so's?

**Comment by cmollis** [comment]
sorry... the first line is the output:

pipeline=# select pipeline_version()
pipeline-# ;
                                                                        pipeline_version
----------------------------------------------------------------------------------------------------------------------------------------------------------------
 PipelineDB 0.8.6 at revision 356a33e7a5fd7b87ea6e87a81633aa4c423414f5 on x86_64-unknown-linux-gnu, compiled by gcc (Ubuntu 4.8.4-2ubuntu1~14.04) 4.8.4, 64-bit
(1 row)

**Comment by cmollis** [comment]
last comment on this.. but it looks like your library doesn't export the correct OpenSSL symbols (with versions). Not sure about this.. but every version of libssl that I have exports symbols with a version number..  maybe that's why it doesn't work.  Whatever.. I'll use the Ubuntu12 working version for testing.  

readelf -Ws pipeline_kafka.so | grep SSL
     5: 0000000000000000     0 NOTYPE  GLOBAL DEFAULT  UND SSL_get_error
    20: 0000000000000000     0 NOTYPE  GLOBAL DEFAULT  UND SSL_write
    26: 0000000000000000     0 NOTYPE  GLOBAL DEFAULT  UND SSLv23_client_method
    33: 0000000000000000     0 NOTYPE  GLOBAL DEFAULT  UND SSL_free
    37: 0000000000000000     0 NOTYPE  GLOBAL DEFAULT  UND SSL_CTX_use_certificate_chain_file
    40: 0000000000000000     0 NOTYPE  GLOBAL DEFAULT  UND SSL_set_fd
    52: 0000000000000000     0 NOTYPE  GLOBAL DEFAULT  UND SSL_CTX_set_default_passwd_cb
    55: 0000000000000000     0 NOTYPE  GLOBAL DEFAULT  UND SSL_CTX_set_default_passwd_cb_userdata
    84: 0000000000000000     0 NOTYPE  GLOBAL DEFAULT  UND SSL_library_init
    88: 0000000000000000     0 NOTYPE  GLOBAL DEFAULT  UND SSL_read
    98: 0000000000000000     0 NOTYPE  GLOBAL DEFAULT  UND SSL_CTX_ctrl
   102: 0000000000000000     0 NOTYPE  GLOBAL DEFAULT  UND SSL_new
   109: 0000000000000000     0 NOTYPE  GLOBAL DEFAULT  UND OPENSSL_add_all_algorithms_noconf
   111: 0000000000000000     0 NOTYPE  GLOBAL DEFAULT  UND SSL_shutdown
   131: 0000000000000000     0 NOTYPE  GLOBAL DEFAULT  UND SSL_CTX_new
   141: 0000000000000000     0 NOTYPE  GLOBAL DEFAULT  UND SSL_get_peer_certificate
   142: 0000000000000000     0 NOTYPE  GLOBAL DEFAULT  UND SSL_CTX_load_verify_locations
   152: 0000000000000000     0 NOTYPE  GLOBAL DEFAULT  UND SSL_CTX_use_PrivateKey_file
   154: 0000000000000000     0 NOTYPE  GLOBAL DEFAULT  UND SSL_CTX_set_cipher_list
   175: 0000000000000000     0 NOTYPE  GLOBAL DEFAULT  UND SSL_connect
   176: 0000000000000000     0 NOTYPE  GLOBAL DEFAULT  UND SSL_CTX_free
   181: 0000000000000000     0 NOTYPE  GLOBAL DEFAULT  UND SSL_load_error_strings
   209: 0000000000000000     0 NOTYPE  GLOBAL DEFAULT  UND SSL_do_handshake
   210: 0000000000000000     0 NOTYPE  GLOBAL DEFAULT  UND SSL_get_verify_result

**Comment by cmollis** [comment]
In case anyone else has this problem, here's a solution:

build librdkafka from source: https://github.com/edenhill/librdkafka, BUT when running configure:

./configure --disable-ssl
make
sudo make install.

then I build pipeline_kafka.so in /contrib and then install into pipeline_db with:
pipeline=# CREATE EXTENSION pipeline_kafka;
 
For whatever reason, the exported symbols do not get built correctly on Ubuntu14 on AWS, so this just builds without SSL.
