### ISSUE TITLE
Potential deadlock in continuous transforms when there is a single worker

### ISSUE THREAD

**Issue by usmanm** [pipelinedb/pipelinedb#1398]
This can happen if the size of the output of the transform is larger than the free space left in the dsm_cqueue of the worker.

**Comment by usmanm** [comment]
I think the only way to avoid this is to drop tuples that don't fit and print out an warning to the insert client. Thoughts @derekjn?

**Comment by derekjn** [comment]
It seems like this may be a reasonably common occurrence, so I'm not sure that dropping is the best approach. Couldn't we just keep executing non-transforms worker plans until there is a certain amount of free space left?

**Comment by usmanm** [comment]
I guess we could keep the extra tuples in process local memory and keep on retrying on every flush.

**Comment by derekjn** [comment]
I think that's a good approach.

**Comment by derekjn** [comment]
Also, we should still log warnings on the worker whenever this happens because technically we can still leak memory here.
