### ISSUE TITLE
Deadlock with COPY... FROM into a stream which is transformed

### ISSUE THREAD

**Issue by usmanm** [pipelinedb/pipelinedb#1416]
/cc @EliSnow

**Comment by EliSnow** [comment]
This could possibly be simplified down but here's one case which reproduces the problem for me:

```sql
CREATE STREAM a_stream (js jsonb);
CREATE STREAM b_stream (js jsonb);

CREATE CONTINUOUS TRANSFORM a_transform AS
  SELECT js
  FROM a_stream
  WHERE js IS NOT NULL
  THEN EXECUTE PROCEDURE pipeline_stream_insert('b_stream');
  
CREATE CONTINUOUS VIEW b_cv AS
SELECT js FROM b_stream;

COPY (SELECT '{"foo":"bar","baz":"bux"}'::jsonb FROM generate_series(1, 10000000) gs) TO '/home/pipeline/junk.csv';

COPY a_stream (js) FROM '/home/pipeline/junk.csv';
```
I believe the csv has to be a certain size before it will lock things up. This caused a deadlock for me with `continuous_query_num_workers = 4`.

**Comment by usmanm** [comment]
Awesome, thanks for repro script @EliSnow. Going to dig into this now.

**Comment by usmanm** [comment]
I have been able to repro this. Going to push out a fix soon.

**Comment by usmanm** [comment]
The fix is on `master`. Let me know if this resolves your problem.

**Comment by EliSnow** [comment]
Is this in nightly yet (and is there a way for me to tell looking at the [CI server](https://circleci.com/gh/pipelinedb/pipelinedb))?

**Comment by usmanm** [comment]
No, but I can trigger a new build. What OS?

On Thursday, March 24, 2016, EliSnow <notifications@github.com> wrote:

> Is this in nightly yet (and is there a way for me to tell looking at the CI
> server <https://circleci.com/gh/pipelinedb/pipelinedb>)?
>
> —
> You are receiving this because you modified the open/close state.
> Reply to this email directly or view it on GitHub
> <https://github.com/pipelinedb/pipelinedb/issues/1416#issuecomment-200801369>
>


-- 
Usman

**Comment by EliSnow** [comment]
Debian 8

**Comment by EliSnow** [comment]
This appears to still be broken. I am still getting deadlocked with the above test case.

**Comment by EliSnow** [comment]
This may not be limited to `COPY`. The following seems to lock up a `CONTINUOUS TRANSFORM` as well:

```sql
CREATE STREAM s1 (n bigint);
CREATE STREAM s2 (n bigint);

CREATE CONTINUOUS TRANSFORM ct AS
  SELECT n FROM s1
  THEN EXECUTE PROCEDURE pipeline_stream_insert('s2');

CREATE CONTINUOUS VIEW cv AS
  SELECT n FROM s2;
  
SELECT n INTO TEMPORARY TABLE temp
FROM generate_series(1, 10000000) gs (n);

INSERT INTO s1 (n) SELECT * FROM temp;
```

**Comment by usmanm** [comment]
Yea, it doesn't have anything to do with `COPY`. It's a deadlock between the insert process and the worker process. I'll keep on digging in.

**Comment by usmanm** [comment]
Pushed another patch to master, see if it fixed your issue.

**Comment by EliSnow** [comment]
This appears to be fixed. Once again, great work @usmanm!

**Comment by usmanm** [comment]
Awesome! The fix right now is a little ugly and it's hard to reason if it truly has fixed all issues. Let me know if you see this issue again. I'm going to close it for now.

I created #1423 which should be a permanent fix. I'll try to get that in over the next few weeks once I have some free cycles.
