### ISSUE TITLE
first_values should not return type anyarray

### ISSUE THREAD

**Issue by EliSnow** [pipelinedb/pipelinedb#1420]
`first_values` currently returns the psuedo type `anyarray` and there is no way (except for converting to text) for a user to access the elements of the array.

**Comment by usmanm** [comment]
Fix is on master and will go out in today's nightly release.

**Comment by EliSnow** [comment]
Awesome. Thanks @usmanm!

**Comment by EliSnow** [comment]
When the `ORDER BY` clause selects multiple columns, of possible different types, will `first_values` return a `row[]`?

**Comment by usmanm** [comment]
Yes, there's nothing else we can do. That's Postgres' way of dealing with anonymous complex types.

**Comment by EliSnow** [comment]
I'll have to play with it, but I believe in that case I can at least cast it to another type at `SELECT`, which was not possible with `anyarray`.

**Comment by usmanm** [comment]
You can do something like:
```
usmanm=# CREATE CONTINUOUS VIEW v AS SELECT first_values(2) WITHIN GROUP (ORDER BY x::int, y::text) FROM stream;
CREATE CONTINUOUS VIEW
usmanm=# INSERT INTO stream (x, y) VALUES (1, 'a'), (1, 'c'), (1, 'b');
INSERT 0 3
usmanm=# SELECT * FROM v;
   first_values    
-------------------
 {"(1,a)","(1,b)"}
(1 row)

usmanm=# SELECT first_values[1] FROM v;
 first_values 
--------------
 (1,a)
(1 row)

usmanm=# CREATE TYPE xy AS (x int, y text);
CREATE TYPE
usmanm=# SELECT (first_values[1]::text::xy).x, (first_values[1]::text::xy).y FROM v;
 x | y 
---+---
 1 | a
(1 row)
```
