### ISSUE TITLE
OSX pkg doesn't seem to have PostGIS

### ISSUE THREAD

**Issue by jsrolon** [pipelinedb/pipelinedb#1427]
I downloaded the 0.9.0 .pkg for OSX yesterday, and just now I'm trying to create a stream with the following query:

`CREATE STREAM test (geom geometry)`

To which I get that `type "geometry" does not exist`. I then try with:

`CREATE EXTENSION postgis`

And I get:
`ERROR:  could not open extension control file "/usr/local/lib/pipelinedb/share/pipelinedb/extension/postgis.control": No such file or directory`

It seems like the .pkg does not include the PostGIS extension. Should I build from source then?

**Comment by usmanm** [comment]
We removed PostgGIS from being automatically built and installed with PipelineDB. And `pipeline_kafka` will also be removed with the next release. It was just complicating our build process and most packaging problems were coming from PostGIS.

You can get PostGIS which is compatible with PipelineDB here: https://github.com/pipelinedb/postgis
