### ISSUE TITLE
Inferred streams sometimes don't get cleaned up

### ISSUE THREAD

**Issue by usmanm** [pipelinedb/pipelinedb#1448]
Probably some weird dependency thing. We should just move to declare all streams always

Repro: run the `cont_view_namespace` test and then inspect the `pipeline_streams` catalog, there's a left over relation for `stream`

**Comment by EliSnow** [comment]
I'd love to see no more inferred streams.

**Comment by usmanm** [comment]
I think the direction we're gonna take is to always have users create streams explicitly but still allow their schema to be inferred. A stream created with no columns will have its schema inferred.

```
CREATE STREAM inferred_stream ();
CREATE STREAM static_stream (x::int);
```

Do you think this approach is better?

**Comment by EliSnow** [comment]
I do think its better, though I prefer everything being explicit. At least this solution will help me catch my typos quicker since I use explicitly defined streams.

**Comment by usmanm** [comment]
Clean them up when calling `pipeline_streams()`
