### ISSUE TITLE
Potential leak in ipc broker when caching messages locally

### ISSUE THREAD

**Issue by usmanm** [pipelinedb/pipelinedb#1471]

**Comment by jarwin123** [comment]
can you tell me how to check memory leak in pipelindb? i used valgrind test pipelinedb,but i haven't success, can you tell me how to use valgrind debug pipelinedb backgroup process worker ? 
my command:
      valgrind  --leak-check=yes --gen-suppressions=all \
    --suppressions=./valgrind.supp --time-stamp=yes \
    --log-file=$HOME/%p.log --trace-children=yes \
    /usr/local/pipelinedb/bin/pipeline-ctl -D db183/ -l logfile restart   -m fast
