### ISSUE TITLE
Fix deadlock between ExecCreateContViewStmt and Drop Continuous view

### ISSUE THREAD

**Issue by loadzero** [pipelinedb/pipelinedb#1473]
This deadlock occurs when a ```DROP CASCADE``` from ```./src/test/regress/sql/analyze_cont_view.sql``` conflicts with a ```CREATE CONTINUOUS VIEW``` from one of the other regressions tests occurring in parallel

```
DETAIL:  Process 1110 waits for ExclusiveLock on relation 4242 of database 16384; blocked by process 1113.
    Process 1113 waits for AccessShareLock on relation 16755 of database 16384; blocked by process 1110.
    Process 1110: DROP TABLE tnotice CASCADE;
    Process 1113: CREATE CONTINUOUS VIEW cv_agg_expr AS SELECT k::text, COUNT(*) + SUM(v::int) FROM sanity_stream GROUP BY k;
```

```ExecCreateContViewStmt``` takes a lock on the ```PipelineQueryTable``` and then calls ```streams_to_meta```, which acquires locks on all view matrels (via get_query_def).

This is in reverse order to the ```DROP TABLE CASCADE```, which takes a lock on a matrel, and then the ```PipelineQuery``` table.

The relevant backtrace for ```ExecCreateContViewStmt``` is here:

```
src/backend/nodes/print.c:78
LockRelationOid
src/backend/storage/lmgr/lmgr.c:117
relation_open
src/backend/access/heap/heapam.c:1064
heap_open
src/backend/access/heap/heapam.c:1239
AcquireRewriteLocks
src/backend/rewrite/rewriteHandler.c:178
get_query_def
src/backend/utils/adt/ruleutils.c:4380
deparse_query_def
src/backend/utils/adt/ruleutils.c:461
streams_to_meta
src/backend/catalog/pipeline_stream.c:178
UpdatePipelineStreamCatalog
src/backend/catalog/pipeline_stream.c:491
DefineContinuousView
src/backend/catalog/pipeline_query.c:275 (discriminator 4)
ExecCreateContViewStmt
```

**Comment by loadzero** [comment]
These buildbot failures are examples of this bug:

https://circleci.com/gh/pipelinedb/pipelinedb/4907 
https://circleci.com/gh/pipelinedb/pipelinedb/4906

**Comment by usmanm** [comment]
`get_query_def` is getting a lock on the table being dropped because some query probably joins a stream with it. I think one way to reduce the surface area for this bug is to only update the stream meta which the continuous query being created reads from.

**Comment by loadzero** [comment]
Putting on the backburner in the meantime - see 6a1cb3e

**Comment by derekjn** [comment]
So this is actually pretty simple to fix, we don't even need to use `deparse_query_def` because we already have the `Query`. The only reason we're using `deparse_query_def` is because it makes inference more convenient. Once inferred streams are gone, this issue will essentially go away,.

**Comment by usmanm** [comment]
This seems like the last thing that causes sporadic test failures.

**Comment by derekjn** [comment]
Yea the fix for this is pretty straightforward I believe. We just don't need to use `deparse_query_def` in `streams_to_meta`. We were using it before because we needed to collect `TypeCast` nodes for inference, which are parse nodes. Now it should be easy to just use the `Query` object we already have there though.
