### ISSUE TITLE
Build packages with SSL support

### ISSUE THREAD

**Issue by derekjn** [pipelinedb/pipelinedb#1498]
And add tests with `sslmode=require`.

**Comment by usmanm** [comment]
I don't think it should be enabled by default. Security is mostly moving towards being on the infrastructure layer with things like Security Groups etc. We can probably build the packages with SSL support though.

**Comment by derekjn** [comment]
Oops, I meant enable it with `configure` by default. SSL support has to be enabled at compile-time so the default build currently can't even support SSL.

**Comment by usmanm** [comment]
Gotcha. +1

**Comment by derekjn** [comment]
Verify that clients and servers compiled with SSL support can still run with SSL disabled on systems that don't have openssl.

**Comment by julianvmodesto** [comment]
@derekjn hm, I've tried 0.9.5 from the PipelineDB download page, and seems that the packages aren't build with SSL support.

Are packages configured with SSL already, or do I need to build from source with the right flags?

**Comment by derekjn** [comment]
Hi @julianvmodesto, the official PipelineDB packages are not built with SSL support. It must be enabled at build time by specifying the `--with-openssl` flag to `./configure`. e.g.,

    ./configure --with-openssl <other flags>
    make
    make install

**Comment by julianvmodesto** [comment]
Ah got it, thanks @derekjn!

Could I open an issue to build packages with SSL support? Just at the build, without enabling `ssl = on` in conf.

**Comment by derekjn** [comment]
@julianvmodesto there hasn't been much demand for packages pre-built with SSL support, so realistically speaking I don't see us adding them to our release publishing pipeline. That said, if you have `docker` you can use the same exact build command that our automated build pipeline uses:

(from the `pipelinedb` root)

    docker run -v $PWD:/pipelinedb -v $PWD:/output -e RELEASE=1 -e PIPELINE_WITH_OPTIONS="--with-openssl" pipelinedb/buildslave:ubuntu14 rpm pipelinedb output

Does that help

**Comment by julianvmodesto** [comment]
Yes, very helpful, thanks! Was worried about building from source, so this simplifies that greatly -- I'll be able to work with this.

Count me as a +1 for requesting packaging with SSL support though :)
