### ISSUE TITLE
cq_stat_get error with stale stats

### ISSUE THREAD

**Issue by derekjn** [pipelinedb/pipelinedb#1526]
If a stale ID gets passed in [here](https://github.com/pipelinedb/pipelinedb/blob/master/src/backend/utils/adt/pipelinefuncs.c#L234) an error will be thrown by `GetContQueryForViewId`.

**Comment by usmanm** [comment]
Are you on master? `GetContQueryForId` is called, not `GetContQueryForViewId` and that returns `NULL` instead of throwing an error for a stale id.
