### ISSUE TITLE
cont_subselect failure

### ISSUE THREAD

**Issue by usmanm** [pipelinedb/pipelinedb#1560]
```
*** 131,137 ****
  SELECT * FROM test_cont_sub_v6;
   count 
  -------
!      6
  (1 row)
  
  DROP CONTINUOUS VIEW test_cont_sub_v6;
--- 131,137 ----
  SELECT * FROM test_cont_sub_v6;
   count 
  -------
!      5
  (1 row)
  
  DROP CONTINUOUS VIEW test_cont_sub_v6;
```
Happens when running `regression` tests. I changed the tests to not drop this view and inspected it after the tests were over. The value was correctly 6. So basically something with `synchronous_stream_insert` is messed up. Not high priority.

**Comment by derekjn** [comment]
#1575
