### ISSUE TITLE
Dropping Continuous Transforms

### ISSUE THREAD

**Issue by brettlaforge** [pipelinedb/pipelinedb#1564]
I'm having issues dropping Continuous Transforms unless I use the superuser account.

I keep getting: 

```
DROP CONTINUOUS TRANSFORM IF EXISTS flow_transform;
- unexpected object type (45)]
  name: 'error',
  length: 90,
  severity: 'ERROR',
  code: 'XX000',
  detail: undefined,
  hint: undefined,
  position: undefined,
  internalPosition: undefined,
  internalQuery: undefined,
  where: undefined,
  schema: undefined,
  table: undefined,
  column: undefined,
  dataType: undefined,
  constraint: undefined,
  file: 'dropcmds.c',
  line: '441',
  routine: 'does_not_exist_skipping' }
```

I was wondering if this issue is due to CT's not being listing in the ExecDropStmt() in the "src/backend/tcop/utility.c" file?

**Comment by usmanm** [comment]
Oops, yea I think I forgot to put it inside a switch. If you remove the `IF EXISTS` part, it should work. I'll push a fix soon.
