### ISSUE TITLE
Make catalog-changing version upgrades lighter

### ISSUE THREAD

**Issue by derekjn** [pipelinedb/pipelinedb#1565]
Currently when there are catalog changes across version users need to dump and restore the old database into the new one. This should just work similarly to how `pg_upgrade` works, which essentially creates new catalogs and copies the existing user-defined relations into the new data directory.

**Comment by derekjn** [comment]
This is actually turning out to be somewhat complicated because of how we create many interdependent objects that comprise a CV/CT. `pg_upgrade`essentially sets the OIDs of each object that is restored with something like:

    SELECT pg_catalog.binary_upgrade_set_next_pg_type_oid('16396'::pg_catalog.oid);

Which sets a global variable that is used to assign the next created relation's OID. This gets complicated when creating several relations under a single command (`CREATE CONTINUOUS VIEW`). I expect this to get even more complicated when inferred streams come into play.

It might be cleaner to wrap `pg_upgrade` in another script that migrates PipelineDB objects separately because semantically this is still pretty simple.

**Comment by usmanm** [comment]
Yea, that makes sense. Probably the easiest do do it that way. I'm gonna rip out inferred streams after this ZMQ stuff. That's like the last bit of major jankiness left in the code base.
