### ISSUE TITLE
I can not create postgis extension for pipelineDB 0.9.3-1

### ISSUE THREAD

**Issue by flybird2012** [pipelinedb/pipelinedb#1566]
I install pipelinedb-0.9.3-1 on centos 6 by pipelinedb-0.9.3-1.x86_64 RPM package, and then I download the postgis (2.3.0) source code by command "git clone -b 0.9.0 https://github.com/pipelinedb/postgis.git".

In order to compile the postgis I also compile the following software:
geos-3.5.0 
 proj-4.8.0
 gdal-2.0.1
libxml2-devel-2.7.6-21.el6.x86_64  

Postgis compile and install successfully, but I can't create postgis extension in pipelineDB. 

./psql -p 1932 -d pipeline
psql (9.5.3)
Type "help" for help.
＃create extension postgis;
ERROR: could not load library "/usr/lib/pipelinedb/lib/pipelinedb/postgis-2.3.so": /usr/lib/pipelinedb/lib/pipelinedb/postgis-2.3.so: undefined symbol: GEOSClipByRect 

Where is wrong?

**Comment by derekjn** [comment]
It looks like the `libgeos` library isn't being found at load time. Can you try adding its path to the `LD_LIBRARY_PATH` environment variable and trying again?

**Comment by flybird2012** [comment]
I fix this problem by following commands:
#echo /usr/local/lib >> /etc/ld.so.conf
#ldconfig (executing command in directory of postgis source code)
 after executing "make install".  But I don't know the reason.

**Comment by kayvank** [comment]
this is a problem for me as well forpipelinedb-0.9.6-osx-x86_64.pkg
the error message is 
`os=> CREATE EXTENSION postgis;
ERROR:  could not open extension control file "/usr/lib/pipelinedb/share/pipelinedb/extension/postgis.control": No such file or directory`

**Comment by IanVaughan** [comment]
I have this issue as well, my setup is using the Docker image
```
docker run -v /dev/shm:/dev/shm --name pipeline --rm -p 5432:5432 pipelinedb/pipelinedb
```
Then in a new shell
```
> docker exec -it pipeline /bin/bash

root@80a427d1b08f:/# apt-get update
root@80a427d1b08f:/# apt-get install -y postgresql-server-dev-9.4 libxml2-dev libgeos-dev libproj-dev libgdal-dev xsltproc autoconf libtool libcunit1-dev

root@80a427d1b08f:/# PATH=$PATH:/usr/lib/pipelinedb/bin/

root@80a427d1b08f:/# git clone https://github.com/pipelinedb/postgis.git
root@80a427d1b08f:/# cd postgis

root@80a427d1b08f:/postgis# ./autogen.sh
root@80a427d1b08f:/postgis# ./configure
root@80a427d1b08f:/postgis# make
root@80a427d1b08f:/postgis# make install
```

Then attempt to install postgis.
```
> psql -h 192.168.99.100 -U pipeline quiqup_development

pipeline=# CREATE EXTENSION postgis;
ERROR:  could not open extension control file "/usr/lib/pipelinedb/share/pipelinedb/extension/postgis.control": No such file or directory
```
