### ISSUE TITLE
why catalog pg_stat_user_functions is can't statistics function in CV query?

### ISSUE THREAD

**Issue by sangli00** [pipelinedb/pipelinedb#1572]
I modify  `track_functions = all`

create stream stream_test(x bigint);
create continuous view cv_test as select my_udf(x) from stream_test;
insert into stream_test(x) values(111);

why  `pg_stat_user_functions` is can't statistics my_udf?
but,if i execute command `select my_udf(1)` ,`pg_stat_user_functions` is OK.

**Comment by derekjn** [comment]
Hi @sangli00, so what was happening was that these statistics weren't being flushed for continuous views until the system was shut down. 5b645d499c54444354987826a46d2a14eedaf506 fixes this, so you should see statistics for UDFs in continuous views now. Thanks for reporting!
