### ISSUE TITLE
Dockerfile should set listen_addresses to '*' in pipelinedb.conf

### ISSUE THREAD

**Issue by avinson** [pipelinedb/pipelinedb#1578]
Initializing the docker image from scratch results in a pipelinedb instance that only listens on localhost and the pipelinedb.conf must be manually edited to fix this. I suggest adding a parameter to the docker init scripts to allow changing this or else listen on '*' by default when running using docker.

**Comment by derekjn** [comment]
Hi @avinson, thanks for the thoughtful suggestion! Just so I can understand this before determining what the best thing to do is, can you clarify what you mean by initializing the Docker image from scratch?

I'm assuming you mean starting the PipelineDB container and manually running `pipeline-init`, is that accurate?

**Comment by avinson** [comment]
I'll try to clarify a bit.. typically when you are running a service in docker, you don't want to only listen on localhost since you can manage network settings with runtime configuration settings to the docker daemon. I would recommend a couple things:

- move package installations to the Dockerfile itself
- combine your three docker scripts into a single docker-entrypoint.sh script
- use the docker-entrypoint.sh from the official postgresql docker image as inspiration: https://github.com/docker-library/postgres/blob/master/docker-entrypoint.sh

This may have more complexity than you guys need but there's some useful concepts in there. Notice how they modify pg_hba.conf to trust 0.0.0.0/0 by default. The way the pipelinedb docker image currently works, it's unusable by default -- you must first start the container, then manually edit pg_hba.conf and pipelinedb.conf and then restart it before you can connect.

I'd be happy to take a stab at a PR for this stuff above if you think it would be useful to the project.

**Comment by derekjn** [comment]
@avinson it would definitely be useful for the project and we'd welcome a PR if you're up for it!

**Comment by ankoh** [comment]
Hi @avinson @derekjn,
IMHO the PipelineDB docker image should behave similar to the Postgres one.
I thought of something like this:
https://gist.github.com/ankoh/3e31de2cf38140bddc82cb02512348be

That way, you can easily replace any existing Postgres container with a PipelineDB.

**Comment by derekjn** [comment]
@ankoh thanks for sharing! We would still welcome a PR here if you'd like to put something together.

**Comment by ankoh** [comment]
@derekjn Sure, I'll push a PR tomorrow. I've first tried to build an alpine based image this morning (which would definitely be more favourable), but you get a tiny problem in [1].

Alpine Linux ships with musl libc instead of glibc which leads to unresolved symbols of execinfo.h (backtrace and backtrace_symbols [2]). I think that could be patched quite easily.

[1]: https://github.com/pipelinedb/pipelinedb/blob/7a8cc52481a7b9abcbd5dc2c37d6c8a6d70ef85d/src/backend/nodes/print.c
[2]: https://www.gnu.org/software/libc/manual/html_node/Backtraces.html
