### ISSUE TITLE
Add output_of range function for reading output streams

### ISSUE THREAD

**Issue by derekjn** [pipelinedb/pipelinedb#1580]
e.g. `... FROM output_of('v')`. This parses as a `RangeFunction`, which unfortunately is smaller than a `RangeVar` so we can't simply clobber the node into a `RangeVar` referring to `v_osrel`.

It's probably time to write a walker that can replace arbitrary parse nodes similarly to how `expression_tree_mutator` can replace expressions.

**Comment by usmanm** [comment]
How is it represented in the `Query` object?

**Comment by derekjn** [comment]
`RangeTblFunction`, but it breaks various checks in our analyzer so it won't currently make it that far without a few changes.

**Comment by derekjn** [comment]
#1563
