### ISSUE TITLE
Back adhoc queries with unlogged CVs

### ISSUE THREAD

**Issue by derekjn** [pipelinedb/pipelinedb#1583]
Instead of executing adhoc queries on streams in memory, just use an actual CV but make its matrel unlogged. Then the adhoc client just reads from this CV's output stream. This should allow us to remove all backend special casing for adhoc queries.

**Comment by derekjn** [comment]
After #1582, both the alert client and server go away and just become:

    COPY (SELECT ... FROM output_of('some_transform')) TO PROGRAM 'do_something'

Which is super clean.

**Comment by usmanm** [comment]
We should also suggest putting them on RAM disk backed table spaces for better performance.

**Comment by derekjn** [comment]
Now that the old stuff is ripped out the vast majority of this work is in #1582, after which the adhoc client can just run `COPY (<adhoc select>) ...`.

**Comment by usmanm** [comment]
The only difference is that adhoc queries can have aggregates so we'll have to create temporary views under the hood. These temp views should be backed by `UNLOGGED` tables and cleaned up at the end of the adhoc query. I agree that there should be no difference from the standpoint of the user. Stream selects should allow aggregates as well.

**Comment by usmanm** [comment]
Closing this since it's covered by #1582
