### ISSUE TITLE
Using array_agg/set_agg causes segfault

### ISSUE THREAD

**Issue by sutram** [pipelinedb/pipelinedb#1594]
This is with PipelineDB 0.9.3 and latest pipeline_kafka from master

I tried using array_agg/set_agg within a continuous view for the first time and it caused a segfault immediately. Once this segfault happens, PipelineDB is unable to recover from this and the only way to get it going again is to restart it.

**Segmentation fault (PID 9920)
version: PipelineDB 0.9.3 at revision 4c750ee118c1d4c91f784dda6b79d1f000561e6e on x86_64-pc-linux-gnu, compiled by gcc (Ubuntu 4.8.4-2ubuntu1~14.04) 4.8.4, 64-bit
backtrace:
pipelinedb: bgworker: combiner6 [pipeline]   (debug_segfault+0x15)[0x60e975]
/lib/x86_64-linux-gnu/libc.so.6(+0x36cb0)[0x7f9e5eff3cb0]
pipelinedb: bgworker: combiner6 [pipeline]   (arrayaggstatesend+0x1a)[0x6ea71a]
pipelinedb: bgworker: combiner6 [pipeline]   [0x5ba0f2]
pipelinedb: bgworker: combiner6 [pipeline]   (ExecProject+0x15d)[0x5bf80d]
pipelinedb: bgworker: combiner6 [pipeline]   [0x5c4c56]
pipelinedb: bgworker: combiner6 [pipeline]   (ExecAgg+0xb8)[0x5c4da8]
pipelinedb: bgworker: combiner6 [pipeline]   (ExecProcNode+0x96)[0x5b8bc6]
pipelinedb: bgworker: combiner6 [pipeline]   (ExecutePlan+0x54)[0x5b7074]
pipelinedb: bgworker: combiner6 [pipeline]   (standard_ExecutorRun+0xea)[0x5b71ba]
pipelinedb: bgworker: combiner6 [pipeline]   [0x6ce098]
pipelinedb: bgworker: combiner6 [pipeline]   (PortalRun+0x24f)[0x6cf42f]
pipelinedb: bgworker: combiner6 [pipeline]   [0x6600db]
pipelinedb: bgworker: combiner6 [pipeline]   (ContinuousQueryCombinerMain+0x328)[0x6604c8]
pipelinedb: bgworker: combiner6 [pipeline]   [0x65d1a8]
pipelinedb: bgworker: combiner6 [pipeline]   (StartBackgroundWorker+0x19b)[0x66a87b]
pipelinedb: bgworker: combiner6 [pipeline]   [0x676ae5]
pipelinedb: bgworker: combiner6 [pipeline]   [0x470d37]
pipelinedb: bgworker: combiner6 [pipeline]   (PostmasterMain+0xea4)[0x6787b4]
pipelinedb: bgworker: combiner6 [pipeline]   (main+0x3ee)[0x47158e]
/lib/x86_64-linux-gnu/libc.so.6(__libc_start_main+0xf5)[0x7f9e5efdef45]
pipelinedb: bgworker: combiner6 [pipeline]   [0x4715f5]
2016-08-02 11:20:12 EDTLOG:  worker process: combiner6 [pipeline] (PID 9920) exited with exit code 1**

Here is the continuous view

**create continuous view conops_ats with (max_age = '2 hours') as select
       payload->>'distribution_timeshiftformat' as dtf,
       array_agg((payload->>'datatransfer_requestdurationMsecs')::integer) as
       xd, sum((payload->>'datatransfer_requestdurationMsecs')::integer) as
       sum_xd, count(*) filter (where
       ((payload->>'datatransfer_requestdurationMsecs')::integer) > 0) as
       xd_cnt, date_trunc('minute',
       to_timestamp((payload->>'timestamp_received')::bigint/1000)) as ts,
       payload->>'datatransfer_server_name' as sname,
       payload->>'datatransfer_server_ip' as sip,
       payload->>'datatransfer_server_cdn' as cdn,
       payload->>'platform_devicetype' as pdt, payload->>'stream_format' as sf,
       ((payload->>'playback_quality_bitrate')::numeric) as bitrate from
       cdn_stream group by ts, dtf, cdn, sname, sip, sf, pdt, bitrate;**

**Comment by derekjn** [comment]
Hi @sutram! This was fixed by https://github.com/pipelinedb/pipelinedb/commit/c2b6bf4fff45da1970d71ac4e10fd8f3f63e4626

I'm still going to run your CV just to confirm that this is the same issue and will report back shortly.

**Comment by derekjn** [comment]
Confirmed, fixed for the next release.
