### ISSUE TITLE
Factor out into a standard PostgreSQL extension

### ISSUE THREAD

**Issue by derekjn** [pipelinedb/pipelinedb#1596]
Our interfaces and core functionality are stable and well-defined enough at this point that we can cleanly formulate our API in terms of the extension API. The main areas of work here are:

**Syntax** - Grammar is not extensible so we lose `CREATE CONTINUOUS VIEW` et all. They become `SELECT pipelinedb.create_cv('...')` etc.

**Syscache lookups** - We'll need to write fast lookup support around our catalog tables since they won't be native catalogs anymore.

**Planner/executor** - CQ node types will need to be handled via hooks instead of natively.

**Dump/restore** - We'll need to make dump/restore work with vanilla `pg_dump`/`pg_restore`

This refactor should probably happen in a few phases:
- Phase 0: get the diff against upstream Postgres down to an absolute minimum
- Phase 1: factor PipelineDB out as an extension of itself
- Phase 2: stabilize the extension against upstream Postgres, possibly landing some changes upstream where necessary

**Comment by EliSnow** [comment]
Woah!

**Comment by derekjn** [comment]
We should start breaking this into incremental additions, and aim to time the final step with PG 9.7, which will probably be out in Q12017. Ideally we can incrementally release this rework in our own releases before then.

**Comment by samgaw** [comment]
According the [Postgres roadmap](https://www.postgresql.org/developer/roadmap/), 10/9.7 is scheduled for a Q3 release next year. Is the Q1 2017 timeline above a typo?

**Comment by samgaw** [comment]
@derekjn Is this likely to land Q1 this year or is it realistically going to be further out towards the second half of the year? I'm just to get a sense of things for our deployment plans.

Cheers.

**Comment by derekjn** [comment]
Hey @samgaw! Second half of the year would be more realistic for planning purposes. Are you currently using PipelineDB or are you waiting for the extension refactor?

**Comment by samgaw** [comment]
@derekjn We've been running it in the lab for a few months. The hold off on deployment has been waiting for either the refactor or the 9.6 merge; but if the merge comes first the end result is the same for us so I've really no preference either way.

**Comment by mbulgakov17** [comment]
@derekjn Would this allow for combining CitusDB and PipelineDB functionality in a single PG deployment?

**Comment by derekjn** [comment]
> @derekjn Would this allow for combining CitusDB and PipelineDB functionality in a single PG deployment?

@mbulgakov17 probably not in any useful way. The PipelineDB core runs on a single server, so if you were running a CitusDB across multiple nodes and wanted to run PipelineDB on them as well, you'd probably end up with some kind of operational mess.

**Comment by agentgt** [comment]
@mbulgakov17 If it helps we have them separate and syndicate to both CitusDB and PipelineDB through a queue (kafka and rabbitmq).

In theory logical decoding (e.g. bottle) from pipelinedb -> citus would be the ideal choice but I'm not sure how well that would work and what the decoding looks like for streams/views. Luckily accurate consistency with stats is not a major requirement for us.

**Comment by mbulgakov17** [comment]
Thank you for sharing, @agentgt

**Comment by aerostitch** [comment]
Wondering if having pipelinedb act as a proxy in front of postgresql wouldn't be an easier path and more flexible on the pipelinedb end (you could keep the same code syntax for the end users).
Doing so would allow you to decorellate the DB backend from the code logic and probably have an easier code to manage. On the end user side, we could have the storage done in, let's say and RDS Postgres instance and the pipelinedb proxy run on a docker image for example.
Thoughts?

**Comment by derekjn** [comment]
@aerostitch it's definitely a cool idea in theory, but wouldn't really be feasible in practice. You could make something work this way and get correct results, but the performance wouldn't even be remotely comparable to what PipelineDB currently provides, to the point where it would likely be pointless to use. It would be so expensive that you'd most likely be better off just storing all of your granular data in a warehouse and running on-demand queries on it.

I see two approaches you could take for this:

1) Cache all aggregate data at the PipelineDB layer and just write out updates to the storage layer to avoid read-writes for incremental updates. But this is basically equivalent to how PipelineDB already works. You can actually do this already with PipelineDB if you want, by just tailing output streams and writing output rows to some external datastore.

2) Don't cache aggregate data and incur the cost of a read-write for each incremental update. Not only would this involve a lot of round trips between PipelineDB and the storage layer, but you'd be incurring all of the overhead of generating raw SQL queries and planning them before execution on the storage end. Currently PipelineDB bypasses all of that by co-locating compute and storage, and running incremental updates without any planner overhead.

I definitely like what you've outlined though, it's very elegant but unfortunately would be impossible to make such a setup perform at the level that users have come to expect of PipelineDB.

**Comment by aerostitch** [comment]
Thanks for the answer @derekjn .
Yeah solution 1 was more what I was thinking and would basically be a big cache with a query language on top of it :)
The use case would have been to be able to have an equivalent of a distributed cache that we could spread on different nodes of a kubernetes cluster for example and having the storage safe in a non-ephemeral environment (we keep only 60mins of datapoints).
But I do understand your concern about performance on large scale data.

**Comment by usmanm** [comment]
Wondering if you aim to refactor this in the same three phases as noted above? The PostgreSQL 10 beta is out and there's enough changes that I think an easier refactor strategy would be to start with a new blank extension and slowly port over code from PipelineDB into that?

I think the first step can be to get a few simple aggregates to work end-to-end, including support for output streams etc. Once that is stable, porting other aggregates should be fairly straight-forward?

**Comment by derekjn** [comment]
@usmanm I think that approach is worth experimenting with now that PG 10beta is out, because it if is going to be faster, it's going to be *much* faster. We'll evaluate this approach and report back here over the next week or so.

**Comment by derekjn** [comment]
@usmanm I did some prototyping with the direct-to-extension approach, and I think it's going to work pretty well. The biggest complication is that it's non-trivial to port modules that use PipelineDB-specific things that aren't available in PG core. Examples of such things are `DestTupleTable`, `DestCombiner`, custom syscache entries, etc.

It is necessary to replace these components with standard primitives no matter how we do this, so I think the best way to go about finishing the refactor will be a two step process:

1. Standardize everything in the PipelineDB tree.
2. Port the standardized tree directly to an extension.

The main advantage of this approach is that I don't believe that any upstream merging is necessary. As you suggested, once everything is standardized it's actually fairly smooth to port all modules directly as an extension. But as I mentioned the standardization has to happen at some point anyways, so it seems more practical to do it in its own stage rather than simultaneously while porting.

**Comment by derekjn** [comment]
Resolved in extension repo.
