### ISSUE TITLE
Investigate nanomsg vs ZeroMQ 

### ISSUE THREAD

**Issue by usmanm** [pipelinedb/pipelinedb#1605]

**Comment by anthony-hz** [comment]
As far as I know, Zeromq is far from  being stable to meet requirement of mission critical application as pipelineDB, Please think twice before adoption.

**Comment by usmanm** [comment]
ZeroMQ or nanomsg?

**Comment by anthony-hz** [comment]
None of both. ZeroMQ is bloating overhead, code is wired and too complicated than raw implementation IPC solution with (UNIX/TCP) sockets or pipes.   Nanomsg is too young and not proved in real case.  Raw implementation will be  light and under control.

**Comment by anthony-hz** [comment]
I have one engineer who has experience on adoption and debugging Zeromq.  The conclusion is DO NOT USE IT in serious environment.  I have adopted PipelineDB in production from 0.8. When I was watching 0.95, it's very  surprised that ZeroMQ  is required. I spend several hours to find this place drop the comments. Many thanks for thinking twice. Cause I think PipelineDD's approach is on the right way and will be promising product for BIG DATA.

**Comment by anthony-hz** [comment]
IF have to choose between Zeromq and nanomsg,  nanomsg will be less overhead, with more control.
nanomsg should be better.
Lib written with C++ is out of control considering the quality as mention above.
Less is more..

**Comment by anthony-hz** [comment]
If socket is what IPC needs, why not choose simple lib as http://libevent.org/
It's proven to be very robust.

Or http://software.schmorp.de/pkg/libev.html

**Comment by sangli00** [comment]
amazed, is good investigate.

**Comment by derekjn** [comment]
Closing this for now, as ZMQ has been working very well for quite a while now.

**Comment by anthony-hz** [comment]
Good news!
