### ISSUE TITLE
Perf analysis

### ISSUE THREAD

**Issue by derekjn** [pipelinedb/pipelinedb#1617]
I just finished running some perf tests with the following configuration:

* 32 cores, 16/16 combiners/workers
* Everything else default
* 8 Insert threads for each workload

Overall I didn't see any crashes or errors on `master`, although there are some behavioral issues that are suspect. Here are some raw numbers:

**0.9.3**

* **`stress-0`** 852000000 events emitted in 605.835 s (1406322.87 eps)
* **`stream-table-join`** 636000000 events emitted in 607.636 s (1046678.73 eps)
* **`100k-groups-by-minute`** 645000000 events emitted in 604.576 s (1066862.74 eps)
* **`10m-8-column-groups`** 165000000 events emitted in 625.326 s (263862.37 eps)

These workloads were run in the above sequence, here are CPU and memory graphs (ignore the first CPU spike):

![0 9 3-cpu](https://cloud.githubusercontent.com/assets/384666/17544725/e5d02514-5e8d-11e6-8e75-39e4ec491f2c.png)
![0 9 3-mem](https://cloud.githubusercontent.com/assets/384666/17544728/e8de5c80-5e8d-11e6-8cef-28a4455a9354.png)

**master**
* **`stress-0`** 650000000 events emitted in 606.619 s (1071512.22 eps)
* **`stream-table-join`** 1009000000 events emitted in 604.242 s (1669860.47 eps)
* **`100k-groups-by-minute`** 554000000 events emitted in 601.223 s (921455.68 eps)
* **`10m-8-column-groups`** Seemed to slow down significantly and didn't end after scheduled 10 minutes so I killed it. There wasn't a stall or deadlock, it just slowed down (see CPU chart below).

These workloads were run in the above sequence, here are CPU and memory graphs:

![master-cpu](https://cloud.githubusercontent.com/assets/384666/17544751/02cb7d6c-5e8e-11e6-8ab5-3508db4f767a.png)
![master-mem](https://cloud.githubusercontent.com/assets/384666/17544748/00489610-5e8e-11e6-8caa-78e0f9b2964c.png)

The first memory spike coincides with `100k-groups-by-minute`, and the second one with `10m-8-column-groups`. Note the significant drop in CPU during the last workload.

I'm guessing there is some memory leakage causing those spikes, even though they do appear to level out eventually. The abrupt drop in CPU also appears suspect.

**Comment by derekjn** [comment]
Since the two workloads that are problematic involve fairly high cardinality CVs with lower throughput, it seems as if the problem is due to the system becoming saturated. The drops in CPU coincide with the memory spikes leveling out.

**Comment by derekjn** [comment]
Update numbers after perf improvements:

* **`stress-0`** 655000000 events emitted in 606.104 s (1080672.49 eps)
* **`stream-table-join`** 1004000000 events emitted in 604.146 s (1661850.20 eps)
* **`100k-groups-by-minute`** 1042000000 events emitted in 603.083 s (1727788.59 eps)
* **`10m-8-column-groups`** 113000000 events emitted in 619.306 s (182462.21 eps)

![master-cpu](https://cloud.githubusercontent.com/assets/384666/17578691/08041eac-5f41-11e6-875b-7d2a76d098ab.png)
![master-mem](https://cloud.githubusercontent.com/assets/384666/17578692/09afc288-5f41-11e6-93cf-d5848198dd43.png)

**Comment by usmanm** [comment]
Hm, `10m-8-column-groups` seems to have taken a perf hit. Can you try running some numbers with large rows. Something like `many-count-distinct`?

**Comment by derekjn** [comment]
I shut the instance down but I'll spin up another one and do some large-row workloads and post my findings here.

`10m-8-column-groups` probably has a lot of variance because disk is by far the bottleneck and the index doesn't fit in `shared_buffers`. There were a bunch of warnings in the logs about checkpoints occurring too frequently (happens on `master` too), so with so much disk activity I wouldn't expect a very consistent  eps between runs.

**Comment by derekjn** [comment]
* `master`
* `memory-0`
* c3.8xlarge
* 16/16 workers combiners

![master-cpu](https://cloud.githubusercontent.com/assets/384666/17582477/c03594b4-5f60-11e6-957b-7c9a9ad385c1.png)
![master-mem](https://cloud.githubusercontent.com/assets/384666/17582484/c1654c76-5f60-11e6-8acc-69ee09131606.png)

It seems like there's an obvious leak here, looking into it with `massif` now.

**Comment by usmanm** [comment]
Oh damn, yea that's a pretty massive leak.

**Comment by derekjn** [comment]
![massif](https://cloud.githubusercontent.com/assets/384666/17582811/6619608a-5f62-11e6-912f-3047268a9cfa.png)

It's happening in `project_sw_overlay_into_ostream`. Technically we shouldn't even call this function when there are no output stream readers, but it is still a legitimate leak. The tuples being accumulated in the step hashtable are never freed because no GC is done unless there are readers.

**Comment by usmanm** [comment]
That makes sense. We shouldn't keep track of matrels if there are no readers for the OS stream. That's just unnecessary overhead. That'll fix the leak as well since whenever we're accumulating tuples, we're bound to have some readers, which means we'll GC the hash table.

**Comment by derekjn** [comment]
Yea exactly, I'm not even sure why it's doing anything with OS tuples without any readers. It seems like a pretty obvious optimization but I must have just overlooked something. I'll have a fix in the morning.
