### ISSUE TITLE
Docker image missing version tag in docker hub

### ISSUE THREAD

**Issue by focusaurus** [pipelinedb/pipelinedb#1625]
Looking at the [tags](https://hub.docker.com/r/pipelinedb/pipelinedb/tags/) for the pipelinedb/pipelinedb docker image, the current latest image is not also tagged with it's version (which I believe is 0.9.3). If you could tag it that would help us keep our dev docker setups at parity with our production version.

**Comment by derekjn** [comment]
Thanks @focusaurus , fixed!
