### ISSUE TITLE
Make combine work on output streams

### ISSUE THREAD

**Issue by derekjn** [pipelinedb/pipelinedb#1626]
```
CREATE CONTINUOUS VIEW v AS SELECT x, combine(new.avg) AS avg FROM output_of('some_cv') ...
```

**Comment by EliSnow** [comment]
This would be needed to use an output stream which has `percentile_cont` data and group it into a higher time interval, right?

**Comment by derekjn** [comment]
@EliSnow  correct.

**Comment by derekjn** [comment]
This will need to behave slightly differently than `combine` on CVs. IMO, the expected behavior of `combine` on output streams will be to essentially aggregate only the latest values for each group. Obviously, simply aggregating all output stream values doesn't make much sense.

There are a few approaches we could take here, and one that comes to mind that seems fairly simple and generic is to introduce the notion of "delta streams" that are like output streams except they contain a stream of incremental deltas applied to each CV row, rather than latest values.

We could then do a regular `combine` on these deltas. Deltas would essentially just be written from the incoming partials, rather than the combine output. Something like this feels more elegant and generic to me than trying to force regular output streams to work for this type of use case.

**Comment by derekjn** [comment]
An alternative to the above is to just add a `delta` row to the output stream:

```sql
CREATE CONTINUOUS VIEW v1 AS
  SELECT day(minute), combine((delta).count) FROM output_of('v1') GROUP BY day;
```

**Comment by derekjn** [comment]
@usmanm any thoughts on this?

**Comment by usmanm** [comment]
I think adding a `delta` row to the output stream is the optimal approach. It is going to be tricky (maybe even impossible) for aggregates like `bloom_agg`.

**Comment by usmanm** [comment]
Actually isn't the `combine` of deltas simply `new`?

**Comment by derekjn** [comment]
I'm thinking we just use the incoming partial as the delta, which seems like it should work, no?

**Comment by derekjn** [comment]
> Actually isn't the combine of deltas simply new?

Basically, but not of the aggregation group is different.

**Comment by derekjn** [comment]
We should also just not write delta tuples to SW output streams, since it doesn't even really make sense.

**Comment by usmanm** [comment]
Agreed, let's do deltas only for non SWs.
