### ISSUE TITLE
Unable to parse valid Json

### ISSUE THREAD

**Issue by sixtus** [pipelinedb/pipelinedb#1628]
Hi,

I am evaluating PipelineDB and hooked it up to a Kafka stream generated by golang's marshaller. So far, no tool had any issues with the JSON, however PipelineDB is acting up on JSON like:

```
{"screen": "7\" TFT"}
```

There seems to be double-unescaping going on.

**Comment by usmanm** [comment]
Moving this to: https://github.com/pipelinedb/pipeline_kafka/issues/27
