### ISSUE TITLE
Segment fault about  ExecInsertCQMatRelIndexTuples.

### ISSUE THREAD

**Issue by sangli00** [pipelinedb/pipelinedb#1631]
# 0  0x00000039dee30265 in raise () from /lib64/libc.so.6
# 1  0x00000039dee31d10 in abort () from /lib64/libc.so.6
# 2  0x0000000000980005 in ExceptionalCondition (conditionName=0xa0fb68 "!(((PageHeader) (page))->pd_special >= (__builtin_offse

tof (PageHeaderData, pd_linp)))", errorType=0xa0fafa "FailedAssertion", fileName=0xa0faf0 "nbtpage.c", lineNumber=629) at asser
t.c:68
# 3  0x00000000004e80f7 in _bt_getbuf (rel=0x2b4c121804f0, blkno=514, access=2) at nbtpage.c:629
# 4  0x00000000004e2d8c in _bt_split (rel=0x2b4c121804f0, buf=6233, cbuf=0, firstright=367, newitemoff=408, newitemsz=16, newite

m=0xd20c1d0, newitemonleft=0 '\000') at nbtinsert.c:977
# 5  0x00000000004e23fb in _bt_insertonpg (rel=0x2b4c121804f0, buf=6233, cbuf=0, stack=0xd20c1f8, itup=0xd20c1d0, newitemoff=408

, split_only_page=0 '\000') at nbtinsert.c:772
# 6  0x00000000004e1221 in _bt_doinsert (rel=0x2b4c121804f0, itup=0xd20c1d0, checkUnique=UNIQUE_CHECK_YES, heapRel=0x2b4c1218b57

0) at nbtinsert.c:204
# 7  0x00000000004ec988 in btinsert (fcinfo=0x7fff0ad99b80) at nbtree.c:243
# 8  0x000000000098abc2 in FunctionCall6Coll (flinfo=0xd251978, collation=0, arg1=47605721072880, arg2=140733375422432, arg3=140

RedHat  15:38:39
733375422400, arg4=220579532, arg5=47605721118064, arg6=1) at fmgr.c:1436
# 9  0x00000000004df3ef in index_insert (indexRelation=0x2b4c121804f0, values=0x7fff0ad99fe0, isnull=0x7fff0ad99fc0 "", heap_t_c

tid=0xd25c6cc, heapRelation=0x2b4c1218b570, checkUnique=UNIQUE_CHECK_YES) at indexam.c:226
# 10 0x0000000000773b7d in ExecInsertCQMatRelIndexTuples (indstate=0xd20c0b8, slot=0xd25bbc0, estate=0xd357298) at cqmatrel.c:11

6
# 11 0x0000000000773c47 in ExecCQMatRelInsert (ri=0xd20c0b8, slot=0xd25bbc0, estate=0xd357298) at cqmatrel.c:146
# 12 0x000000000078815e in sync_combine (state=0xd253738) at cont_combiner.c:603
# 13 0x0000000000788335 in sync_all (cont_exec=0xd249068) at cont_combiner.c:638
# 14 0x0000000000788f6f in ContinuousQueryCombinerMain () at cont_combiner.c:959
# 15 0x00000000007848ec in cont_bgworker_main (arg=47604543243848) at cont_scheduler.c:479
# 16 0x0000000000797eed in StartBackgroundWorker () at bgworker.c:734
# 17 0x00000000007ab34a in do_start_bgworker (rw=0xd16d380) at postmaster.c:5627
# 18 0x00000000007ab62b in maybe_start_bgworker () at postmaster.c:5802
# 19 0x00000000007a5d8c in ServerLoop () at postmaster.c:1781
# 20 0x00000000007a51e7 in PostmasterMain (argc=3, argv=0xd142710) at postmaster.c:1311
# 21 0x00000000006d346a in main (argc=3, argv=0xd142710) at main.c:224

@usmanm 
PipelineDB Version:0.9.1

**Comment by usmanm** [comment]
Can you try upgrading to 0.9.5?

**Comment by sangli00** [comment]
This is  online system, if  any release goto  upgrade, is impossibility.

**Comment by derekjn** [comment]
Have not seen this on recent versions.
