### ISSUE TITLE
multiple columns capability for keyed_max aggregate

### ISSUE THREAD

**Issue by peterbeasley** [pipelinedb/pipelinedb#1634]
I have a use case where devices are publishing their position to a stream:

```
CREATE STREAM raw_gps
( dev_id text,
  ts timestamp(3) with time zone,
  lat double precision,
  lng double precision);
```

A simple frontend might want to display the latest position of all of the devices, current capability in pipelineDB uses the following syntax where lat and lng is required to be concatenated into a single column for output:

```
CREATE CONTINUOUS VIEW latest_gps AS
    SELECT dev_id, max(ts), keyed_max (ts,lat || ',' || lng)
    FROM prd_raw_gps
    GROUP BY dev_id;
```

It would be nice to be able to keep these two (or 'n') items in separate columns in the view, i.e. so that they can be referenced individually in subsequent views.

Something like this would be nice:
`SELECT dev_id, max(ts), keyed_max (ts,lat), keyed_max(ts,lng)`
OR
`SELECT dev_id, max(ts), keyed_max (ts,(lat,lng))`

**Comment by derekjn** [comment]
@peterbeasley Another workaround in the meantime is to just use two aggregates:

```
CREATE CONTINUOUS VIEW latest_gps AS
    SELECT dev_id, max(ts),
        keyed_max (ts,lat) AS lat, keyed_max(ts, lng) as lng
    FROM prd_raw_gps
    GROUP BY dev_id;
```

`keyed_max` is a very lightweight aggregate so this is going to incur negligible performance impact.

**Comment by peterbeasley** [comment]
Ahh that's perfect, I didn't realise it was the naming keyed_max that my database was complaining about... renaming with the AS term has fixed my problem :-)

**Comment by derekjn** [comment]
It seems like just using multiple aggregates is the cleanest solution here.
