### ISSUE TITLE
Documentation Error

### ISSUE THREAD

**Issue by hedayat** [pipelinedb/pipelinedb#1636]
http://docs.pipelinedb.com/streams.html#insert says:
> It is an error to write to a stream that no active continuous views are reading from–the write will be rejected. This is to prevent against unknowingly writing data that is being silently ignored. See activation-deactivation for more information about active continuous views.

Apparently, this is no longer correct.

**Comment by derekjn** [comment]
Thanks @hedayat, fixed!
