### ISSUE TITLE
INSERT into an stream without any active continuous views -> INSERT lock up

### ISSUE THREAD

**Issue by hedayat** [pipelinedb/pipelinedb#1642]
Ubuntu 16.04
PipelineDB: 0.9.5

If I create an stream without any CVs and keep INSERTing data into it, after some time INSERT command get stuck. Apparently, it causes a dead-lock in the server. I should kill the server afterwards, as I didn't find anyway to be able to use the STREAM (or even to drop it) anymore. Creating a CV afterwards doesn't help either. So I should kill the server and start a new one, create a CV and then INSERT's will work fine.

**Comment by usmanm** [comment]
Hey man, I've been trying to reproduce this but haven't been able to. Can you give me a repro script or something? Are you running under the default settings? I am on the same OS.

**Comment by hedayat** [comment]
I'll try to see if I can provide a better way to reproduce the problem. Right now, I don't know exactly when the deadlock occurs, since I've an application which is constantly inserting into the stream and it takes some time until it locks up.

Note: I don't know if it is important or not, but the data is not directly written into the stream by the application. The application inserts into a view, which has an INSTEAD OF INSERT trigger, which insert the data into the stream or a temporary table (it decides between these based on a boolean column). Another function (based on some conditions and after some UPDATEs) removes rows from the temporary table and inserts them into the stream. This function is called in another connection periodically.

Yes, running under default settings.

**Comment by usmanm** [comment]
Oh interesting, that's definitely a more complex setup than what I used to repro. I simply created a stream and inserted into it using an infinite loop at max rate and saw no lock up. 

When everything locks up, can you share the output of:

```
SELECT
  locktype,
  relation::regclass,
  mode,
  transactionid,
  virtualtransaction,
  pid,
  granted
FROM pg_catalog.pg_locks;
```

**Comment by hedayat** [comment]
Yeah, sorry, I didn't notice that it might be important, but well... it might create additional locks...
OK, I will do it this Saturday and report back. :)

**Comment by hedayat** [comment]
Sorry for not providing that info sooner. I'll provide the wanted output on Saturday.

**Comment by usmanm** [comment]
No worries man, thanks for your help!

**Comment by hedayat** [comment]
```
sample=# SELECT
  locktype,
  relation::regclass,
  mode,
  transactionid,
  virtualtransaction,
  pid,
  granted
FROM pg_catalog.pg_locks;
  locktype  |         relation             |       mode       | transactionid | virtualtransaction |  pid  | granted
------------+------------------------------+------------------+---------------+--------------------+-------+---------
 relation   | my_locked_stream             | RowExclusiveLock |               | 13/147             | 18731 | t
 virtualxid |                              | ExclusiveLock    |               | 13/147             | 18731 | t
 relation   | pk_helper_table              | AccessShareLock  |               | 11/46468           |   869 | t
 relation   | my_temp_table_indexed_column | RowExclusiveLock |               | 11/46468           |   869 | t
 relation   | pk_my_temp_table             | RowExclusiveLock |               | 11/46468           |   869 | t
 relation   | helper_table                 | AccessShareLock  |               | 11/46468           |   869 | t
 relation   | my_locked_stream             | RowExclusiveLock |               | 11/46468           |   869 | t
 relation   | my_temp_table                | RowExclusiveLock |               | 11/46468           |   869 | t
 virtualxid |                              | ExclusiveLock    |               | 11/46468           |   869 | t
 relation   | my_locked_stream             | RowExclusiveLock |               | 8/94208            |   868 | t
 relation   | my_temp_table                | RowExclusiveLock |               | 8/94208            |   868 | t
 relation   | helper_table                 | AccessShareLock  |               | 8/94208            |   868 | t
 relation   | insertion_view               | RowExclusiveLock |               | 8/94208            |   868 | t
 virtualxid |                              | ExclusiveLock    |               | 8/94208            |   868 | t
 relation   | pg_locks                     | AccessShareLock  |               | 14/267             | 20269 | t
 virtualxid |                              | ExclusiveLock    |               | 14/267             | 20269 | t

```

**Comment by usmanm** [comment]
All these locks are granted so it's probably deadlocking somewhere else.

**Comment by hedayat** [comment]
OK, I'll try to provide a simple reproduction script.

**Comment by hedayat** [comment]
I can reproduce it in a very simple form. First, create a sample DB and stream:
```
create database tmp;
CREATE STREAM my_stream
(
      t1 integer,
      t2 text
);

```

Then, with a while loop under shell I can reproduce the problem in a few seconds:
`$ while sleep 0.05; do echo -n "." 1>&2; echo "insert INTO my_stream VALUES (1, 'hi');"; done | /usr/lib/pipelinedb/bin/psql -p 5433 -Upipeline tmp`

In a sample run, only 136 `INSERT 0 1` appears and then only dots are seen.

**Comment by usmanm** [comment]
Ok, I can repro it, thanks! Will push a fix soon.

**Comment by usmanm** [comment]
This is fixed on `master` now. Thanks for your help!

**Comment by hedayat** [comment]
Great, thanks :)
