### ISSUE TITLE
pipelinedb-contrib package

### ISSUE THREAD

**Issue by joshk0** [pipelinedb/pipelinedb#1645]
I need access to modules in the contrib/ source directory, such as hstore and fuzzystrmatch.

It would be cleaner if the pipelinedb package contained these or an auxiliary pipelinedb-contrib package contained them. Right now, I have to check out pipelinedb source, build, pray and hope mine are ABI compatible with the pipelinedb binary i installed, ... it's not a great experience.

Thanks!

**Comment by derekjn** [comment]
@joshk0 this will no longer be an issue after #1596, which is coming in the near future. We won't have many free cycles to spend on a `contrib` package before #1596, so hopefully you can hold out until then. And as always, we appreciate the thoughtful feedback!
