### ISSUE TITLE
Failed to load Kafka Extension: Undefined Symbol IsInferredStream

### ISSUE THREAD

**Issue by jamesmintram** [pipelinedb/pipelinedb#1646]
I am trying to load the Kafka Extension within docker. When I call

```CREATE EXTENSION pipeline_kafka;```

I get the following error:
```
ERROR:  could not load library "/usr/lib/pipelinedb/lib/pipelinedb/pipeline_kafka.so": /usr/lib/pipelinedb/lib/pipelinedb/pipeline_kafka.so: undefined symbol: IsInferredStream
```

This is the Dockerfile I am using:

```
FROM pipelinedb/pipelinedb

RUN apt-get update && apt-get install -y python && rm -rf /var/lib/apt/lists/*
RUN git clone -b 0.9.1 https://github.com/edenhill/librdkafka.git ~/librdkafka
RUN cd ~/librdkafka && ./configure --disable-ssl --prefix=/usr && make && sudo make install

RUN git clone -b 0.9.4 https://github.com/pipelinedb/pipeline_kafka.git ~/pipeline_kafka
RUN cd ~/pipeline_kafka && ./configure && make && sudo make install

ADD ./mnt/  /mnt/pipelinedb/
```

and the pipelinedb.conf file is a default config with kafka added to the extensions list, it is here: https://gist.github.com/jamesmintram/26ed20e6685ed066fd25d54bd5777801

**Comment by derekjn** [comment]
Hi @jamesmintram, can you use the `master` branch of `pipeline_kafka`?

Also, moving this to: pipelinedb/pipeline_kafka#43
