### ISSUE TITLE
Use a Stream's composite type in a function

### ISSUE THREAD

**Issue by brettlaforge** [pipelinedb/pipelinedb#1653]
As I understand when creating a Stream it also creates a corresponding composite type. I'd like to use this type as an argument in a function.

Example:

```sql
CREATE STREAM mystream (
    id int,
    name varchar(255)
);

CREATE OR REPLACE FUNCTION myfunc(item mystream)
RETURNS BOOL AS
$$
    BEGIN
        RETURN FALSE;
    END;
$$
LANGUAGE plpgsql;
```

I get the following error:
ERROR:  relation "mystream" is not a table
CONTEXT:  compilation of PL/pgSQL function "myfunc" near line 1

I think this is because PL/pgSQL checks to see if the relation type is one of a few different types.
pipelinedb/src/pl/plpgsql/src/pl_comp.c :: build_row_from_class

I plan on using this function in a Continuous Transform and I'd like to pass the entire stream record to the function.

Version
PipelineDB 0.9.3

**Comment by usmanm** [comment]
Fixed via 28097cb06e7c8e085977f71c4a87cf8976f2032b
