### ISSUE TITLE
Continuous transform can't  used pg_notify.

### ISSUE THREAD

**Issue by sangli00** [pipelinedb/pipelinedb#1654]
version: pipelineDB-0.9.5

I  have question.
why this function pg_notify is not seed msg?

`postgres=# insert into str1(x) select 12;
INSERT 0 1
`
I can't find any notify msg.but I executor
`
postgres=# select pg_notify('foobar','test');
 pg_notify
-----------

(1 row)
`

I can find msg `abcdefg` and `test`.
`abcdefg` in function func_3()

about transaction?

```
create stream str1(x bigint);
create stream str2(x bigint y bigint);
create continuous view cv_2 as select x,y from str2;
 
create continuous transform trans as select 
x ,func_2(x) as y from str1
THEN EXECUTE PROCEDURE pipeline_stream_insert('str2');

create or replace function func_2(x bigint)
returns bigint as $$

declare


begin

perform func_3();
return x+1;

end
$$
language plpgsql;


create or replace function func_3()
returns void as $$
declare
begin

perform pg_notify('foobar','abcdefg');

raise log '%','------------';


end
$$
language plpgsql;

```

**Comment by sangli00** [comment]
@usmanm  can you give me some suggest?

**Comment by usmanm** [comment]
I can see the log statement in the server logs:
```
LOG:  ------------
CONTEXT:  SQL statement "SELECT func_3()"
	PL/pgSQL function func_2(bigint) line 8 at PERFORM
STATEMENT:  trans
```

How are you checking `pg_notify(...)`?

**Comment by sangli00** [comment]
yes,server logs is OK.
but ,pg_notify is can't run,because ```pg_notify```  need transaction is commit.

I used 
retval = select(sock + 1, &rfds, &wfds, NULL, NULL);
notify = PQnotifies(conn)
checking pg_notify.

if i executor select pg_notify('footer','abde');
```select``` is OK
but,transform executor pg_notify,I can't  get any msg.

**Comment by sangli00** [comment]
If you can read source ,I can seed to you mail.

**Comment by usmanm** [comment]
So `pg_notify()` won't work with continuous transforms. It must be called from the process forked for the client connection, but in the case of continuous transforms its called from a worker process. #1582 this could be used as an alternative to get notified when a transform outputs something. It'll be implemented in the next few days.

**Comment by sangli00** [comment]
OK Thanks @usmanm
