### ISSUE TITLE
Log offending column when a transform's schema doesn't align with pipeline_stream_insert stream

### ISSUE THREAD

**Issue by derekjn** [pipelinedb/pipelinedb#1661]
With transforms with huge target lists, it's cumbersome to figure this out manually.

**Comment by derekjn** [comment]
We also might want to relax the check to just require that the transform's columns be coercible into the target stream's columns.

**Comment by usmanm** [comment]
Now that CTs have output streams too we should just do #1640, so people simply read off the output stream rather than create a new stream and `pipeline_stream_insert` into it.

**Comment by derekjn** [comment]
As long as we keep `pipeline_stream_insert`, we should still improve the error messaging here though.

**Comment by derekjn** [comment]
This is kind of ugly and results in duplicate, unnecessarily complicated error reporting code. I think given that the right way to do this is to just use output streams, we're fine here.
