### ISSUE TITLE
Add TTL support

### ISSUE THREAD

**Issue by derekjn** [pipelinedb/pipelinedb#1662]
SWs are often used as a way to give CV rows TTLs. While convenient, SWs incur CPU and disk overhead and are generally overkill for this use case. Since time-based groupings are very common, we should provide a simpler, cheaper way to give rows a TTL. e.g.:

```
CREATE CONTINUOUS VIEW v WITH (ttl='30 days', ttl_column='day') AS
  SELECT day(arrival_timestamp), count(*) FROM stream GROUP BY day
```

The autovac should simply delete all rows for which the TTL column is expired. 

- [x] Add TTL support
- [x] Rename `max_age` to `sliding_window` or `sw`

**Comment by schapirama** [comment]
Yes! +1
