### ISSUE TITLE
Why pipelineDB pg_xlog is very bigger?

### ISSUE THREAD

**Issue by sangli00** [pipelinedb/pipelinedb#1664]
I think  worker process is cant't CKPT.
how to fixed this problem?

version:0.9.5

**Comment by derekjn** [comment]
@sangli00 can you give us any more information? Is there anything in the logs?

**Comment by sangli00** [comment]
@derekjn 
```continuous_triggers_enabled = on
wal_level = logical
#Specifies the maximum number of concurrent connections from standby servers or streaming base backup clients
max_wal_senders = 3
#Specifies the maximum number of replication slots that the server can support
max_replication_slots = 3
wal_keep_segments = 0		# in logfile segments, 16MB each; 0 disables
min_wal_size=80MB
checkpoint_completion_target=0.5
max_wal_size=1GB```

this is pipelined.conf 
I used ```continuous_triggers_enabled```

**Comment by jarwin123** [comment]
yes，i have the same problem in pipelinedb 0.9.5, and my pipelinedb.conf is default configuration. the pg_xlog have more files that size is 16MB。i have a background process（it‘s Tcp server，it receives tuples and through  ·CopyIntoStream· function insert some stream named xxx  ）in pipelinedb。

**Comment by derekjn** [comment]
I don't think there is any issue here, as this is lower-level than anything PipelineDB really manages. Long-running transactions could be the problem, but without more information/errors/logs I'm afraid we can't be particularly helpful here.
