### ISSUE TITLE
The pipeline-dumpall command is referencing 'pg_dump'

### ISSUE THREAD

**Issue by brettlaforge** [pipelinedb/pipelinedb#1667]
When I run:

```
$ pipeline-dumpall
The program "pg_dump" is needed by pipeline-dumpall but was not found in the
same directory as "/usr/lib/pipelinedb/bin/pipeline-dumpall".
Check your installation.
```

The cmds pipeline-dump and pipeline-dumpall are located together in my pipeline bin directory. I just think the pipeline-dumpall command is searching for pg_dump instead of pipeline-dump.

**Comment by usmanm** [comment]
What version are you on? This was fixed a while ago: https://github.com/pipelinedb/pipelinedb/commit/1d0fb12f1baa28b5dafd4b578bdddd7ed1a75ed4

**Comment by brettlaforge** [comment]
0.9.3 -- my bad. You are correct. This was fixed. I did a quick search using 'pipeline-dumpall' and the commit didn't come up. Weird. I must have been searching an older version.

Thanks for you time and an amazing product.
