### ISSUE TITLE
the worker process's memory increase all the time

### ISSUE THREAD

**Issue by liang3rd** [pipelinedb/pipelinedb#1671]
create stream stream_1(id bigint, ts timestamp without time zone);
create stream stream_2(id bigint,ts char(32));
create stream stream_3(id bigint,date char(16), time char(16));
create sequence  seq_1 start 1;

create continuous transform trans_1_2 as 
select id as id,
to_char(ts,'yyyy-MM-dd hh24:mi:ss.ms')::char(32) as ts 
from stream_1 
then execute procedure pipeline_stream_insert('stream_2');

create continuous transform trans_1_3 as
select id as id,
to_char(ts,'yyyy-MM-dd')::char(16) as date,
to_char(ts,'hh24:mi:ss.ms')::char(16) as time 
from stream_1 then 
execute procedure pipeline_stream_insert('stream_3');

create continuous view cv_2 as select id,ts from stream_2;
create continuous view cv_3 as select date,time ,id from stream_3;
--create continuous view cv_2 as select count(*) from stream_2;
--create continuous view cv_3 as select count(*) from stream_3;

CREATE OR REPLACE FUNCTION public.sdf()
RETURNS void
AS $function$
BEGIN
 raise notice 'sdf_lianggj';
end;
$function$  LANGUAGE plpgsql;
 
CREATE OR REPLACE FUNCTION umparse_trigger() RETURNS trigger AS $$
BEGIN    
 PERFORM sdf();
 return new;
END;
$$ LANGUAGE plpgsql;

CREATE CONTINUOUS TRANSFORM trans_umparse AS 
SELECT (new).ts FROM output_of('cv_2') 
THEN EXECUTE PROCEDURE umparse_trigger();

--CREATE CONTINUOUS TRANSFORM trans_umparse1 AS 
--SELECT ts FROM stream_2
--THEN EXECUTE PROCEDURE umparse_trigger();

-----------------------------------------------------------------------------------------
pipelinedb version 0.9.5
when I execute the sql statement( insert into stream_1 values(nextval('seq_1'), now()); ), the worker process's momery increases all the time. Is there somethine I use wrongly or it's a bug, thanks

**Comment by derekjn** [comment]
Hi @liang3rd,

Over what period of time did you notice this memory leak? So far I've been unable to reproduce it after running your insert statement for a few minutes:

```
while (true) do pipeline -c "insert into stream_1 (id, ts) SELECT nextval('seq_1'), now() FROM generate_series(1, 10000);"; done
```

**Comment by liang3rd** [comment]
@derekjn ,
sorry, I forgot a thing(maybe should change the configure file: log_min_messages = notice), so the notice can be printed out, and the memory inceases.

**Comment by liang3rd** [comment]
these are the sql file and shell script file.
[sql.txt](https://github.com/pipelinedb/pipelinedb/files/574425/sql.txt)
[sh.txt](https://github.com/pipelinedb/pipelinedb/files/574432/sh.txt)

**Comment by derekjn** [comment]
Thanks @liang3rd! I still cannot reproduce a memory leak with the information given. It may be the case that your terminal is getting flooded with log messages and that is the source of the memory consumption. Can you determine which specific PipelineDB process or processes is showing increasing memory consumption (using `ps` or some other OS-level tool), and share your findings here?

Ideally we can get snapshots of memory usage for this process over time to show that it is indeed potentially leaking memory.

**Comment by liang3rd** [comment]
create stream stream_1(id bigint, ts timestamp without time zone);
create stream stream_2(id bigint,ts char(32));
create stream stream_3(id bigint,date char(16), time char(16));
create sequence seq_1 start 1;

create continuous transform trans_1_2 as
select id as id,
to_char(ts,'yyyy-MM-dd hh24:mi:ss.ms')::char(32) as ts
from stream_1
then execute procedure pipeline_stream_insert('stream_2');

create continuous transform trans_1_3 as
select id as id,
to_char(ts,'yyyy-MM-dd')::char(16) as date,
to_char(ts,'hh24:mi:ss.ms')::char(16) as time
from stream_1 then
execute procedure pipeline_stream_insert('stream_3');

create continuous view cv_2 as select id,ts from stream_2;
create continuous view cv_3 as select date,time ,id from stream_3;

CREATE OR REPLACE FUNCTION public.sdf()
RETURNS void
AS $function$
BEGIN
raise warning 'sdf_lianggj';
end;
$function$ LANGUAGE plpgsql;

CREATE OR REPLACE FUNCTION umparse_trigger() RETURNS trigger AS $$
BEGIN
PERFORM sdf();
return new;
END;
$$ LANGUAGE plpgsql;

CREATE CONTINUOUS TRANSFORM trans_umparse AS
SELECT (new).ts FROM output_of('cv_2')
THEN EXECUTE PROCEDURE umparse_trigger();

---------------------------------------------------------------------------------------
[sql.txt](https://github.com/pipelinedb/pipelinedb/files/574566/sql.txt)
[sh.txt](https://github.com/pipelinedb/pipelinedb/files/574567/sh.txt)

my test's steps:
1, init a database cluster;
2, execute the all "create" sql above;
3, change file name "sql.txt" to "test.sql", change file name "sh.txt" to "test.sh";
4, execute ./test.sh

maybe some details of the steps need to change according your test environment.

my test is on a virtual machine that has 2GB memory.
lsb_release -a
LSB Version:    :core-4.0-amd64:core-4.0-ia32:core-4.0-noarch:graphics-4.0-amd64:graphics-4.0-ia32:graphics-4.0-noarch:printing-4.0-amd64:printing-4.0-ia32:printing-4.0-noarch
Distributor ID: RedHatEnterpriseServer
Description:    Red Hat Enterprise Linux Server release 5.8 (Tikanga)
Release:        5.8
Codename:       Tikanga

-----------------------------------------------------------------------------------------
after about 15 minutes, I stop the "./test.sh" and use gdb attach the worker0 progress, and execute: call MemoryContextStats(TopMemoryContext)
the "ErrorContext" is large unusual most.

(gdb) info proc
process 13658
cmdline = 'pipelinedb: bgworker: worker0 [pipeline]   '
cwd = '/home/pipeline/pg095'
exe = '/usr/local/pg095/bin/pipelinedb'

TopMemoryContext: 138040 total in 16 blocks; 14872 free (32 chunks); 123168 used
  PL/pgSQL function context: 8192 total in 1 blocks; 4864 free (0 chunks); 3328 used
  PLpgSQL cast info: 0 total in 0 blocks; 0 free (0 chunks); 0 used
    PLpgSQL cast cache: 8192 total in 1 blocks; 2664 free (0 chunks); 5528 used
  PL/pgSQL function context: 24576 total in 2 blocks; 16832 free (3 chunks); 7744 used
  CFuncHash: 8192 total in 1 blocks; 1640 free (0 chunks); 6552 used
  Rendezvous variable hash: 8192 total in 1 blocks; 1640 free (0 chunks); 6552 used
  PLpgSQL function cache: 24528 total in 2 blocks; 3712 free (0 chunks); 20816 used
  Type information cache: 24472 total in 2 blocks; 3712 free (0 chunks); 20760 used
  ipc_tuple_reader MemoryContext: 8192 total in 1 blocks; 8160 free (0 chunks); 32 used
  ContExecutor Context: 16512 total in 2 blocks; 8040 free (2 chunks); 8472 used
    QueryStateCxt: 57344 total in 3 blocks; 30808 free (4 chunks); 26536 used
      QueryStateTmpCxt: 8192 total in 1 blocks; 8160 free (0 chunks); 32 used
    QueryStateCxt: 57344 total in 3 blocks; 28760 free (2 chunks); 28584 used
      QueryStateTmpCxt: 8192 total in 1 blocks; 8160 free (0 chunks); 32 used
    QueryStateCxt: 57344 total in 3 blocks; 31920 free (2 chunks); 25424 used
      QueryStateTmpCxt: 8192 total in 1 blocks; 8160 free (0 chunks); 32 used
    QueryStateCxt: 122880 total in 4 blocks; 69920 free (3 chunks); 52960 used
      QueryStateTmpCxt: 8192 total in 1 blocks; 8160 free (0 chunks); 32 used
    QueryStateCxt: 57344 total in 3 blocks; 17816 free (4 chunks); 39528 used
      QueryStateTmpCxt: 8192 total in 1 blocks; 8160 free (0 chunks); 32 used
    ContQueryTransactionContext: 0 total in 0 blocks; 0 free (0 chunks); 0 used
    ContQueryBatchContext: 8192 total in 1 blocks; 8160 free (0 chunks); 32 used
  pzmq MemoryContext: 8192 total in 1 blocks; 6032 free (0 chunks); 2160 used
    pzmq dests HTAB: 18888 total in 2 blocks; 3712 free (0 chunks); 15176 used
  Operator class cache: 8192 total in 1 blocks; 1640 free (0 chunks); 6552 used
  smgr relation table: 24576 total in 2 blocks; 9752 free (3 chunks); 14824 used
  TransactionAbortContext: 32768 total in 1 blocks; 32736 free (0 chunks); 32 used
  Portal hash: 8192 total in 1 blocks; 1640 free (0 chunks); 6552 used
  PortalMemory: 0 total in 0 blocks; 0 free (0 chunks); 0 used
  Relcache by OID: 24576 total in 2 blocks; 12752 free (2 chunks); 11824 used
  CacheMemoryContext: 1335800 total in 16 blocks; 403424 free (17 chunks); 932376 used
    CachedPlan: 1024 total in 1 blocks; 64 free (0 chunks); 960 used
    CachedPlanSource: 3072 total in 2 blocks; 1688 free (0 chunks); 1384 used
      CachedPlanQuery: 3072 total in 2 blocks; 2000 free (1 chunks); 1072 used
    SPI Plan: 1024 total in 1 blocks; 808 free (0 chunks); 216 used
    cv_2: 7168 total in 3 blocks; 3360 free (0 chunks); 3808 used
    pg_db_role_setting_databaseid_rol_index: 1024 total in 1 blocks; 8 free (0 chunks); 1016 used
    pg_user_mapping_user_server_index: 1024 total in 1 blocks; 8 free (0 chunks); 1016 used
    pg_user_mapping_oid_index: 1024 total in 1 blocks; 144 free (0 chunks); 880 used
    pg_type_oid_index: 1024 total in 1 blocks; 88 free (0 chunks); 936 used
    pg_type_typname_nsp_index: 3072 total in 2 blocks; 1968 free (0 chunks); 1104 used
    pg_ts_template_oid_index: 1024 total in 1 blocks; 144 free (0 chunks); 880 used
    pg_ts_template_tmplname_index: 1024 total in 1 blocks; 8 free (0 chunks); 1016 used
    pg_ts_parser_oid_index: 1024 total in 1 blocks; 144 free (0 chunks); 880 used
    pg_ts_parser_prsname_index: 1024 total in 1 blocks; 8 free (0 chunks); 1016 used
    pg_ts_dict_oid_index: 1024 total in 1 blocks; 144 free (0 chunks); 880 used
    pg_ts_dict_dictname_index: 1024 total in 1 blocks; 8 free (0 chunks); 1016 used
    pg_ts_config_oid_index: 1024 total in 1 blocks; 144 free (0 chunks); 880 used
    pg_ts_config_cfgname_index: 1024 total in 1 blocks; 8 free (0 chunks); 1016 used
    pg_ts_config_map_index: 3072 total in 2 blocks; 1728 free (1 chunks); 1344 used
    pg_transform_type_lang_index: 1024 total in 1 blocks; 8 free (0 chunks); 1016 used
    pg_transform_oid_index: 1024 total in 1 blocks; 144 free (0 chunks); 880 used
    pg_tablespace_oid_index: 1024 total in 1 blocks; 144 free (0 chunks); 880 used
    pg_statistic_relid_att_inh_index: 3072 total in 2 blocks; 1672 free (1 chunks); 1400 used
    pg_replication_origin_roname_index: 1024 total in 1 blocks; 144 free (0 chunks); 880 used
    pg_replication_origin_roiident_index: 1024 total in 1 blocks; 144 free (0 chunks); 880 used
    pg_range_rngtypid_index: 1024 total in 1 blocks; 144 free (0 chunks); 880 used
    pg_proc_oid_index: 1024 total in 1 blocks; 88 free (0 chunks); 936 used
    pg_proc_proname_args_nsp_index: 3072 total in 2 blocks; 1672 free (1 chunks); 1400 used
    pipeline_stream_oid_index: 1024 total in 1 blocks; 144 free (0 chunks); 880 used
    pipeline_stream_relid_index: 1024 total in 1 blocks; 88 free (0 chunks); 936 used
    pipeline_query_oid_index: 1024 total in 1 blocks; 144 free (0 chunks); 880 used
    pipeline_query_matrelid_index: 1024 total in 1 blocks; 144 free (0 chunks); 880 used
    pipeline_query_relid_index: 1024 total in 1 blocks; 88 free (0 chunks); 936 used
    pipeline_query_id_index: 1024 total in 1 blocks; 88 free (0 chunks); 936 used
    pipeline_combine_transfn_index: 1024 total in 1 blocks; 8 free (0 chunks); 1016 used
    pipeline_combine_oid_index: 1024 total in 1 blocks; 144 free (0 chunks); 880 used
    pg_opfamily_oid_index: 1024 total in 1 blocks; 144 free (0 chunks); 880 used
    pg_opfamily_am_name_nsp_index: 3072 total in 2 blocks; 1728 free (1 chunks); 1344 used
    pg_operator_oid_index: 1024 total in 1 blocks; 144 free (0 chunks); 880 used
    pg_operator_oprname_l_r_n_index: 3072 total in 2 blocks; 1728 free (1 chunks); 1344 used
    pg_namespace_oid_index: 1024 total in 1 blocks; 88 free (0 chunks); 936 used
    pg_namespace_nspname_index: 1024 total in 1 blocks; 88 free (0 chunks); 936 used
    pg_language_oid_index: 1024 total in 1 blocks; 88 free (0 chunks); 936 used
    pg_language_name_index: 1024 total in 1 blocks; 144 free (0 chunks); 880 used
    pg_foreign_table_relid_index: 1024 total in 1 blocks; 88 free (0 chunks); 936 used
    pg_foreign_server_oid_index: 1024 total in 1 blocks; 88 free (0 chunks); 936 used
    pg_foreign_server_name_index: 1024 total in 1 blocks; 144 free (0 chunks); 880 used
    pg_foreign_data_wrapper_oid_index: 1024 total in 1 blocks; 88 free (0 chunks); 936 used
    pg_foreign_data_wrapper_name_index: 1024 total in 1 blocks; 144 free (0 chunks); 880 used
    pg_event_trigger_oid_index: 1024 total in 1 blocks; 144 free (0 chunks); 880 used
    pg_event_trigger_evtname_index: 1024 total in 1 blocks; 144 free (0 chunks); 880 used
    pg_enum_typid_label_index: 1024 total in 1 blocks; 8 free (0 chunks); 1016 used
    pg_enum_oid_index: 1024 total in 1 blocks; 144 free (0 chunks); 880 used
    pg_default_acl_role_nsp_obj_index: 3072 total in 2 blocks; 1728 free (1 chunks); 1344 used
    pg_conversion_oid_index: 1024 total in 1 blocks; 144 free (0 chunks); 880 used
    pg_constraint_oid_index: 1024 total in 1 blocks; 144 free (0 chunks); 880 used
    pg_conversion_name_nsp_index: 1024 total in 1 blocks; 8 free (0 chunks); 1016 used
    pg_conversion_default_index: 3072 total in 2 blocks; 1728 free (1 chunks); 1344 used
    pg_collation_oid_index: 1024 total in 1 blocks; 144 free (0 chunks); 880 used
    pg_collation_name_enc_nsp_index: 3072 total in 2 blocks; 1728 free (1 chunks); 1344 used
    pg_opclass_am_name_nsp_index: 3072 total in 2 blocks; 1728 free (1 chunks); 1344 used
    pg_cast_source_target_index: 3072 total in 2 blocks; 1968 free (0 chunks); 1104 used
    pg_auth_members_role_member_index: 1024 total in 1 blocks; 8 free (0 chunks); 1016 used
    pg_attribute_relid_attnam_index: 1024 total in 1 blocks; 8 free (0 chunks); 1016 used
    pg_amop_fam_strat_index: 3072 total in 2 blocks; 1728 free (1 chunks); 1344 used
    pg_amop_opr_fam_index: 3072 total in 2 blocks; 1728 free (1 chunks); 1344 used
    pg_aggregate_fnoid_index: 1024 total in 1 blocks; 144 free (0 chunks); 880 used
    pg_auth_members_member_role_index: 1024 total in 1 blocks; 8 free (0 chunks); 1016 used
    pg_authid_oid_index: 1024 total in 1 blocks; 88 free (0 chunks); 936 used
    pg_authid_rolname_index: 1024 total in 1 blocks; 144 free (0 chunks); 880 used
    pg_database_oid_index: 1024 total in 1 blocks; 88 free (0 chunks); 936 used
    pg_database_datname_index: 1024 total in 1 blocks; 144 free (0 chunks); 880 used
    pg_trigger_tgrelid_tgname_index: 1024 total in 1 blocks; 8 free (0 chunks); 1016 used
    pg_rewrite_rel_rulename_index: 3072 total in 2 blocks; 1968 free (0 chunks); 1104 used
    pg_amproc_fam_proc_index: 3072 total in 2 blocks; 1672 free (1 chunks); 1400 used
    pg_opclass_oid_index: 1024 total in 1 blocks; 88 free (0 chunks); 936 used
    pg_index_indexrelid_index: 1024 total in 1 blocks; 88 free (0 chunks); 936 used
    pg_attribute_relid_attnum_index: 3072 total in 2 blocks; 1968 free (0 chunks); 1104 used
    pg_class_oid_index: 1024 total in 1 blocks; 88 free (0 chunks); 936 used
  WAL record construction: 49768 total in 2 blocks; 6576 free (0 chunks); 43192 used
  PrivateRefCount: 8192 total in 1 blocks; 3712 free (0 chunks); 4480 used
  MdSmgr: 8192 total in 1 blocks; 7640 free (2 chunks); 552 used
  ident parser context: 0 total in 0 blocks; 0 free (0 chunks); 0 used
  hba parser context: 7168 total in 3 blocks; 3920 free (1 chunks); 3248 used
  LOCALLOCK hash: 8192 total in 1 blocks; 1640 free (0 chunks); 6552 used
  Timezones: 83480 total in 2 blocks; 3712 free (0 chunks); 79768 used
  Postmaster: 8192 total in 1 blocks; 7776 free (5 chunks); 416 used
  ErrorContext: 147030016 total in 17948 blocks; 83136 free (8 chunks); 146946880 used

**Comment by derekjn** [comment]
@liang3rd this is fixed in `master`. There was a memory leak for allocations being made for log messages, which aren't expected to be made for every event written to a stream. Technically it was a bug, but it was only showing up because the test function is doing so much logging. You're not going to see this issue once you implement that function for actual use, assuming it doesn't log something on every execution :)

Thanks for reporting!
