### ISSUE TITLE
Remove all custom node types

### ISSUE THREAD

**Issue by derekjn** [pipelinedb/pipelinedb#1682]
**Plan nodes**
* We may just want to use a custom scan node for some of these.
- [ ] `TuplestoreScan`
  * Can probably replace this with some kind of range function node that simply reads from a process-local 
`Tuplestorestate`
  * `TuplestoreScanState`
- [ ] `PhysicalGroupLookup`
  * Now that matrels have PKs and PG has `UPSERT`, this should probably be straightforward (and cleaner) to eliminate
  * `PhysicalGroupLookupState`
- [ ] `nodeAgg`
- [x] ContinuousUnique
  * can probably just rip this and associated complexity out completely, it's not really used and there are other ways to get the same results (#1708)

**Planner path**
- [ ] PhysicalGroupLookupPath

**Comment by usmanm** [comment]
I think executor nodes are fine, since we can have executor hooks. 

Parse nodes should be removed and all syntax stuff we've added should be replaced with function calls

**Comment by usmanm** [comment]
A good starting point could be to just create the extension's `.sql` fine and go from there

**Comment by derekjn** [comment]
> I think executor nodes are fine, since we can have executor hooks.

The only executor hooks currently available are start/stop. There are no node-level hooks, unless I'm mistaken.

**Comment by derekjn** [comment]
This should also include any custom login in `nodeAgg`.

**Comment by derekjn** [comment]
https://www.postgresql.org/docs/9.6/static/custom-scan.html

**Comment by derekjn** [comment]
Break this out into separate issues as necessary.
