### ISSUE TITLE
Use standard syntax

### ISSUE THREAD

**Issue by derekjn** [pipelinedb/pipelinedb#1684]
- [ ] `CREATE CONTINUOUS VIEW` -> ??
- [ ] `CREATE CONTINUOUS TRANSFORM` -> ??
- [ ] `CREATE STREAM` -> `CREATE FOREIGN TABLE`
- [ ] `ACTIVATE/DEACTIVATE` -> function calls

Streams are already foreign tables internally, so those are easy. `ACTIVATE/DEACTIVATE` are fairly rarely used and are intuitive as functions. 

`CREATE CONTINUOUS VIEW/TRANSFORM` require some thought and discussion though. While we could easily just wrap them in functions, I think we should try to represent them as standard PostgreSQL objects so users can leverage existing tooling when managing them.

My initial ideas:

* **CVs**: `CREATE MATERIALIZED VIEW v WITH (materializer='pipelinedb') ...` (or something along these lines). A materialized view over a stream is just automatically recognized and handled accordingly.

* **Transforms**: Possibly use `CREATE RULE`. Transforms are a bit tricky because they don't map particularly well to any standard PG objects, although I think rules are fairly intuitive and the syntax is probably expressive enough. Some other ways we could represent transforms:

  * `CREATE VIEW` over a stream
  * `CREATE TRIGGER` on a stream

**Comment by derekjn** [comment]
After thinking through this some more, I think CVs can be intuitively represented by `MATERIALIZED VIEW`s over streams. I think transforms can also be intuitively represented with regular `VIEW`s over streams. Writing to a stream would then just be a regular `TRIGGER` definition:

    CREATE VIEW transform AS SELECT x, y, z FROM input_stream;
    CREATE MATERIALIZED VIEW cv AS SELECT sum(x) FROM transform;

    CREATE TRIGGER t ON transform
      AFTER INSERT EXECUTE PROCEDURE pipeline_stream_insert('another_stream');

**Comment by usmanm** [comment]
I think Postgres only allows `INSTEAD OF` triggers on views, so this might not work.

**Comment by derekjn** [comment]
I personally don't feel that we're hammering anything into the standard syntax, materialized views over streams seem pretty intuitive to me and map well to a CV, and a view over a stream is basically exactly what a transform already is.

Are there any good examples of widely used extensions that use DDL via UDFs? I think the general approach is to create objects with regular DDL, and then call some function on them to apply extended behavior to it. Either way, we will likely still want to create top-level objects via DDL.

**Comment by derekjn** [comment]
To recap our convo: triggers are the only thing that doesn't really fit here. `CREATE MATERIALIZED VIEW` for CVs and `CREATE VIEW` for transforms make sense and are intuitive. We just need to figure out how to map `THEN EXECUTE PROCEDURE` to standard syntax.

**Comment by derekjn** [comment]
What about something like this?

    CREATE VIEW xform AS
      SELECT pipeline_stream_insert(s, 'output_stream') FROM input_stream s;

**Comment by derekjn** [comment]
* #1699 
* #1700 
* #1701 
* #1702
