### ISSUE TITLE
Vacuum Continuous view is WARING.

### ISSUE THREAD

**Issue by sangli00** [pipelinedb/pipelinedb#1694]
My pipelineDB is very big,I need execute vacuum continuous  view.
This continuous view is so big.I execute `vacuum continuous view`
This continuous view is sliding window continuous view.

WARNING:  relation "pg_toast_685819" page 944409 is uninitialized --- fixing

**Comment by derekjn** [comment]
@sangli00 can you add the CV and stream definitions? We can't be very helpful without more information to go off of.

**Comment by liang3rd** [comment]
@sangli00 probably because of long term transaction, ^_^

**Comment by derekjn** [comment]
Closing for now, will reopen if we can get more information.
