### ISSUE TITLE
WHY continuous view is not closed?

### ISSUE THREAD

**Issue by sangli00** [pipelinedb/pipelinedb#1696]
detail log:
STATEMENT:  comm_unique_visitor_main_source_device
WARNING:  relcache reference leak: relation "comm_unique_visitor_main_source_device_mrel" not closed
ERROR:  unexpected chunk number 0 (expected 1) for toast value 331303021 in pg_toast_307803075
STATEMENT:  comm_unique_visitor_main_page_area
ERROR:  unexpected chunk number 0 (expected 1) for toast value 331301842 in pg_toast_307803183
STATEMENT:  comm_unique_visitor_main_isp_area
WARNING:  relcache reference leak: relation "comm_unique_visitor_main_isp_area_mrel" not closed
WARNING:  relcache reference leak: relation "comm_unique_visitor_main_page_area_mrel" not closed
ERROR:  unexpected chunk number 0 (expected 1) for toast value 331301902 in pg_toast_685891
STATEMENT:  comm_unique_visitor_main_source_device
WARNING:  relcache reference leak: relation "comm_unique_visitor_main_source_device_mrel" not closed
ERROR:  unexpected chunk number 0 (expected 1) for toast value 331301902 in pg_toast_685891
STATEMENT:  comm_unique_visitor_main_source_device

WARNING:  relcache reference leak: relation "comm_unique_visitor_main_source_device_mrel" not closed
ERROR:  unexpected chunk number 0 (expected 1) for toast value 331303021 in pg_toast_307803075
STATEMENT:  comm_unique_visitor_main_page_area
WARNING:  relcache reference leak: relation "comm_unique_visitor_main_page_area_mrel" not closed
ERROR:  unexpected chunk number 0 (expected 1) for toast value 331301902 in pg_toast_685891
STATEMENT:  comm_unique_visitor_main_source_device
WARNING:  relcache reference leak: relation "comm_unique_visitor_main_source_device_mrel" not closed

This problem about `cv_mrel_arrival_timestamp_idx`? 
If i REINDEX TABLE pg_toast_307803075; IS OK.
what happen in this error？

sometimes CV_mrel tables is very very very big.  I select cv have 200000 rows,but table size is 30GB.I execute vacuum cv_mrel,error log is like this.

**Comment by usmanm** [comment]
What query were you executing?

**Comment by derekjn** [comment]
Closing for now, will reopen if more information is provided.
