### ISSUE TITLE
Remove STREAM objects

### ISSUE THREAD

**Issue by derekjn** [pipelinedb/pipelinedb#1701]
They're already foreign tables internally, so we essentially just need to remove `STREAM` syntax and rework some metadata management.

- [x] Remove `CreateStmt->stream`
- [x] `RELKIND_STREAM`
- [x] Migrate stream planning logic to planner hooks
- [x] dump/restore
- [x] `OCLASS_STREAM`
- [x] `OBJECT_STREAM`

**Comment by derekjn** [comment]
Currently the foreign server used by `stream_fdw` is called `pipeline_streams`. So to create a stream, you'd now do:

    CREATE FOREIGN TABLE stream (x integer, y integer) SERVER pipeline_streams;

@usmanm any thoughts on what to name the foreign server to make this as intuitive as possible? Something like,

    CREATE FOREIGN TABLE stream (x integer, y integer) SERVER pipelinedb;
    CREATE FOREIGN TABLE stream (x integer, y integer) SERVER streams;
    CREATE FOREIGN TABLE stream (x integer, y integer) SERVER firehose;

**Comment by usmanm** [comment]
I'm thinking just pipeline? We can all the extension pipeline as well. And
then use the namespace pipeline for things like pipeline.streams,
pipeline.views etc. Fit well with the names other extensions like
pipeline_kafka.

**Comment by derekjn** [comment]
If we're going to do that, I kind of actually like the full `pipelinedb`. I don't feel that just `pipeline` is descriptive enough when there isn't a suffix. Naming the extension `pipelinedb` is congruent with all current nomenclature, docs, etc., and then using the extension name as the foreign server name seems very intuitive:

    CREATE FOREIGN TABLE stream (x integer, y integer) SERVER pipelinedb;

**Comment by usmanm** [comment]
In that case we should rename all other extensions to be `pipelinedb_xxx` as well. I think `db` is a little superfluous since now we're going to be an extension to a database, so having db at the end doesn't convey much.

**Comment by derekjn** [comment]
We can leave in the syntax until 1.0.0 (when we'll remove all custom syntax at once), but after this rework we should basically be rewriting to a standard `CREATE FOREIGN TABLE` statement.
