### ISSUE TITLE
CREATE AGGREGATE (combinfunc=...) -> function call

### ISSUE THREAD

**Issue by derekjn** [pipelinedb/pipelinedb#1705]
SELECT create_combiner(aggregate, combinefunc := cf, transout := ..);

**Comment by usmanm** [comment]
Postgres 9.6 actually supports passing in a `combinefunc` to `CREATE AGGREGATE`

https://www.postgresql.org/docs/current/static/sql-createaggregate.html

**Comment by derekjn** [comment]
This will also involve removing `OCLASS_COMBINE`.
