### ISSUE TITLE
Remove all CQ state additions to PG objects

### ISSUE THREAD

**Issue by derekjn** [pipelinedb/pipelinedb#1706]
If we need to attach state to objects, we can probably rework things to use some kind of process-local cache with the object's address as the key:

    object_cache_get(object_ptr, "some_addtional_field");

- [ ] `EState->es_continuous`
- [ ] `ParseState->p_cont_view_context`
- [ ] `ParseState->p_no_locking`
- [ ] `ParseState->p_ins_cols`
- [ ] `PlannedStmt->isContinuous`
- [ ] `Query->isContinuous`
- [ ] `Query->cqId`
- [ ] `Query->isCombine`
- [ ] `Query->isCombineLookup`
- [ ] `Query->swStepFactor`

**Comment by usmanm** [comment]
We can maybe use embedded structures?

```
typedef struct ContQuery
{
  Query query
  additional_field1 int
 ...
} ContQuery
```

**Comment by sangli00** [comment]
What time release  PipelineDB extension ,very expect.

**Comment by derekjn** [comment]
@sangli00 probably in the second quarter of this year.

**Comment by derekjn** [comment]
Split into individual issues.
