### ISSUE TITLE
Rip out pipeline_tstate catalog

### ISSUE THREAD

**Issue by derekjn** [pipelinedb/pipelinedb#1708]
Continuous `SELECT DISTINCT` is not really used, so we should remove the additional dependency and catalog metadata that supports it. And if we really need this down the road, we can probably do it more cleanly by rewriting the query and putting an overlay on the mrel.

Users should also be able to accomplish what they want here fairly easily with some combination of CV/CT/output stream.

**Comment by usmanm** [comment]
Or we can just store the query state inside `pipeline_query` catalog. Unsure how the overlay on matrel would work.

**Comment by derekjn** [comment]
```
CREATE CONTINUOUS VIEW v AS SELECT DISTINCT x, y z FROM s
```

Worker/combiner query:

```
SELECT x, y z FROM s GROUP BY x, y, z
```

**Comment by usmanm** [comment]
We should also make the combiner never try to *update* a tuple in a `SELECT DISTINCT` query.
