### ISSUE TITLE
Add the ability to alter the ttl and ttl_column storage params

### ISSUE THREAD

**Issue by EliSnow** [pipelinedb/pipelinedb#1715]
It could be useful to change, remove, and add `ttl` and `ttl_column` storage params to existing `CONTINUOUS VIEW`s without creating new ones and copying over data.

**Comment by usmanm** [comment]
Changing the `ttl` value should be pretty simple, but changing the column or adding/removing `ttl` might be tricky.

**Comment by derekjn** [comment]
@EliSnow the best way to do this would be via `ALTER`:

    ALTER CONTINUOUS VIEW v SET ttl = '1 hour', ttl_column = 'column';

However, because of #1596 we're pulling out all PipelineDB syntax so we'd prefer not to add any in the meantime. For now, we can wrap this in a function call:

    SELECT set_ttl('cv_name', '1 hour', 'column');

Once #1596 lands, we can map that function call back to the DDL interface:

    ALTER MATERIALIZED VIEW SET ttl = '1 hour', ttl_column = 'column';

**Comment by EliSnow** [comment]
@derekjn, you're on a roll today! The function call should be fine.

Just out of curiosity is there any `ALTER CONTINUOUS VIEW` syntax that exists today?

**Comment by derekjn** [comment]
> Just out of curiosity is there any ALTER CONTINUOUS VIEW syntax that exists today?

Nope, only `ALTER STREAM`.

**Comment by derekjn** [comment]
Docs:

http://docs.pipelinedb.com/continuous-views.html#modifying-ttls
