### ISSUE TITLE
Allow constraints to work on CONTINUOUS VIEWS

### ISSUE THREAD

**Issue by EliSnow** [pipelinedb/pipelinedb#1719]
(This is a very low priority feature request, and I'm not sure if it's technically possible with the way Pipeline's workers insert rows into the `_mrel` tables)

Foreign key constraints do not work quite right on CVs (or rather their underlying `_mrel` tables):

```sql
CREATE TABLE foo (
  n integer PRIMARY KEY
);

INSERT INTO foo VALUES (1);

CREATE STREAM s (n integer);

CREATE CONTINUOUS VIEW v AS
SELECT n FROM s;

ALTER TABLE v_mrel ADD CONSTRAINT vfk FOREIGN KEY (n) REFERENCES foo (n) ON DELETE CASCADE;

INSERT INTO s VALUES (1), (2), (3);

SELECT * FROM v;

 n
---
 1
 2
 3
(3 rows)
```

Though a delete on the foreign table will correctly cascade to the `_mrel` table so long as `SET continuous_query_materialization_table_updatable = ON`.

**Comment by derekjn** [comment]
As always, thanks for the thoughtful feedback @EliSnow! This should be fairly straightforward to implement and I do think that it makes sense to support. One bigger issue that comes to mind here is error handling semantics in the combiner. Currently if there's an error while a combiner is syncing a batch of tuples to disk, the entire batch will fail and get dropped, which I don't think is the ideal (or expected) behavior for FK violation errors.

We'll need to add some logic to evaluate the FK constraints at sync time, so perhaps we can just add a level of error handling around that. We'd just log an error and drop offending rows.

**Comment by EliSnow** [comment]
@derekjn, is this the same behavior that currently happens with unique constrain violations? I have been testing out a unique constraint defined on a data archive CV to prevent duplicates from accidentally entering the system. Does this mean on a unique constraint violation an entire batch is lost?

**Comment by derekjn** [comment]
> Does this mean on a unique constraint violation an entire batch is lost?

Yes, CVs are admittedly not really designed for these kinds of user-imposed constraints so they're not handled particularly intelligently.
