### ISSUE TITLE
UTC Timestamp doesnt work

### ISSUE THREAD

**Issue by devsschmidt** [pipelinedb/pipelinedb#1730]
The following continuous view will not contain any data (unless you are already in UTC timezone) since the UTC Parameter doesnt seems to be applied to return value of clock_timestamp(). 

```
CREATE STREAM my_stream(payload JSONB);

CREATE CONTINUOUS VIEW my_count_5_minutes AS 
SELECT COUNT(1) _count
FROM my_stream
WHERE (payload->>'created')::TIMESTAMP> clock_timestamp() AT TIME ZONE 'UTC' - '5  Minutes'::INTERVAL;

```
(Im working in Germany which puts my timezone at +0100 to UTC)
When i add the difference between my timezone and UTC to my interval ('65  Minutes'::INTERVAL)  it works.

What works, but still seems to be a weird solution:
```
CREATE STREAM my_stream(payload JSONB);

CREATE CONTINUOUS VIEW my_count_5_minutes AS 
SELECT COUNT(1) _count
FROM (SELECT payload, (payload->>'created')::TIMESTAMP _created, (clock_timestamp() AT TIME ZONE 'UTC')::TIMESTAMP _utc
            FROM my_stream) AS t 
WHERE _created > _utc - '5  Minutes'::INTERVAL;

```

**Comment by devsschmidt** [comment]
Using the solution keeps all records within the view no matter how much time passes.

**Comment by derekjn** [comment]
@devsschmidt for the first CV, can you provide some example `INSERT` statements that reproduce the issue?

**Comment by derekjn** [comment]
@devsschmidt it's hard to be helpful without having some actual `payload` examples to get a complete picture of what's going on here. I don't think there's a bug anywhere, but we're always happy to point users in the right direction and help however we can, so if you'd like to add some `payload` examples we'll revisit this.

**Comment by devsschmidt** [comment]
sorry, had been on Christmas vacation and didnt realize you need more information. i'll compile a full script to show the issue more precise.
