### ISSUE TITLE
Refactor combine analyzer/planner

### ISSUE THREAD

**Issue by derekjn** [pipelinedb/pipelinedb#1732]
It's gotten fairly complex and is do for a rewrite, ideally a significant simplification. We may want to do something like just make `combine` an actual aggregate that just accepts any arguments, and handle everything else at aggregate startup time. All it really needs to do is choose the correct transition functions, apply `combinein`/`transout` functions, etc.

- [ ] Standardize `ParseCombineFuncCall`
- [ ] Remove `OCLASS_COMBINE`

All `combine` infra should be completely standardized after this rework.

**Comment by usmanm** [comment]
Can we deterministically figure out the merge function at aggregate start up? Two different aggregates could have the same `transtype` in which case I'm not sure if we can do anything.

**Comment by derekjn** [comment]
Current all we use to build the `combine` `Aggref` are:

* Target column/relation, which we get from the `Aggref's` TL
* CV id, which we get from the matrel

So I believe we should be able to generate a `combine` call fairly easily. The problem may lie with the fact that currently for `combines` we create an actual `Aggref` node, so it may be too late to do anything with an `Aggref` that is essentially already executing.

**Comment by derekjn** [comment]
Remove special `combine` handling in `ParseFuncOrColumn`.
