### ISSUE TITLE
Deadlock while INSERTing lots of data

### ISSUE THREAD

**Issue by hedayat** [pipelinedb/pipelinedb#1738]
I have a CV with (step_factor = 1, sw = '30 mins'). I use it's output stream in a transform to feed another stream. CVs can be created over the latter, but this problems even occurs when there are no CVs on the latter stream.
I do lots of INSERTs each one have 500 rows. Having this load for awhile, e.g. 30 minutes, pipelinedb keeps up with my INSERTs, then it starts to lag behind for a few minutes, and suddenly one of my INSERTs block. Nothing happens anymore, no new data is inserted and CPU usages drop considerably. 

I created another view with larger sw to see if it has any different behavior, but it doesn't. When blocked, I tried to DROP this second view but it becomes 'waiting'. So, effectively something is locked forever.

**Comment by derekjn** [comment]
Hi @hedayat, this is most likely happening as a result of an issue that has been fixed for the next release:

https://github.com/pipelinedb/pipelinedb/issues/1714

Can you verify that this doesn't happen for you if you use the nightly release?

**Comment by derekjn** [comment]
Will reopen this is it is reproducible on `master`

**Comment by hedayat** [comment]
Please reopen. tried with a nightly release but it happened again (using PREPARE/EXECUTE actually rather than INSERT) inserting 100 rows in each statement. 

In previous version I tried both using EXECUTE and INSERT and in both cases deadlock happened. This time I've used EXECUTE but not tried INSERT, but I guess that will happen too.

**Comment by hedayat** [comment]
Still investigating. Since then, it has happened only once (while it happened regularly with the previous version). I think it is much better now, but probably there is still some corner cases...

**Comment by derekjn** [comment]
> Please reopen. tried with a nightly release but it happened again (using PREPARE/EXECUTE actually rather than INSERT) inserting 100 rows in each statement.

We're more than happy to reopen if you can attach repro steps here. Otherwise there isn't much we can do.

**Comment by hedayat** [comment]
I'm going to provide that, but it's slightly complicated (and might need some permissions too).  I'll try to provide you with more info but it'll take some time to provide something usable by you and as simple as possible.

**Comment by derekjn** [comment]
> I'm going to provide that, but it's slightly complicated (and might need some permissions too).

You also might want to try simplifying things down as much as possible without sharing the DDL verbatim.
