### ISSUE TITLE
Kafka extension function pipeline_kafka.add_broker() always returns success

### ISSUE THREAD

**Issue by sfkeller** [pipelinedb/pipelinedb#1746]
By using the Kafka Extension the function “pipeline_kafka.add_broker ( hostname text )” always returns ’success’ in ANY case. Thus, the PipelineDB user assumes everything went well – which may be not the case at all. It seems that the input string (hostname) is not validated at all (no URL/URN pattern checking ...).

**Comment by derekjn** [comment]
Hi @sfkeller, do you mind moving this over to https://github.com/pipelinedb/pipeline_kafka/issues?

**Comment by sfkeller** [comment]
No; but I think there's no "move" function - except https://github-issue-mover.appspot.com/ . Should I close it here and re-open over there?

**Comment by derekjn** [comment]
Yea, I just meant close it here and copy/paste it to the `pipeline_kafka` repo :) Thanks!

**Comment by sfkeller** [comment]
Moved over to here https://github.com/pipelinedb/pipeline_kafka/issues/62
