### ISSUE TITLE
TTL - set_ttl function not found

### ISSUE THREAD

**Issue by brettlaforge** [pipelinedb/pipelinedb#1747]
An error occurs when attempting to use the set_ttl function in the latest 0.9.6

```
pipeline=# SELECT set_ttl('day_detail', '1 month', 'ts');
ERROR:  function set_ttl(unknown, unknown, unknown) does not exist
LINE 1: SELECT set_ttl('day_detail', '1 month', 'ts');
               ^
HINT:  No function matches the given name and argument types. You might need to add explicit type casts.
```

Pipeline Version:
```
PipelineDB 0.9.6 at revision 72b0c7fb25c2361399e17fde7eaf013b5f0dd7de on x86_64-pc-linux-gnu, compiled by gcc (Ubuntu 5.4.0-6ubuntu1~16.04.4) 5.4.0 20160609, 64-bit
```

I was wondering if this is a valid workaround?
```
UPDATE pipeline_query SET ttl = EXTRACT(epoch from interval '25 days') WHERE relid = (SELECT relfilenode FROM pg_class WHERE relname= 'day_detail');
```

**Comment by derekjn** [comment]
His @brettlaforge, this functionality is actually not available in 0.9.6. It's available in the nightly release and will of course be available in 0.9.7, which will be released imminently.

And your workaround is almost complete but not quite there. Here's the query template that `set_ttl` ultimately uses:

https://github.com/pipelinedb/pipelinedb/blob/master/src/backend/utils/adt/pipelinefuncs.c#L993

Please do this at your own risk though :)
