### ISSUE TITLE
Server not starting while enabling continuous triggers

### ISSUE THREAD

**Issue by eric-bunch** [pipelinedb/pipelinedb#1750]
Hello,

I am trying to use continuous triggers, without success. I have modified my `pipelinedb.conf` file to include 

```
continuous_triggers_enabled = on
wal_level = logical
max_wal_senders = 1
max_replication_slots = 1
```

But after I restart the server, I am not able to access Postgres--I get the message

```
psql: could not connect to server: No such file or directory
	Is the server running locally and accepting
	connections on Unix domain socket "/tmp/.s.PGSQL.5432"?
```

and the log file shows this

```
LOG:  unrecognized configuration parameter "continuous_triggers_enabled" in file "/home/ubuntu/pipelinedb_datadir/pipelinedb.conf" line 665
FATAL:  configuration file "/home/ubuntu/pipelinedb_datadir/pipelinedb.conf" contains errors
```

If I comment out the lines in the `pipelinedb.conf` file, and restart the server, it works fine.

I am running Ubuntu 16.04.2 LTS, the output of `select pipeline_version();` is 

```
PipelineDB 0.9.6 at revision 72b0c7fb25c2361399e17fde7eaf013b5f0dd7de on x86_64-pc-linux-gnu, compiled by
 gcc (Ubuntu 5.4.0-6ubuntu1~16.04.4) 5.4.0 20160609, 64-bit
```

and the output of `select version();` is

```
PostgreSQL 9.5.3 on x86_64-pc-linux-gnu, compiled by gcc (Ubuntu 5.4.0-6ubuntu1~16.04.4) 5.4.0 20160609, 
64-bit
```

Let me know if there is any more information you want from me, or if I missed a step in the setup.

**Comment by derekjn** [comment]
Hi @eric-bunch, the concept of continuous triggers was removed in `0.9.6` in favor of achieving the same functionality with continuous transforms on output streams. See the [release notes](https://www.pipelinedb.com/blog/pipelinedb-0-9-6) for more information. Please let us know if you need help using these abstractions.

**Comment by eric-bunch** [comment]
Ah, I see. Thanks for the info. I'll check that out to see what I can use.
