### ISSUE TITLE
PipelineDB <-> PostgreSQL interface

### ISSUE THREAD

**Issue by derekjn** [pipelinedb/pipelinedb#1774]
All of the internal refactoring work for #1596 is fairly straightforward and well defined. The most important thing in my mind that needs to be figured out is what exactly we want the PipelineDB <-> PostgreSQL interface to look and feel like at a high level. That is, how do users interact with PipelineDB's abstractions now that we're going to only be using PostgreSQL's interface/syntax?

I see a few different approaches we can take here. In no particular order,

## 0) Keep PipelineDB syntax

Continuous views, transforms, and streams are fairly unique and simply do not map very directly to any existing PG objects. So it's nice to have a small bit of syntax to represent these objects, and helps new users become familiar with PipelineDB's abstractions. It also makes documentation more distinctive and precise.

However, PG does not support syntax extension so this approach would require working around that. Fundamentally we'd probably need a very thin shim process in front of PostgreSQL that detects and handles PipelineDB DDL statements.

If it's a `CREATE CONTINUOUS VIEW`, `CREATE CONTINUOUS TRANSFORM`, or `CREATE STREAM`, statement, we'd transpile the query into a valid PG query using function calls. Otherwise, the statement would just be quickly passed off to PG.

Obviously this isn't ideal, but I do see quite a bit of value in keeping our syntax for our primitives. This approach would also incur minimal migration friction.

## 1) Map PipelineDB objects to PostgreSQL objects

Streams are already foreign tables internally, so if we simply removed `CREATE STREAM` syntax and required that streams be created with the foreign table interface, we'd be able to to detect when queries are reading from a stream. That would allow us to leverage existing syntax to create continuous views and transforms.

For example, you could create a stream like so:

```sql
CREATE FOREIGN TABLE stream (x integer) SERVER pipelinedb_stream;
```

And perhaps use `CREATE MATERIALIZED VIEW` syntax to create a continuous view: 

```sql
CREATE MATERIALIZED VIEW continuous_view AS SELECT count(*) FROM stream;
```

So we'd just detect the stream in the `FROM` clause, and create a continuous view accordingly. Similarly, for transforms we could use a `VIEW` over a stream:

```sql
CREATE VIEW continuous_transform AS SELECT transform(x) FROM stream;
```

These objects map relatively intuitively to PipelineDB objects. The downside is that their behavior is quite a bit different: The "materialized view" in this case would be automatically updating, whereas actual materialized views are updated via `REFRESH`. And the "view" would be writing rows out to another stream (its output stream), which is kind of weird for a view.

## 2) Use functions for everything

We could just encapsulate all PipelineDB DDL functionality in function calls. This is what **approach 0)** would do internally. For example,

```sql
-- CREATE STREAM
SELECT pipelinedb.create_stream('stream_name', '(x integer, y integer)');

-- CREATE CONTINUOUS VIEW
SELECT pipelinedb.create_continuous_view('cv_name',
  'SELECT x, count(*) FROM stream GROUP BY x');

-- CREATE CONTINUOUS TRANSFORM
SELECT pipelinedb.create_continuous_transform('xform_name',
  'SELECT transform(x) FROM stream');
```

This is probably the most straightforward approach, but does feel a bit lacking. It feels weird to be writing SQL within strings, rather than being able to leverage things like syntax highlighting.

--------

There may be fundamentally better approaches, or perhaps the best one is some combination of the above. We'd love to get some user feedback here and have a discussion about what the best design looks like. Getting this interface just right as we become an extension is the most important part of the remaining work.

**Comment by eeeebbbbrrrr** [comment]
I'm not a @pipelinedb user, so take this with a grain of salt, but what about implementing a custom language handler so you could maintain your declarative syntax?

Maybe you'd be able to allow things like:

```sql
DO LALNGUAGE pipeline $$
    CREATE CONTINUOUS VIEW ... ;
    CREATE STREAM ... ;
$$;
```

I have an extension called @zombodb, and I've thought about doing something like this for it, but haven't completely talked myself into it -- ZomboDB is an Access Method, so it ties in a little easier with standard Postgres SQL (and its parser) than I guess PipelineDB does.

**Comment by solidsnack** [comment]
I have some questions about (1):

* Would a continuous transform still be able to function as a `VIEW`, even if this is not a desirable or normal way to use it?

* Views have `WITH (...)` to provide additional options, which might allow things like `CREATE VIEW ... WITH (refresh = '100ms')` and `CREATE VIEW ... WITH (output = 'stream')`. Is it possible to extend these options with an extension?

**Comment by jberkus** [comment]
I don't have a good solution to this problem; it's why I never suggested an extension in the past.  

I don't see a better way forwards than the function interface unless someone were to implement syntax extensions as a core postgresql feature for extensions, and that would be a multi-release effort. 

Rather than "a thin shim", I might suggest that you create a fork of psql which would support the pipelinedb syntax and its transformation to functions.

**Comment by derekjn** [comment]
@solidsnack 

> Would a continuous transform still be able to function as a VIEW, even if this is not a desirable or normal way to use it?

I think we'd just throw an error if a user tried to `SELECT` from a transform

> Views have WITH (...) to provide additional options, which might allow things like CREATE VIEW ... WITH (refresh = '100ms') and CREATE VIEW ... WITH (output = 'stream'). Is it possible to extend these options with an extension?

Yes, `WITH` options are easy to parse and handle from the extension interface.

**Comment by derekjn** [comment]
@jberkus If there aren't fundamental PG design reasons for not supporting syntax/parse-time hooks, we would be more than happy to put that work into upstream PG. I've been under the impression that such support has never been added because it has been excluded as an explicit design decision.

But if you think upstream would be receptive to merging in this support, we'd be perfectly happy to begin working on it immediately.

**Comment by mbulgakov17** [comment]
@derekjn I'm not a PipelineDB user yet (currently evaluating it), but I hope you are able to go the syntax/parse-time hooks route.

**Comment by jberkus** [comment]
Derek: there are, indeed, some substantial both technical and community blockers to be resolved for any such change.  Aside from the issues with the parser, there's the question of various extensions conflicting with each other and with user-created objects.

**Comment by anarazel** [comment]
We went through a similar discussion in the Citus team when working on converting it to an extension (via the function route).  There's one more option that I think has some benefits, namely using storage options. You can e.g. do something like

```
CREATE TABLE ...(...) WITH (pipelinedb.type = 'continuous_stream', pipelinedb.whatnot = 'somethingelse')
```

requires some hooks to make it work, but you'll have more than a few of those anyway...

**Comment by derekjn** [comment]
> Derek: there are, indeed, some substantial both technical and community blockers to be resolved for any such change.

@jberkus that's what I had thought. I actually think it makes a lot of sense for PG to never support syntax extension. From PG's perspective, there is a certain kind of impurity that would create and it has always maintained its focus on the SQL standard anyways. From our perspective, there is a certain kind of impurity in using function calls but that is a *much* lesser concern.

I actually like the idea of just using our own client for DDL statements where users prefer to keep using PipelineDB-specific syntax, and just do everything internally with function calls. Most users already use the `pipeline` client anyways, so we could just keep the same name and most users wouldn't feel any difference at all when using the extension.

And we're only talking about 3 statements here (`CREATE CONTINUOUS VIEW/TRANSFORM` and `CREATE STREAM`), so I feel like this is a reasonable price to pay.

**Comment by EliSnow** [comment]
Building off @jberkus' suggestions, I would like to see pieces of Pipeline make it upstream. `CONTINUOUS VIEW`s could perhaps turn into the missing feature of incrementally updating `MATERIALIZED VIEW`s. Additionally Pipeline's extra data types and aggregate functions would be very useful upstream. With all the work being done on parallelizing PostgreSQL, Pipeline's once unique concept of combine functions is now in vanilla PostgreSQL.

**Comment by davidfetter** [comment]
If your investors allow, it should be possible to refactor the bits of pipelinedb that make sense to and get them into PostgreSQL.  Are there parts that don't?

**Comment by EliSnow** [comment]
Benefits of getting pieces into PostgreSQL include having a lot more eyes on the code, more people to help maintain the code and build off of it, and more people consuming and testing those pieces.

One downside, or at least something to be conscience of, is that user facing features of PostgreSQL have to remain stable. That's why I think it would be a good idea to start with getting Pipeline's data types and aggregate functions upstream. Those are pretty stable and would provide tremendous benefit to PostgreSQL.

**Comment by davidfetter** [comment]
Do you have a list?  Patches for the next commitfest?

**Comment by derekjn** [comment]
> If your investors allow, it should be possible to refactor the bits of pipelinedb that make sense to and get them into PostgreSQL. Are there parts that don't make sense to put into PostgreSQL? If so, which?

Hey @davidfetter !

In general I don't think it makes sense for anyone to spend time on rushing anything into upstream before we're done with the extension refactor. A lot of things are in flux right now, and you'd end up with a lot of structure and functionality that will have likely diverged from the end result of the refactor by the time we're done.

If we planned on keeping PipelineDB forked, I think it would make sense to merge in some of our functionality if people wanted it upstream. But since we're going to be an extension in the relatively near future, I don't see much of a benefit to moving PipelineDB functionality into PG. It would likely end up behind our own maintenance cycles anyways, which would basically result in another fork.

There are also a number of sticky issues, such as the fact that we only target 64-bit Linux OSs, license incompatibilities, functionality that depends on the broader internal PipelineDB catalog infrastructure, etc.

The whole idea of unforking into an extension is to make PipelineDB as accessible as possible to vanilla PG users, so I sort of feel that merging anything into upstream is just an unnecessarily complicated and less effective way of accomplishing that. And if anything, it will be much cleaner and easier to cherry pick things in to upstream from PipelineDB once it's an extension.

But doing so before then is just very low benefit, complicated, and would take time away from progress on the extension refactor, which is what the vast majority of our users are eagerly awaiting :smiley: 

> Are there parts that don't make sense to put into PostgreSQL? If so, which?

The only parts I could realistically see ending up in upstream are some of the probabilistic aggregates and their associated functions, but even that's debatable. The core, continuous query engine is basically a completely separate beast that will never belong in upstream PG.

----

Fundamentally I'm very much of the opinion that PipelineDB is exactly what the PG extension interface was made for, and feel that keeping them separate is a win for everybody, as we can keep our focus as narrow as possible. PG is generic and lean, and extensions add specialization where it's needed.

It is true that a very large percentage of PipelineDB users use PostgreSQL, but it's also important to realize that only a relatively small percentage of PostgreSQL users use PipelineDB. And for that reason, I think they belong separate from one another, certainly before we're done with the extension refactor :wink:

**Comment by davidfetter** [comment]
Licensing is completely under the control of the copyright holders, which is why I named investors as an interested party.  Anything that goes into community PostgreSQL needs to be licensed compatibly with the Postgres license, approximately the MIT license.

As to whether community PostgreSQL will ever have a streaming capability, the question is not whether, but when.  It could be as soon as 11, with your help.

**Comment by derekjn** [comment]
> As to whether community PostgreSQL will ever have a streaming capability, the question is not whether, but when.

We would definitely love to help lead the way there! Personally I'm still not sure that the PipelineDB engine would be relevant to a general-purpose streaming capability in PG, as it's highly optimized for a fairly specific set of use cases and semantics but I suppose we can cross that bridge when we get to it :)

Are there any preliminary design docs/brainstorms being worked on yet? All I can find online regarding streaming queries on PostgreSQL is... :smiley:

**Comment by jberkus** [comment]
There has been no public work on streaming core Postgres since TelegraphCQ went proprietary, AFAIK.

And not everything needs to be a core Postgres feature.  If anything, the extensions interfaces are possibly PostgreSQL's "killer feature".

**Comment by davidfetter** [comment]
Extensions certainly are a killer feature of PostgreSQL.

As I see it, streaming can come in a couple of main ways.  I'll list the most natural ones first:

- Grammar and possibly wire protocol changes to the core make the whole thing play nicely with SQL
- Grammar and possibly wire protocol changes implemented via extension APIs yet to be defined and with no certainty they'll be available in the next five years.
- Various UDFs that relegate it to second class status and have much less natural access to planner/executor machinery

As you can probably tell, I see the first as the one that fits best.  The last is probably the quickest, and could be a stepping stone, but people won't be wild about adopting it precisely because it couldn't feel natural. The middle one basically depends on sky (or at any rate, parser and wire protocol) hooks and fairy dust, even though superficially it resembles the first.

**Comment by jberkus** [comment]
David,

Neither the first nor the second option seem realistic on any reasonable timeline; consider that you're discussing a feature here for which there are no industry standards to consult.  And given that all of our syntax is backed by functions anyway, implementing a function interface doesn't in any way prevent someone from incorporating it into additional syntax someday when that might become more reasonable.

**Comment by derekjn** [comment]
@jberkus @davidfetter what do you guys think about the feasibility of adding ` AS <query>` support to `CREATE FOREIGN TABLE`?. If PG supported this, we'd have everything we'd need for streams, continuous views, and continuous transforms:

```sql
-- Stream
CREATE FOREIGN TABLE stream (x integer, y integer)
SERVER pipelinedb
OPTIONS (type 'stream');

-- Continuous view
CREATE FOREIGN TABLE cv_name AS  
  SELECT x, y, count(*) FROM stream GROUP BY x, y
SERVER pipelinedb
OPTIONS (type 'view')

-- Continuous transform
CREATE FOREIGN TABLE transform_name AS  
  SELECT x + 1 AS y FROM stream
SERVER pipelinedb
OPTIONS (type 'transform')
```

By default, the rows returned by `<query>` would be passed to the corresponding FDW's `INSERT` handler, obviously failing if one wasn't defined. It seems like this is generally useful, at least to the extent that `CREATE TABLE AS` is.

We're going with function calls for the time being, but this strikes me as a potentially interesting approach that would be generally useful to PG as well.

**Comment by jberkus** [comment]
Derek: seems hard, but yeah, generally useful.  Wanna float the idea on -hackers?

**Comment by jberkus** [comment]
BTW, might end up being "CREATE FOREIGN VIEW"

**Comment by derekjn** [comment]
> Derek: seems hard, but yeah, generally useful. Wanna float the idea on -hackers?

@jberkus sure, just wanted to get a sanity check from you guys first. I'll think through it in more detail and follow up with you.

**Comment by davidfetter** [comment]
Yeah, the function thing seems neat.  It also occurs to me that CURSOR might be a way to get something from a continuous stream once it's set up.

**Comment by postgresmith** [comment]
I am a PostgreSQL developer. When I saw your PipelineDB , I was thinking that the DB's features were so exciting.Earlier this year, I heard that you guys are going to release your features as a extension. So, I always pay attention to your blog. In August 17 this year, I see your 《PipelineDB 0.9.8 - PostgreSQL Extension Refactor Nearing Completion》. So I want to know your plan about making PipelineDB a standard PostgreSQL extension.
I really really really  want to test and study this extension. Could you tell me that? I will feel very honored.
Looking forward to your reply.

**Comment by esatterwhite** [comment]
Is there still an effort on this? it seems the progress has halted

**Comment by derekjn** [comment]
> Is there still an effort on this? it seems the progress has halted

@esatterwhite Yes, absolutely! The extension release is in a completely separate, private repo. This repo will be updated with the extension code as soon as it's complete. It's very close to finished and we're currently wrapping up packaging, stress testing, etc. You can expect the extension to be released within weeks, definitely not months.

**Comment by davidfetter** [comment]
Why did you do that? Is there some proprietary thing you're developing alongside, or was there, and no more, or...?

**Comment by janantos** [comment]
HI,
any movement here? when we can expect v1.0 pgsql extension. Can't wait for it. can you please make some communication, as it seems you are silent for months, can you please provide some milestone delivery ETA?

**Comment by derekjn** [comment]
@janantos PipelineDB `1.0.0` is slated to go out next week! The extension codebase is currently in a separate repository, which is why you haven't seen the commits landing here.

**Comment by ercengsha** [comment]
Hi, we are Extreme hopes v1.0 pgsql extension.
Whether the new version of pipelinedb(v1.0) handled the problem of postgresql compatibility in the original expected solution, such as "Map pipelinedb objects to postgresql objects", "Use functions for everything", etc. 
When it comes to the sequential database, it is the extension of postgresql, so we have to think of pipelinedb and timescaledb. #1876 
We would like to know the developer's new opinion on the combination of the two, especially when pipelinedb becomes a postgresql extension.

**Comment by derekjn** [comment]
The extension rework has just landed in `master`, so I just wanted to close the loop here on how the high-level interface has changed. We're pretty happy with what we ended up with, as we've mostly been able to use existing PostgreSQL primitives to create PipelineDB objects:

**Streams**

Streams are foreign tables:

```sql
CREATE FOREIGN TABLE stream (x integer) SERVER pipelinedb;
```

**Continuous views**

Continuous views are just regular views with an `action` parameter specified:

```sql
CREATE VIEW continuous_view WITH (action=materialize) AS
  SELECT x, count(*) FROM stream
GROUP BY x;
```

The default `action` is `materialize`, so it can be omitted when defining continuous views:

```sql
CREATE VIEW continuous_view AS
  SELECT x, count(*) FROM stream
GROUP BY x;
```

**Continuous transforms**

Continuous transforms are also just views with an `action` of `transform`:

```sql
CREATE VIEW transform WITH (action=transform) AS
  SELECT x + 1 FROM stream;
```

Transform output functions are specified via the `outputfunc` parameter:

```sql
CREATE VIEW transform WITH (action=transform, outputfunc=pipelinedb.insert_into_stream('s')) AS
  SELECT x + 1 FROM stream;
```

---

PipelineDB `1.0.0` extension binaries will be published tomorrow morning, and please note that docs and related resources are currently in the process of being updated to reflect the new interface. Thank you all so much for you invaluable input here and most of all, your patience!

Enjoy `1.0.0` :)

**Comment by esatterwhite** [comment]
is it possible or can it be possible to have a stream write to a table?
I suppose that could be done from a transform with a function, maybe?

**Comment by derekjn** [comment]
> is it possible or can it be possible to have a stream write to a table?
I suppose that could be done from a transform with a function, maybe?

@esatterwhite exactly, you'd just use a transform with an `outputfunc` that runs `INSERTs` into your target table.

**Comment by JasonkayZK** [comment]
> The extension rework has just landed in `master`, so I just wanted to close the loop here on how the high-level interface has changed. We're pretty happy with what we ended up with, as we've mostly been able to use existing PostgreSQL primitives to create PipelineDB objects:
> 
> **Streams**
> 
> Streams are foreign tables:
> 
> ```sql
> CREATE FOREIGN TABLE stream (x integer) SERVER pipelinedb;
> ```
> 
> **Continuous views**
> 
> Continuous views are just regular views with an `action` parameter set to `materialize`:
> 
> ```sql
> CREATE VIEW continuous_view WITH (action=materialize) AS
>   SELECT x, count(*) FROM stream
> GROUP BY x;
> ```
> 
> The default `action` is `materialize`, so it can be omitted when defining continuous views:
> 
> ```sql
> CREATE VIEW continuous_view AS
>   SELECT x, count(*) FROM stream
> GROUP BY x;
> ```
> 
> **Continuous transforms**
> 
> Continuous transforms are also just views with an `action` of `transform`:
> 
> ```sql
> CREATE VIEW transform WITH (action=transform) AS
>   SELECT x + 1 FROM stream;
> ```
> 
> Transform output functions are specified via the `outputfunc` parameter:
> 
> ```sql
> CREATE VIEW transform WITH (action=transform, outputfunc=pipelinedb.insert_into_stream('s')) AS
>   SELECT x + 1 FROM stream;
> ```
> 
> PipelineDB `1.0.0` extension binaries will be published tomorrow morning, and please note that docs and related resources are currently in the process of being updated to reflect the new interface. Thank you all so much for you invaluable input here and most of all, your patience!
> 
> Enjoy `1.0.0` :)

Thanks! 
It works for me!
