### ISSUE TITLE
Upstream merge

### ISSUE THREAD

**Issue by derekjn** [pipelinedb/pipelinedb#1778]
The introduction of combine functions in PG 9.6 will simplify a lot of things for #1596, and will probably make it possible to remove all changes we've made to `nodeAgg`.

**Comment by usmanm** [comment]
This probably isn't valid anymore? We can just start right off by supporting only PG 9.6+.

**Comment by derekjn** [comment]
https://www.pipelinedb.com/blog/pipelinedb-1-0-0-high-performance-time-series-aggregation-for-postgresql
