### ISSUE TITLE
Can add windows OS support?

### ISSUE THREAD

**Issue by runner-mei** [pipelinedb/pipelinedb#1794]
Can add windows OS support?
I need run it on win2012

**Comment by derekjn** [comment]
Hi @runner-mei, there hasn't been much demand for Windows support so we probably won't be spending much time on Windows compatibility. Are you trying to run PipelineDB on a development machine? If so, using a VM would probably be your best option. And I'm not familiar with the state of Docker's support for Windows, but that may be another option.
