### ISSUE TITLE
Download link to 0.9.6 is redirect to 0.9.7

### ISSUE THREAD

**Issue by agentgt** [pipelinedb/pipelinedb#1799]
The download page here: https://www.pipelinedb.com/download

Has a previous version download link: https://www.pipelinedb.com/download/0.9.6/ubuntu14

.... which will always download the latest.

Which begs the question where can I still get 0.9.6 and is there a reliable link for previous versions?

**Comment by derekjn** [comment]
@agentgt https://github.com/pipelinedb/pipelinedb/releases

**Comment by derekjn** [comment]
@agentgt archive links are fixed now, thank you for reporting. And the GH releases is probably a good option for you guys, as we will never delete binaries from there.
