### ISSUE TITLE
Output Streams on Sliding Window Views don't emit new values

### ISSUE THREAD

**Issue by tschie** [pipelinedb/pipelinedb#1804]
I'm trying to implement generating alerts when a new value in a sliding window crosses above a threshold. Here is my idea:
```sql
CREATE TABLE alerts (q numeric);
CREATE FUNCTION alert() RETURNS TRIGGER AS $$ BEGIN
  INSERT INTO alerts (q) VALUES (NEW.q); RETURN NEW;
END; $$ LANGUAGE plpgsql;

CREATE CONTINUOUS STREAM s (q numeric);
CREATE CONTINUOUS VIEW v WITH (sw = '1 day') AS SELECT q FROM s;
CREATE CONTINUOUS TRANSFORM t AS SELECT (new).q FROM output_of('v') WHERE (new).q > 5 AND ( (old).q < 5 OR (old).q IS NULL) THEN EXECUTE PROCEDURE alert();

INSERT INTO s VALUES (4.0), (6.0);
```

I expect `alert()` to be called once and to see one record `6.0` in alerts. But when I do this, I don't see any alerts. However, if I remove `WITH (sw = '1 day')`, it works as expected. So it seems that output streams on sliding window views don't emit new values. I suppose maybe that's what this is trying to say: http://docs.pipelinedb.com/streams.html#output-streams-on-sliding-windows? Either way, is there some workaround to do this with sliding windows?

Copied from gitter. I also tried with a sliding window of 10 seconds. Same result. Used docker container with 0.9.7.

**Comment by derekjn** [comment]
@tschie so the problem here is that your continuous view that the transform is reading from isn't doing any aggregation, so no updates are going to be happening, and therefore you will never have an `old` tuple.

`old` and `new` in this context refer to the tuple before and after an incremental aggregation update to the continuous view.

Your continuous view will simply keep appending all values written to `s`.

**Comment by tschie** [comment]
@derekjn I see that if I change the view to 
```sql
CREATE CONTINUOUS VIEW v WITH (sw = '1 day') AS SELECT keyed_max(arrival_timestamp, q) AS q FROM s;
```
then I get alerts as you say. However, I still wonder why removing `WITH (sw = '1 day')`? also seems to work. I'm still not aggregating in that case, right?

For my use case, I do just want a view that keeps track of the last 24 hours of records. Is there some aggregate I can use to achieve the effect of a sliding window while still providing output?

**Comment by derekjn** [comment]
> I'm still not aggregating in that case, right?

You are aggregating with and without a sliding window. Sliding windows are not required for aggregation. The fundamental difference between sliding-window and non-sliding-window aggregations is that sliding-windows will automatically exclude information that is older than the window.

Without a sliding window, nothing is removed from the CV (unless you're using a [TTL](http://docs.pipelinedb.com/continuous-views.html#time-to-live-ttl-expiration), which SWs actually use internally).

> For my use case, I do just want a view that keeps track of the last 24 hours of records.

One approach here would be to simply make your transform read from the stream directly:

```sql
CREATE CONTINUOUS TRANSFORM t AS SELECT q FROM s WHERE <alarm condition> THEN EXECUTE PROCEDURE alert();
```

(Note that transforms don't get `old` and `new` tuples since they read from raw streams)

And then have a separate continuous view that persists the rows from the stream over your window:

```sql
CREATE CONTINUOUS VIEW v WITH (sw = '1 day') AS SELECT q FROM s;
```

Does that help?

**Comment by tschie** [comment]
I don't think there is an `<alarm condition>` that captures "threshold crossing." I only want an alert when the threshold is crossed from below to above. I don't want to keep getting alerts if new values are still above the threshold.

My workaround is to use two views on the same stream. One that just holds the last 24 hours of records. And another that uses an aggregate with the latest value. The transform will then go on the aggregate view. It just seems like a waste because the first view has all of the information I need (namely the last record) but I can't use it in my transform.

As for this issue though, I still don't understand why removing the sliding window changes everything. You first said
> the problem here is that your continuous view that the transform is reading from isn't doing any aggregation, so no updates are going to be happening

But then you said
> You are aggregating with and without a sliding window.

So does the problem not have to do with aggregations in general, but sliding window aggregations in particular?

> The fundamental difference between sliding-window and non-sliding-window aggregations is that sliding-windows will automatically exclude information that is older than the window.

I get how this effects the contents of the CV but I still don't quite understand how this effects the output stream of a CV. Sorry that I'm not getting it, I really do appreciate your help.

**Comment by derekjn** [comment]
> I don't think there is an <alarm condition> that captures "threshold crossing."

I guess I'm just not clear on what your thresholds even mean in this context, as you haven't really specified any aggregations or computations that you are performing on your stream. Unless I'm mistaken, I think you're implicitly applying meaning to the order of your stream's values. e.g. if `event1` is received after `event0`, then you consider `event1` to be the most "up to date" value.

It seems to me that these values being written to your stream are computed elsewhere, and you just want to use PipelineDB to process them in order. To be honest (if I'm understanding correctly), this isn't really a good case for PipelineDB and you're probably going to keep running into trouble like you are now. What you're talking about here is basically a traditional stream processing/CEP type workload, where you need strong ordering for individual events.

But PipelineDB is designed primarily for high throughput aggregation, which is fairly different. If you're not doing a lot of aggregation everywhere, then it's very likely not the right tool for the job.

It could potentially make sense if you were running these computations within PipelineDB itself and therefore could just put these alerts on actual aggregate output streams, but even then you might run into trouble for the type of workload you're describing. For example, aggregates are updated in microbatches, so you might not get the threshold crossing granularity you need.

> My workaround is to use two views on the same stream. One that just holds the last 24 hours of records. And another that uses an aggregate with the latest value. The transform will then go on the aggregate view. It just seems like a waste because the first view has all of the information I need (namely the last record) but I can't use it in my transform.

I agree that using PipelineDB in this way is overkill and doesn't really fit.

> I get how this effects the contents of the CV but I still don't quite understand how this effects the output stream of a CV. Sorry that I'm not getting it, I really do appreciate your help.

Again, I think you're probably going down the wrong path with PipelineDB here and may want to consider a more traditional stream-processing approach. I think that's probably the fundamental reason for the disconnect here. If you're interested to better understand everything you're asking about, I would strongly suggest reading through the docs though, as everything is explained fairly extensively with examples, and we'd rather not just echo the docs here too much.

**Comment by tschie** [comment]
Fair enough. Thanks for your help.

**Comment by derekjn** [comment]
@tschie np, let me know if you need anything further. If you'd like to discuss your use case and the problem you're trying to solve, feel free to reach out to me via email or Gittr. If PipelineDB doesn't end up being a good fit, maybe I can help point you in the right direction. Closing this for now.
