### ISSUE TITLE
Remove all non-standard CommandDests

### ISSUE THREAD

**Issue by derekjn** [pipelinedb/pipelinedb#1819]
- [x] `DestTupleTable`
- [x] `DestCombiner`
- [x] `DestTransform`

**Comment by derekjn** [comment]
Each of these can probably be replaced fairly cleanly by using `DestTuplestore` and just writing those tuples out as they currently are in the current `CommandDests`.

**Comment by derekjn** [comment]
While this obviously requires a bit of extra iteration since output rows aren't written directly to the receiver, after some initial work it seems like this model will actually help quite a bit with 853.

**Comment by usmanm** [comment]
Yes, that's going to be a pretty killer feature. I think first step is going to be ordered stream processing. Which we can add as another "level", since it'll slow things down a bit.
