### ISSUE TITLE
Remove special handling of scheduler in Postmaster loop

### ISSUE THREAD

**Issue by derekjn** [pipelinedb/pipelinedb#1820]
The scheduler should know how to manage everything on its own, and should appear to the `postmaster` as a regular bgworker.

**Comment by usmanm** [comment]
So this will require us to use `RegisterBackgroundWorker`. The cleanest way would be to actually create an extension, load it via `shared_preload_libraries` and then have the scheduler process boot up at start up time. 

https://www.postgresql.org/docs/9.5/static/bgworker.html

**Comment by derekjn** [comment]
@usmanm do you mean implicitly creating an extension at init time?

**Comment by usmanm** [comment]
Yes, so we can start using the BG worker infrastructure. It'll also help with #1839, since LW locks need to be registered at the time of module init as well.

**Comment by derekjn** [comment]
> Yes, so we can start using the BG worker infrastructure. It'll also help with #1839, since LW locks need to be registered at the time of module init as well.

@usmanm got it. This is mostly what I had in mind with my inceptionish #1685.

**Comment by usmanm** [comment]
Yes, it's pretty much that! Until we get to a point where we need 9.6 for support for partial aggregates etc.

**Comment by derekjn** [comment]
@usmanm moving this to `1.0.0` since it's only relevant within the context of an extension.

**Comment by derekjn** [comment]
Resolved in extension repo.
