### ISSUE TITLE
Remove custom parse node types

### ISSUE THREAD

**Issue by derekjn** [pipelinedb/pipelinedb#1821]
- [ ] CreateContViewStmt (#1699)
- [ ] CreateStreamStmt (#1701)
- [ ] CreateContTransformStmt (#1700)
- [ ] ExplainContQueryStmt (#1822)
- [ ] TruncateContViewStmt (#1823)
- [ ] ActivateStmt (#1702)
- [ ] DeactivateStmt (#1702)

**Comment by sangli00** [comment]
hi ,what time release 0.9.8 pipelineDB?
