### ISSUE TITLE
Remove TuplestoreScan

### ISSUE THREAD

**Issue by derekjn** [pipelinedb/pipelinedb#1824]
We may be able to just use a custom scan node.

**Comment by derekjn** [comment]
Or can we use a `WorkTableScanNext`?

**Comment by derekjn** [comment]
`WorkTableScan` is design for recursive union plans, but it basically does the exact same thing as `TuplestoreScan`. It looks like we should be able to use it if we set it up correctly...

**Comment by derekjn** [comment]
A custom scan is probably cleaner than hijacking the `WorkTableScan` node.

**Comment by usmanm** [comment]
:boom:
