### ISSUE TITLE
keyed_max / keyed_min with sliding window crashes client connection

### ISSUE THREAD

**Issue by brettlaforge** [pipelinedb/pipelinedb#1826]
Problem:

If you create a continuous view with both a keyed_max/keyed_min aggregate as well as a sliding window and don't use group by, the client will crash when there is no data.

Example:

```
pipeline=# CREATE STREAM s (
    x int
);

pipeline=# CREATE CONTINUOUS VIEW cv WITH (sw = '1 day') AS
    SELECT
        keyed_max(1, x) AS keymax
    FROM s;

pipeline=# SELECT * FROM cv;

server closed the connection unexpectedly
	This probably means the server terminated abnormally
	before or while processing the request.
The connection to the server was lost. Attempting reset: Succeeded.
```

- If you add a group by clause it works as expected.
- If you remove the sliding window it works as expected.
- If you remove the keyed_max it works as expected.
 
Version:
```
PipelineDB 0.9.7 at revision 2e5331dd57f1577573c15ab5065091d65eb63a51 on x86_64-pc-linux-gnu, compiled by gcc (Ubuntu 5.4.0-6ubuntu1~16.04.4) 5.4.0 20160609, 64-bit
```

**Comment by derekjn** [comment]
@brettlaforge we just confirmed that this is in fact a different issue from #1797. We'll publish an official release update containing a fix for this issue no later than EOD Monday (7/24). I'll confirm here once it's available.

**Comment by derekjn** [comment]
@brettlaforge we just pushed out a release update that contains a fix for this issue. It also contains some fixes that likely resolves the other behavior you observed with `keyed_min/max` within the context of output streams.

https://github.com/pipelinedb/pipelinedb/releases/tag/0.9.7u6
