### ISSUE TITLE
Usage of indexes in continuous view

### ISSUE THREAD

**Issue by Sudmota** [pipelinedb/pipelinedb#1830]
Dear all, 

I'm running the "latest" pipelinedb container from Docker Hub.
I have a continuous view with some columns, two in particular:
- CHAR(36) id
- TIMESTAMP ts

The view is populated via a kafka_stream, such that:

```
CREATE STREAM test_stream (payload json);
SELECT pipeline_kafka.consume_begin('test', 'test_stream', format := 'json');

CREATE CONTINUOUS VIEW test WITH (ttl='2 month', ttl_column='ts') AS SELECT
((payload->>'ud')::CHAR(36)) AS id,
to_timestamp( TRUNC( CAST( payload->>'ts' AS bigint  ) / 1000 ) ) AS ts,
...
FROM test_stream;
```

Additionally I created some (!!) indexes, in order to try to understand if the query uses them (my goal is to compute the MAX(`ts`) for each `id`:

```
CREATE INDEX test_id_ts_INDEX ON test (id, ts);
CREATE INDEX test_id_tsDESC_INDEX ON test (id, ts DESC);
CREATE INDEX testts_INDEX ON test (ts);
CREATE INDEX testid_INDEX ON test (id);
```

When running `EXPLAIN` on
```
SELECT DISTINCT(id) FROM test;
```
or
```
SELECT id FROM test GROUP BY id;
```

, which should produce a similar output, I see that in neither cases any index is used:

```
 HashAggregate  (cost=250473.71..250479.72 rows=601 width=37)
   Group Key:test_mrel.id
   ->  Seq Scan on test_mrel  (cost=0.00..234901.97 rows=6228697 width=37)
```

The number of returning results seems decent (601), but it doesn't use any index, and takes 10+ seconds to output such results.

Is this a normal behaviour ?

Disk isn't full, logs don't show anything particularly wrong .

**Comment by derekjn** [comment]
@Sudmota are you able to export this data to share with us so we can reproduce the behavior on our end?

**Comment by Sudmota** [comment]
I'm not sure how I should export data for you, but consider this subset of representative data:

```
"00000000-0000-0000-0000-000000000000","2017-07-19 04:33:26+00"
"00000000-0000-0000-0000-000000000001","2017-07-19 04:33:26+00"
"00000000-0000-0000-0000-000000000002","2017-07-19 04:33:26+00"
"00000000-0000-0000-0000-000000000003","2017-07-19 04:33:26+00"
"00000000-0000-0000-0000-000000000004","2017-07-19 04:33:26+00"
"00000000-0000-0000-0000-000000000005","2017-07-19 04:33:26+00"
"00000000-0000-0000-0000-000000000006","2017-07-19 04:33:26+00"
"00000000-0000-0000-0000-000000000007","2017-07-19 04:33:27+00"
"00000000-0000-0000-0000-000000000008","2017-07-19 04:33:28+00"
"00000000-0000-0000-0000-000000000009","2017-07-19 04:33:28+00"
```

**Comment by derekjn** [comment]
@Sudmota can you share the entire CV definition? I'm guessing you're not using any aggregates--is that accurate? And how many rows are in that CV (`SELECT count(*) FROM test`)?

CVs without aggregates are a pretty huge anti-pattern and should almost never be used because the CV size will obviously grow without bound.

I'm guessing your CV is just really big and that's why the query is slow. As far as why the index isn't being used, I'm not exactly sure. Postgres is choosing the plan that it thinks is the fastest, so it's possible that your stats are out of date or something.
