### ISSUE TITLE
How to query top-k in Stream?

### ISSUE THREAD

**Issue by sangli00** [pipelinedb/pipelinedb#1831]
eg:I query some visited   website  top-100  one day.

**Comment by derekjn** [comment]
@sangli00 the `fss_*` [aggregate](http://docs.pipelinedb.com/aggregates.html#filtered-space-saving-aggregates) and [functions](http://docs.pipelinedb.com/builtin.html#filtered-space-saving-functions) work well for this. Use `fss_agg` to build the object that maintains the top-k state:

```sql
CREATE CONTINUOUS VIEW v0 AS SELECT fss_agg(x, 100) AS top_100 FROM s
```

And then use the `fss_topk` functions to read the object created by `fss_agg`:

```sql
--- Get an array of tuples of the form: <value, frequency>
SELECT fss_topk(top_100) FROM v0
```

```sql
-- Get an array of the most frequently occurring values
SELECT fss_topk_values(top_100) FROM v0
```

```sql
-- Get an array of the frequencies associated with the most frequently occurring values
SELECT fss_topk_freqs(top_100) FROM v0
```

The results returned by these functions are usually unpacked using `unnest`. Let us know if that helps!

**Comment by sangli00** [comment]
@derekjn  Thanks very much .
