### ISSUE TITLE
Add Debian 9 builds to CI

### ISSUE THREAD

**Issue by EliSnow** [pipelinedb/pipelinedb#1835]
It would be nice to have builds for Debian 9

**Comment by derekjn** [comment]
@EliSnow we've added a Debian 9 (Stretch) build and they'll be published via the normal CI flow moving forward. We'll get around to updating the downloads page of our website, and I also went ahead and added a Debian 9 binary to the latest release:

https://github.com/pipelinedb/pipelinedb/releases/tag/0.9.7u8

Thanks for the suggestion!

**Comment by derekjn** [comment]
Also, Debian 9 introduced some changes to the `libreadline` packaging, so you may have to do something like this:

    apt-get install libreadline7

**Comment by EliSnow** [comment]
Thank you!
