### ISSUE TITLE
Standardize nodeAgg

### ISSUE THREAD

**Issue by derekjn** [pipelinedb/pipelinedb#1838]
We probably can't use a `CustomScan` for this. And it will probably involve #1732 as well.  What we'll likely want to end up doing is just create separate aggregates that only aggregate into transitions states, and plan things accordingly.

- [ ] Remove `AGGKIND_COMBINE`.
- [ ] Remove `PIPELINE_EXEC_CONTINUOUS`

**Comment by usmanm** [comment]
I think Postgres 9.6+ has native support for this in the form of parallel aggregates.

**Comment by derekjn** [comment]
> I think Postgres 9.6+ has native support for this in the form of parallel aggregates.

@usmanm so we may just want to do this part when we're porting to the extension then. I'd like to avoid an upstream merge if possible.

**Comment by usmanm** [comment]
Yes, I think that makes sense. Try to get as much as possible done with #1685, and then port the extension to vanilla 9.6.
