### ISSUE TITLE
Create a pipeline extension

### ISSUE THREAD

**Issue by usmanm** [pipelinedb/pipelinedb#1841]
Add it to `contrib`, compile it at build time, add it to the config so it's automatically loaded using `shared_preload_libraries`, install it at with core and add `CREATE EXTENSION pipeline` to `initdb`.

**Comment by derekjn** [comment]
@usmanm should we just merge this with #1685 or is there something materially different here?

**Comment by usmanm** [comment]
I think we should close #1685. This is like a micro task included in that.

**Comment by derekjn** [comment]
Cool, so we'll just keep incrementally adding issues after this one then.

**Comment by usmanm** [comment]
Started work on this. Should have something done by tonight or tomorrow.

**Comment by usmanm** [comment]
There's one problem with extensionizing: we can't call into the extension code from code. Not sure how much of a problem it's going to be.

**Comment by derekjn** [comment]
> There's one problem with extensionizing: we can't call into the extension code from code. Not sure how much of a problem it's going to be.

If I'm understanding correctly, you're referring to the migration period when both an extension and forked code coexsit, right?

It may end up being easiest to only do the extension port in a "single" pass, once everything is standardized so we can basically just move everything to a tree organized as an extension.

**Comment by usmanm** [comment]
Yes, that's what I mean. I guess we should split tasks into pre and post extension refactor. Some tasks like moving scheduler to `BackgroundWorker` can only happen post extension.

**Comment by derekjn** [comment]
That makes sense, anything under the `1.0.0` is probably fine for post extension. Everything leading up to that is basically a standardization effort, so extensionizing after that becomes (as much as possible) just organizing it all into an extension.

**Comment by esatterwhite** [comment]
Still very excited to see the pg extension happen. Is there a rough time line on this?

**Comment by derekjn** [comment]
@esatterwhite we are very excited about it too! The extension release is code complete and you should start seeing the code land in this repo within the next week or so, then we'll be publicly announcing the release shortly after that. As a rough timeline, you can expect to start seeing official releases published within the next two weeks.

PipelineDB has never been better, this is very much a `1.0` release with countless fundamental improvements based on everything we've learned and has performed extremely well under weeks and weeks of rigorous stress testing on machines with hundreds of cores under sustained maximum load. Thanks for you patience, we always take the time to do things the right way and I think you'll be happy with the results :) Stay tuned!

**Comment by derekjn** [comment]
https://www.pipelinedb.com/blog/pipelinedb-1-0-0-high-performance-time-series-aggregation-for-postgresql
