### ISSUE TITLE
Remove ParseState state additions

### ISSUE THREAD

**Issue by derekjn** [pipelinedb/pipelinedb#1850]
- [x] `ParseState->p_no_locking`
- [x] `ParseState->p_cont_view_context`
- [x] `ParseState->p_ins_cols`

**Comment by derekjn** [comment]
@usmanm I'm not sure if the `p_no_locking` field is even necessary anymore, do you remember what conditions led to https://github.com/pipelinedb/pipelinedb/commit/68b0ede52f92621e5385e73ea1f8b65c4e479433#diff-f31fb96ba744db980903ce20a528b85eR837?

**Comment by usmanm** [comment]
From the test case added if seems like it was added to "fix" some of the deadlock issues when adding + dropping continuous views concurrently. Over time, we made a lot of concurrency control improvements to those code paths, so it's possible that this flag isn't needed anymore.

**Comment by derekjn** [comment]
@usmanm removing the `p_no_locking` did re-introduce some deadlocking possibilities between `DROP` and the combiner. Basically the combiner acquires locks in an order we don't control, since the analyzer/planner/executor can acquire locks however they want. Previously we just overrode this planner/analyzer/executor behavior with the flag in question.

The deadlocks can happen under the following circumstances (and probably more):

* `select_existing_groups` plans the lookup query (cache miss since we cache that plan)
* A `DROP CONTINUOUS VIEW` is issued concurrently while the combiner's xact is still open
* The `DROP` takes locks on the CV's dependent objects, and waits on `deadlock_rel`
* But the analyzer/planner/executor already acquired a lock on `deadlock_rel`
* The combiner attempts to acquire a lock on one of the objects that the dropper currently holds a lock on, but it's obviously blocked by the combiner so we're deadlocked

It seems like a straightforward way to resolve all of this would be to simply add a shared-memory lock for the CV that must be acquired before acquiring any other locks, either by the dropper or the combiner. Would that make sense?

**Comment by derekjn** [comment]
We could even make the above locking scheme super simple (and statically allocated) by having only a single lock for all CQs, since there would only be contention during `DROP CONTINUOUS` which is a rare operation. Basically this would ensure that no `DROP CONTINUOUS` would be performed while *any* CQ is currently executing.

**Comment by usmanm** [comment]
You mean have an `LWLock`. All workers + combiners acquiring it in shared mode and unlock at EOT, but the adder/dropper acquire it in exclusive mode?

**Comment by derekjn** [comment]
> You mean have an LWLock. All workers + combiners acquiring it in shared mode and unlock at EOT, but the adder/dropper acquire it in exclusive mode

Yea exactly.

**Comment by derekjn** [comment]
Although at first glance, I guess the problem with the LW lock approach is that with many combiners/workers, it's fairly likely that at least one process will always be holding the lock, which would obviously block the dropper indefinitely...

**Comment by usmanm** [comment]
Yes, I think we'll stave the DDL statements. We need a lock that guarantees fairness.

**Comment by derekjn** [comment]
Yea, I'm brainstorming some solutions to this--do you have any thoughts on a high-level approach here?

**Comment by derekjn** [comment]
Off the top of my head, any reliable approach we go with here will have to do one of two things:

* Ensure `DROP` order is congruent with lock acquisition order in the combiner
* Ensure combiner and `DROP` transactions are mutually exclusive (not concurrent)

I believe the first approach is basically not possible, given that the planner/executor can acquire locks in whatever order it chooses. So it seems like the second option is going to be required, unless my reasoning if flawed.

**Comment by usmanm** [comment]
I agree that two-phased locking is the ideal approach but we can't do it since lock order is out of our control. Are table locks fair? If so, we can create a lock table and use that instead of a LWLock. If worst case, we can implement a simple fair LWLock?

**Comment by derekjn** [comment]
I also considered a table-based approach here, it's an interesting idea. If we're going to do that, couldn't the dropper just explicitly acquire an `AccessExclusiveLock` on the matrel before proceeding along the delete path? Currently it uses the PG core delete infrastructure so we just don't even control any part of it, but it would be easy to intercept a `DROP CONTINUOUS` and acquire any necessary locks programmatically...

**Comment by usmanm** [comment]
That can still result in protocol violation of two-phased locking. Especially because both combiners and the `DROP` have to take other conflicting locks, such as on the `pipeline_query` table. Having a table that's only used for locking avoids this problem. But we must make sure table locks prioritize fairly, otherwise it's no better than a `LWLock`.

**Comment by usmanm** [comment]
It might be worth looking at Advisory Locks: https://www.postgresql.org/docs/9.1/static/explicit-locking.html

**Comment by derekjn** [comment]
Table locks do behave fairly, but they're probably not going to work, as they require an explicit `BEGIN` block. e.g. `DROP CONTINUOUS` would not work, it would have to be:

```sql
BEGIN;
DROP CONTINUOUS ...
```

Implicitly adding a `BEGIN` within the `DROP CONTINUOUS` xact seems like a bad idea, and we'd have to also add them to the combiner loop. I tried some basic prototyping and a bunch of unexpected and weird things started happening when I did that.

But since table locks do appear to be fair, maybe it's worth investigating using the underlying locking mechanisms directly.

**Comment by usmanm** [comment]
Can't we just call rel_open inside the DROP handler?

**Comment by derekjn** [comment]
> Can't we just call rel_open inside the DROP handler?

As long as it behaves fairly like advisory locks do, yea.

**Comment by derekjn** [comment]
The other complication here is that the combiner loop may begin/commit a transaction in `ContExecutorStartNextQuery`, whereas when we take a lock on a relation it must be within a single transaction. So it's slightly tricky to obtain a lock this way such that it safely spans all CQ executions...

**Comment by derekjn** [comment]
After doing some prototyping with just acquiring locks on a table used exclusively for locking, that approach is going to work. But as I noted above it's a bit awkward to implement with how we currently commit/begin transactions implicitly in certain places. But we just need to make sure we acquire the lock immediately after beginning the transaction and we should be good.

All of this can be handled within `executor.c` so it shouldn't be too messy.

**Comment by derekjn** [comment]
@usmanm finished prototyping the lock table approach and it works pretty well. As I mentioned the implementation is kind of awkward because we have transaction seams throughout the worker/combiner loops, but it's manageable after wrapping everything up in the `ContExecutor` methods.

I'll have a diff later today, if you can spare a few minutes it would be really helpful if you could take a look at it.
