### ISSUE TITLE
Eliminate locking flags

### ISSUE THREAD

**Issue by derekjn** [pipelinedb/pipelinedb#1855]
- [ ] `EXEC_NO_MATREL_LOCKING`
- [ ] `EXEC_NO_STREAM_LOCKING`
- [ ] `EXEC_FLAG_COMBINE`

**Comment by derekjn** [comment]
With the new locking improvements it's likely that this is no longer necessary.

**Comment by derekjn** [comment]
Only one use:

https://github.com/pipelinedb/pipelinedb/blob/master/src/backend/executor/execUtils.c#L835

**Comment by usmanm** [comment]
One thing we can do is have tuples inside the _lock table_ and use a tuple to synchronize these different code paths. We probably just need two: one for streams, one for continuous queries.

**Comment by derekjn** [comment]
I'm pretty sure we originally made these areas lockless because of `DROP CONTINUOUS` deadlocks, right? If that's the only purpose they serve they're obsolete now...

**Comment by usmanm** [comment]
And `DROP STREAM`.

**Comment by derekjn** [comment]
Yes good point, I should probably adapt the latest locking stuff to include `DROP STREAM`.
