### ISSUE TITLE
Upgrade failed due to conflicts with a system column name

### ISSUE THREAD

**Issue by venu** [pipelinedb/pipelinedb#1864]
Hi,

We are trying to upgrade 0.9.7 to 0.98..

We added one key arrival_timestamp in to stream (apparently it's a system column name)
now pipeline-upgrade fails due to this column name "arrival_timestamp" conflicts with a system column name

Unfortunately there is no way to delete a field from stream.. but system allowed adding that field...

Could you please help on this?

**Comment by derekjn** [comment]
Hi @venu, thanks for reporting!

We took a look at this and it looks like the easiest way to upgrade will be to export and load all of your data with [pipeline-dump/restore](http://docs.pipelinedb.com/backups.html). This is a bit slower than `pipeline-upgrade`, but it should work reliably.

Please let us know here if you have any issues with that approach.

**Comment by venu** [comment]
Sorry for the delayed response.

We did try that after `pipeline-upgrade` failed, but failed due to memory exhaustion..Luckily we are still on development, so we could skip that data and start a fresh.
