### ISSUE TITLE
Continuous view is can't Agg

### ISSUE THREAD

**Issue by sangli00** [pipelinedb/pipelinedb#1866]
stream:
```
CREATE STREAM iprobe_zone_data_stream(ZoneID bigint,InOctets bigint,OutOctets bigint,InPkts bigint,OutPkts bigint,Session bigint,Date timestamp,arrival_time timestamp);
```

CV:
```
CREATE CONTINUOUS VIEW iprobe_zone_data_tbl_min
WITH (ttl = '7 day', ttl_column = 'interval_time') 
AS
select ZoneID,
    sum(InOctets) as InOctets ,
    sum(OutOctets) as OutOctets,
    sum(InPkts) as InPkts,
    sum(OutPkts) as OutPkts,
    sum(Session) as Session ,
    make_timestamp(EXTRACT(year from arrival_time)::int,EXTRACT(month from arrival_time)::int,EXTRACT(day from arrival_time)::int,EXTRACT(hour from arrival_time)::int,(EXTRACT(minute from arrival_time)::int/5 * 5)::int,0.0::double precision) as interval_time 
from iprobe_zone_data_stream
group by ZoneID,interval_time;
```

Query:
```
pipeline=# select * from iprobe_zone_data_tbl_min where zoneid = 1 and interval_time = ' 2017-09-13 23:45:00'::timestamp;
 zoneid | inoctets | outoctets | inpkts | outpkts | session |    interval_time
--------+----------+-----------+--------+---------+---------+---------------------
      1 |    14192 |     23395 |    128 |     164 |      35 | 2017-09-13 23:45:00
      1 |        0 |         0 |      0 |       0 |       0 | 2017-09-13 23:45:00
(2 rows)

pipeline=#
```
Why CV is not agg this data?

**Comment by derekjn** [comment]
@sangli00 can you provide some `INSERT` statements to reproduce this?

**Comment by sangli00** [comment]
@derekjn  I recreate  this CV is OK.

**Comment by hnnyzyf** [comment]
Hi，I have found the same issue in our production enviroment and the version is 0.97。
It will happan in this situation：
when a cv has been used for a long time，if you restart the pipeline instance， you can find the old cq does not work correctly，but if you create a new cv，the new cv will work correctly.

we create almost 200+ different cvs and use pipeline to aggr more than 15TB data every day on a single machine.

**Comment by derekjn** [comment]
Hi @hnnyzyf, a few questions for you:

* Would you be able to share a CV definition for which you've seen this behavior?
* How man rows are in the CV?
  * `SELECT count(*) FROM cv_name`
* What is the CV's materialization table's maximum `$pk` column value?
  * `SELECT max("$pk") FROM <cv_name>_mrel`
