### ISSUE TITLE
transaction ids being assigned for queries on hot standby pipelinedb 9.8.0

### ISSUE THREAD

**Issue by ericfonseca** [pipelinedb/pipelinedb#1867]
I am having an issue when trying to query a hot standby, i get the error:

`ERROR:  cannot assign TransactionIds during recovery`

If i enable verbose logs, the error is being thrown here:

```
varsup.c:72
/* safety check, we should never get this far in a HS standby */ 
if (RecoveryInProgress())
   elog(ERROR, "cannot assign TransactionIds during recovery");
```

This issue does not occur on pipelinedb 9.7.8

I tested with these packages [pipelinedb-0.9.7u8-ubuntu16-x86_64.deb, pipelinedb-0.9.8u0-ubuntu16-x86_64.deb]

Here are the steps to reproduce (pretty much your replication doc) :
```
1. sudo dpkg -i {package}

2. pipeline-init -D ~/pipelinedb

3. cd ~/pipelinedb

4. pipeline-ctl -D . -l logfile start

5. pipeline pipeline 

6. CREATE ROLE replicator WITH LOGIN REPLICATION;

7. add

wal_level = hot_standby
max_replication_slots = 1
max_wal_senders = 2

to pipelinedb.conf

8. add

host    replication     replicator         ::1/128                 trust

to pg_hba.conf

9. pipeline-ctl -D . -l logfile restart

10. pipeline pipeline 

11. SELECT * FROM pg_create_physical_replication_slot('replicator_slot');

12. pg_basebackup -X stream -D ~/pipelinedb_standby -h localhost -U replicator

13.  cd ~/pipelinedb_standby

14. remove 

wal_level = hot_standby
max_replication_slots = 1
max_wal_senders = 2

and add

hot_standby = on 

to pipelinedb.conf

15. add

standby_mode = 'on'
primary_slot_name = 'replicator_slot'
primary_conninfo = 'user=replicator host=localhost port=5432'
recovery_target_timeline = 'latest'

to recovery.conf

16. pipeline-ctl -D . -l logfile start -o "-p 5433"

17. pipeline pipeline -p 5433

18. SELECT pg_is_in_recovery();
```

If you need any more info or want me check something let me know. thanks.

**Comment by derekjn** [comment]
@ericfonseca thank you so much for this wonderful writeup! The team is currently looking into this and we'll have a solution and potential release update published for you soon. We'll keep you posted!

**Comment by ericfonseca** [comment]
hi @derekjn, are there any updates on this issue?

**Comment by derekjn** [comment]
@ericfonseca we haven't gotten around to a fix just yet, should happen by the end of this week though. Thanks for the reminder!

**Comment by derekjn** [comment]
@ericfonseca an updated official release has now been published:

https://github.com/pipelinedb/pipelinedb/releases/tag/0.9.8u1

Thanks again for your thoughtful report!

**Comment by ericfonseca** [comment]
@derekjn thank you for the fix!! :)
