### ISSUE TITLE
support for -o flag like in kafkacat

### ISSUE THREAD

**Issue by timnon** [pipelinedb/pipelinedb#1872]
Is it possible to start the consumption using the last n messages? Comparable to `-o -1000` for the last 1000 messages in kafkacat. Couldnt find anything `start_offset:=-1000` doesnt work.

A normal use case is to pull some messages from the queue to avoid a cold start without any history. However, starting at the beginning of the queue takes quite some time depending on how much is saved, so limiting this process to the e.g. last 1000000 messages would be nice.

I also experienced that offsets are not reseted when dropping the complete extension, it is then still necessary to reset them by hand using the offsets-table.

**Comment by derekjn** [comment]
@timnon I moved this over to https://github.com/pipelinedb/pipeline_kafka/issues/70.
