### ISSUE TITLE
json_object_int_sum - Returns empty result with ad hoc queries

### ISSUE THREAD

**Issue by venu** [pipelinedb/pipelinedb#1874]
Hi,

I am trying `json_object_int_sum` aggregator,  it's working very well in continuous CV. But ad hoc query aggregation is not working, returns empty value. There is one more crash in this aggregator, will submit in another issue.

**Test Scenario:**
```
CREATE STREAM elapsed_json_stream (app_id varchar, country varchar, elapsed_time bigint);

CREATE CONTINUOUS TRANSFORM elapsed_json_transform AS
SELECT '{ "' || ((elapsed_time / 10) * 10)::text || '": ' || 1 || ' }' elapsed_time_bucket, country, app_id  FROM  elapsed_json_stream;


CREATE CONTINUOUS VIEW elapsed_json_cv AS SELECT json_object_int_sum(elapsed_time_bucket) as elapsed_time_bucket, app_id, country FROM output_of('elapsed_json_transform') group by app_id, country;

insert into elapsed_json_stream values ('a', 'us', 100);
insert into elapsed_json_stream values ('a', 'us', 100);
insert into elapsed_json_stream values ('a', 'us', 100);
insert into elapsed_json_stream values ('b', 'us', 100);
insert into elapsed_json_stream values ('a', 'uk', 100);
insert into elapsed_json_stream values ('a', 'uk', 100);
```

**Data is properly aggregated and stored:**
```
pipeline=# select * from elapsed_json_cv;
 elapsed_time_bucket | app_id | country 
---------------------+--------+---------
 { "100": 3 }        | a      | us
 { "100": 1 }        | b      | us
 { "100": 2 }        | a      | uk
(3 rows)
```

**Ad hoc query fails:**
```
pipeline=# select app_id, json_object_int_sum(elapsed_time_bucket::text) as elapsed_time_bucket from elapsed_json_cv group by app_id;
 app_id | elapsed_time_bucket 
--------+---------------------
 b      | 
 a      | 
(2 rows)
```
Please check this and let me know if I am missing anything.

**Comment by derekjn** [comment]
@venu thank you so much for the detailed report, this makes it easy on us! I'm going to go ahead and merge this w/ #1875, as after taking a look the underlying causes are related.

**Comment by venu** [comment]
Hi @derekjn ,

I have tested this on https://github.com/pipelinedb/pipelinedb/issues/1875 fix, but this is not fixed.

Could you please check it once?

Thanks,
Venu

**Comment by venu** [comment]
Sorry, with combine function it works well..

This fails
```
pipeline=# select app_id, json_object_int_sum(elapsed_time_bucket::text) as elapsed_time_bucket from elapsed_json_cv group by app_id;
 app_id | elapsed_time_bucket 
--------+---------------------
 b      | 
 a      | 
(2 rows)
```
Works perfectly
```
pipeline=# select app_id, combine(elapsed_time_bucket) as elapsed_time_bucket from elapsed_json_cv group by app_id;
 app_id | elapsed_time_bucket 
--------+---------------------
 b      | { "100": 1 }
 a      | { "100": 5 }
(2 rows)
```

Thank you!

**Comment by derekjn** [comment]
@venu is using `combine` sufficient for now? We have some general cleanup to do with that function (see [comments here](https://github.com/pipelinedb/pipelinedb/blob/master/src/backend/utils/adt/pipelinefuncs.c#L829)) and can include this issue in that rework. But if you need to use `json_object_int_sum` directly outside of a CV definition we can look at shipping a fix sooner.

**Comment by venu** [comment]
ya, combine is fine @derekjn. You can take care while refactoring.

Thank you so much!
