### ISSUE TITLE
Performance concerns about pure SQL vs pipeline_kafka

### ISSUE THREAD

**Issue by cailin-lai** [pipelinedb/pipelinedb#1880]
Hi @derekjn,
May I know something about the performance metric about pipeline_kafka extension?
Assuming that we consume data from kafka by pipeline_kafka extension, will it be much slower than pure sql data talks to pipelinedb directly?
Please show me some pieces or suggestions. Appreciate for help!

Allen Lai

**Comment by cailin-lai** [comment]
Hi @derekjn,
Assuming we need continuously consume ~20k detailed data per seconds via pipeline_kafka extension which produced by 20 clients with multiple processes, would it be performance issue?
In this case, would pure sql be much sufficient?
Hoping to see your advise!
Thanks.

**Comment by derekjn** [comment]
@cailin-lai `pipeline_kafka` internally uses `COPY` to write data to streams, so each consumer process is basically as fast as possible already. The `parallelism` argument to your consume command determines how many parallel consumer processes run, with a maximum of 1 consumer process per Kafka partition.

**Comment by cailin-lai** [comment]
Thanks @derekjn, it is helpful!
Basically, according to our verifications, sounds like the data consuming performance index heavily depends on server disk i/o since the specific data scenarios, wherever it consumes from SQL or kafka. Anyway, SSD device is required.
I'd close this question.
