### ISSUE TITLE
Reaper generating invalid expiration query

### ISSUE THREAD

**Issue by derekjn** [pipelinedb/pipelinedb#1881]
(From @bartlomiej-korpus on Gittr)

hello! I've got a problem with 0.9.8 with sliding window views, old rows don't get deleted from underlying tables, in the console i can see the following error

```
ERROR: relation "public.sometablenamewithuppercaseletters_mrel" does not exist at character 13 QUERY: DELETE FROM public.SomeTableNameWithUpperCaseLetters_mrel WHERE "$pk" IN (SELECT "$pk" FROM public.SomeTableNameWithUpperCaseLetters_mrel WHERE arrival_timestamp < now() - interval '259200 seconds' LIMIT 10000 FOR UPDATE SKIP LOCKED);
```

basically, my continuous view name contains uppercase letters, and they don't get properly put into " " characters when creating a DELETE query

**Comment by derekjn** [comment]
@bartlomiej-korpus we've just published an official release update containing a fix for this issue:

https://github.com/pipelinedb/pipelinedb/releases/tag/0.9.8u2

**Comment by bartlomiej-korpus** [comment]
@derekjn awesome, thanks!
