### ISSUE TITLE
Change the definition of a continous view

### ISSUE THREAD

**Issue by fritzrichter** [pipelinedb/pipelinedb#1883]
Hey there,
I am wondering how I can do the following without loosing the data:

**BEFORE**
`CREATE CONTINUOUS VIEW impressions_daily AS
SELECT
date_trunc('day', impression_time) AS day,
company_id,
COUNT(*) AS total_impressions,
COUNT(DISTINCT maid) AS unique_users
FROM impression_stream
GROUP BY company_id, day;`

**AFTER**
`CREATE CONTINUOUS VIEW impressions_daily AS
SELECT
date_trunc('day', impression_time) AS day,
company_id,
COUNT(*) AS total_impressions,
COUNT(DISTINCT maid) AS unique_users
FROM impression_stream
WHERE platform_id IS NULL
GROUP BY company_id, day;`

Is there a way to ALTER or change the view, as I want to add a new WHERE expression.

**Comment by derekjn** [comment]
@fritzrichter currently there is no way to directly modify a continuous view. However, you can load whatever data you want into `_mrel` tables as long as `continuous_query_materialization_table_updatable` is set to `on`. So you may be able to do something along the lines of:

* Create the new CV
* `SET continuous_query_materialization_table_updatable TO on`
* `INSERT INTO new_mrel SELECT ... FROM old_mrel` 

Is that feasible in your case?

**Comment by fritzrichter** [comment]
That totally makes sense. Thanks for sharing this idea, which is at least a good workaround. Feel free to close the ticket then. Best, Fritz
