### ISSUE TITLE
Segmentation fault

### ISSUE THREAD

**Issue by bartlomiej-korpus** [pipelinedb/pipelinedb#1892]
Hello,
Sometimes in Docker on my dev machine, after restarting it, I get this error from PipelineDB when trying to perform inserts.
Dropping all my streams and recreating them fixes the issue, but I also lose all the data that I seeded.

`    ____  _            ___            ____  ____
   / __ \(_)___  ___  / (_)___  ___  / __ \/ __ )
  / /_/ / / __ \/ _ \/ / / __ \/ _ \/ / / / __  |
 / ____/ / /_/ /  __/ / / / / /  __/ /_/ / /_/ /
/_/   /_/ .___/\___/_/_/_/ /_/\___/_____/_____/
       /_/
2017-12-11T14:03:08.353903100Z 
LOG:  database system is ready to accept connections
LOG:  autovacuum launcher started
LOG:  pipelinedb scheduler started
LOG:  starting pipelinedb processes for database: "pipeline"
LOG:  pipelinedb process "queue0 [pipeline]" running with pid 24
LOG:  pipelinedb process "reaper0 [pipeline]" running with pid 23
LOG:  pipelinedb process "worker0 [pipeline]" running with pid 22
LOG:  pipelinedb process "combiner0 [pipeline]" running with pid 25
LOG:  using stale statistics instead of current ones because stats collector is not responding
Segmentation fault (PID 25)
version: PipelineDB 0.9.8 at revision d8154c517801b5150759c66f2b37fd5c906ca68a on x86_64-pc-linux-gnu, compiled by gcc (Debian 4.9.2-10) 4.9.2, 64-bit
query: MyViewName
backtrace:
pipelinedb: bgworker: combiner0 [pipeline]   (debug_segfault+0x15)[0x60afe5]
/lib/x86_64-linux-gnu/libpthread.so.0(+0xf890)[0x7f695d239890]
pipelinedb: bgworker: combiner0 [pipeline]   [0x47bb1d]
pipelinedb: bgworker: combiner0 [pipeline]   (slot_getsomeattrs+0x3e)[0x47d65e]
pipelinedb: bgworker: combiner0 [pipeline]   (ExecProject+0x58)[0x5beb88]
pipelinedb: bgworker: combiner0 [pipeline]   [0x5c3756]
pipelinedb: bgworker: combiner0 [pipeline]   (ExecAgg+0x3c6)[0x5c44f6]
pipelinedb: bgworker: combiner0 [pipeline]   (ExecProcNode+0xf8)[0x5b8358]
pipelinedb: bgworker: combiner0 [pipeline]   (ExecutePlan+0x45)[0x5b6995]
pipelinedb: bgworker: combiner0 [pipeline]   (standard_ExecutorRun+0x112)[0x5b6b12]
pipelinedb: bgworker: combiner0 [pipeline]   [0x6c1d98]
pipelinedb: bgworker: combiner0 [pipeline]   (PortalRun+0x25e)[0x6c30de]
pipelinedb: bgworker: combiner0 [pipeline]   [0x656090]
pipelinedb: bgworker: combiner0 [pipeline]   (ContinuousQueryCombinerMain+0x468)[0x658118]
pipelinedb: bgworker: combiner0 [pipeline]   [0x65471f]
pipelinedb: bgworker: combiner0 [pipeline]   (StartBackgroundWorker+0x181)[0x65f8e1]
pipelinedb: bgworker: combiner0 [pipeline]   [0x66b572]
pipelinedb: bgworker: combiner0 [pipeline]   [0x475263]
pipelinedb: bgworker: combiner0 [pipeline]   (PostmasterMain+0xe8a)[0x66d1fa]
pipelinedb: bgworker: combiner0 [pipeline]   (main+0x3fd)[0x47621d]
/lib/x86_64-linux-gnu/libc.so.6(__libc_start_main+0xf5)[0x7f695c272b45]
pipelinedb: bgworker: combiner0 [pipeline]   [0x4762b7]
LOG:  worker process: combiner0 [pipeline] (PID 25) exited with exit code 1
LOG:  pipelinedb process "combiner0 [pipeline]" running with pid 4070
ERROR:  cache lookup failed for type 0
STATEMENT:  MyViewName
ERROR:  cache lookup failed for type 0
STATEMENT:  MyViewName
`

**Comment by derekjn** [comment]
@bartlomiej-korpus ok great! Please re-open this issue if that does not resolve the problem. Thanks for reporting!
