### ISSUE TITLE
How to improve CV query?

### ISSUE THREAD

**Issue by sangli00** [pipelinedb/pipelinedb#1894]
CV define:
![wechatimg27](https://user-images.githubusercontent.com/3765918/34186391-34344a68-e566-11e7-8c0a-a080b266044d.jpeg)

SQL query:
![wechatimg6](https://user-images.githubusercontent.com/3765918/34186284-bfc89ea4-e565-11e7-9090-0815ca773015.jpeg)

explain:
![wechatimg4](https://user-images.githubusercontent.com/3765918/34186321-da06dbd2-e565-11e7-9f3d-fabaa9bdadcf.jpeg)

table size:
![wechatimg6](https://user-images.githubusercontent.com/3765918/34186406-49cb8922-e566-11e7-8bad-eaa446a8c8c8.jpeg)

Why query is very slowly?
I modify config ```continuous_query_combiner_work_mem``` is not improve.

**Comment by sangli00** [comment]
HLL column toast 2.1M

**Comment by derekjn** [comment]
@sangli00 can you copy/paste the full CV definition here in text form, along with all `SELECT` queries against the CV?

**Comment by sangli00** [comment]
CV definition:
```
create continuous view reinforce.app_world_num_2month as
select
  app_id::integer, 
  (ip2location).country_short as stat_area,
  date_trunc('month', arrival_timestamp) as stat_time,
  count(distinct user_ipaddress) as stat_count
from atomic.stream_event
where arrival_timestamp >= date_trunc('month',clock_timestamp()) -interval '1 month'
group by app_id::integer,stat_time,stat_area;
```
select query:
```
SELECT stat_area,sum(stat_count) AS userTotal
        FROM  reinforce.app_world_num_2month as userTable
where app_id in (1000,1001)
and stat_time >=Timestamp '2017-12-01 00:00:00'
and stat_tiem <Timestamp '2017-12-21 23:59:59'
 GROUP BY stat_area
```

@derekjn

**Comment by derekjn** [comment]
```sql
SELECT count(*) FROM reinforce.app_world_num_2month
-- (436 rows)
```

**Comment by derekjn** [comment]
@sangli00 this is a sliding-window CV, which internally uses many more rows than are actually visible in final results. When you're including a `timestamp` column *and* using a sliding window, what you really probably want is a CV with a TTL instead of a sliding window.

So something like this will perform a lot better:

```
create continuous view reinforce.app_world_num_2month with (ttl = '1 month', ttl_column = 'stat_time') as
select
  app_id::integer, 
  (ip2location).country_short as stat_area,
  date_trunc('month', arrival_timestamp) as stat_time,
  count(distinct user_ipaddress) as stat_count
from atomic.stream_event
group by app_id::integer,stat_time,stat_area;
```

**Comment by sangli00** [comment]
PipelineDB version is old .
maybe i need upgrade .

https://www.pipelinedb.com/blog/pipelinedb-0-9-7-delta-streams-and-towards-a-postgresql-extension
```HyperLogLog Performance Improvement```
