### ISSUE TITLE
Bloom_intersection affects subsequent columns

### ISSUE THREAD

**Issue by carter-andrewj** [pipelinedb/pipelinedb#1895]
The following query produces two different outcomes for identical columns `cohort_before` and `cohort_after`:

```
SELECT
	retentionusers.cohortdate,
	retentionusers.retentionage,
	BLOOM_CARDINALITY(BLOOM_UNION_AGG(cohortsize.uniqueusers)) AS cohort_before,
	BLOOM_CARDINALITY(BLOOM_INTERSECTION(BLOOM_UNION_AGG(cohortsize.uniqueusers), BLOOM_UNION_AGG(retentionusers.uniqueusers))) AS retained,
	BLOOM_CARDINALITY(BLOOM_UNION_AGG(cohortsize.uniqueusers)) AS cohort_after
FROM studio_teststudio1_product_testproduct1a.retentionusers retentionusers
INNER JOIN studio_teststudio1_product_testproduct1a.cohortsize cohortsize
	ON retentionusers.cohortdate = cohortsize.cohortdate
GROUP BY retentionusers.cohortdate, retentionusers.retentionage;
```

`BLOOM_INTERSECTION(...)` appears to be having an affect outside of the column it defines, producing the result shown here:

<img width="679" alt="screen shot 2017-12-24 at 17 23 21" src="https://user-images.githubusercontent.com/16546089/34328176-479f304c-e8cf-11e7-87a5-dbb2ca6a5121.png">

After `BLOOM_INTERSECTION` any columns/aggregations using `cohortsize.uniqueusers` seem to instead receive `BLOOM_INTERSECTION(BLOOM_UNION_AGG(cohortsize.uniqueusers), BLOOM_UNION_AGG(retentionusers.uniqueusers))` as input.

The issue may only occur when using `BLOOM_INTERSECTION` and `BLOOM_UNION_AGG` together as I was able to reproduce it with manually entered data only in that circumstance. (Though my explorations here have not been exhaustive.)

Am running the latest version of pipelineDB (0.9.8), but saw it originally on an older version (apologies - I did not note the old version number before upgrading in an initial attempt to fix the issue). Have searched for this issue being raised elsewhere, but can see no sign of it (so apologies if I'm unwittingly duplicating something that's already known). 

I'm working on a system that generates and manages its own queries atop pipelineDB, so solving this by ordering the columns accordingly is not particularly feasible. In addition, I have other more complex tables that take the intersection of one master bloom filter with several others - for which no alternate order exists that would not run afoul of this issue.

**Comment by derekjn** [comment]
@carter-andrewj thank you so much for the thoughtful writeup! We're looking into this and will report back soon when we know more.

**Comment by carter-andrewj** [comment]
No worries, and thanks for the response. This is a major blocker for us, so I'd hugely appreciate any updates/timelines you might be able to give regarding a fix/release.

**Comment by derekjn** [comment]
@carter-andrewj good to know, thanks. Can you supply any `INSERT` statements from which this issue can be reproduced?

**Comment by carter-andrewj** [comment]
Full set of test queries to reproduce the problem included below.

On closer inspection, it would appear that `BLOOM_INTERSECTION` doesn't work at all when wrapping `BLOOM_UNION_AGG` (it seems to just ignore all inputs bar the last one in that instance).

I've obviously simplified the use case here to omit a direct need to use `GROUP` in the parent views. However, It's sadly not feasible to work without `BLOOM_UNION_AGG` as, in practice, we'll have multiple grouping columns in almost every view.

```
-- SETUP --

-- Drop old schema on reset --
DROP SCHEMA IF EXISTS testbed CASCADE;

-- Make schema anew --
CREATE SCHEMA IF NOT EXISTS testbed;



-- CREATE BASE STREAMS AND CONTINUOUS VIEWS

-- Set up input streams --
CREATE STREAM testbed.s1 (
	i INTEGER,
	b TEXT
);
CREATE STREAM testbed.s2 (
	j INTEGER,
	c TEXT
);

-- Set up base continuous views --
CREATE CONTINUOUS VIEW testbed.b1 AS
	SELECT
		x.i AS i,
		BLOOM_AGG(x.b) as b
	FROM testbed.s1 AS x
	GROUP BY i;

CREATE CONTINUOUS VIEW testbed.b2 AS
	SELECT
		x.j AS j,
		BLOOM_AGG(x.c) as c
	FROM testbed.s2 AS x
	GROUP BY j;



-- CREATE PARENT VIEWS --	

-- Create working view (without BLOOM_UNION_AGG) --
CREATE OR REPLACE VIEW testbed.result_1 AS
	SELECT
		i,
		BLOOM_CARDINALITY(x1.b) AS b_count,
		BLOOM_CARDINALITY(x2.c) AS c_count,
		BLOOM_CARDINALITY(BLOOM_UNION(x1.b, x2.c)) AS bc_union,
		BLOOM_CARDINALITY(BLOOM_INTERSECTION(x1.b, x2.c)) AS bc_inter,
		BLOOM_CARDINALITY(BLOOM_UNION(x1.b, x2.c)) AS bc_union2
	FROM testbed.b1 AS x1, testbed.b2 AS x2
	WHERE x1.i = x2.j;

-- Create failing view (with BLOOM_UNION_AGG) --
CREATE OR REPLACE VIEW testbed.result_2 AS
	SELECT
		i,
		BLOOM_CARDINALITY(BLOOM_UNION_AGG(x1.b)) AS b_count,
		BLOOM_CARDINALITY(BLOOM_UNION_AGG(x2.c)) AS c_count,
		BLOOM_CARDINALITY(BLOOM_UNION(BLOOM_UNION_AGG(x1.b), BLOOM_UNION_AGG(x2.c))) AS bc_union,
		BLOOM_CARDINALITY(BLOOM_INTERSECTION(BLOOM_UNION_AGG(x1.b), BLOOM_UNION_AGG(x2.c))) AS bc_inter,
		BLOOM_CARDINALITY(BLOOM_UNION(BLOOM_UNION_AGG(x1.b), BLOOM_UNION_AGG(x2.c))) AS bc_union2
	FROM testbed.b1 AS x1, testbed.b2 AS x2
	WHERE x1.i = x2.j
	GROUP BY i;
	

	
-- INSERT DATA TO STREAMS --

-- Expected result for i = 1:
--	b_count		= 3	(A, B, C)
--	c_count		= 3	(A, D, E)
--	union		= 5	(A, B, C, D, E)
--	intersect	= 1	(A)
INSERT INTO testbed.s1 (i, b) VALUES (1, 'A');
INSERT INTO testbed.s1 (i, b) VALUES (1, 'B');
INSERT INTO testbed.s1 (i, b) VALUES (1, 'C');
INSERT INTO testbed.s2 (j, c) VALUES (1, 'A');
INSERT INTO testbed.s2 (j, c) VALUES (1, 'D');
INSERT INTO testbed.s2 (j, c) VALUES (1, 'E');

-- Expected result for i = 2:
--	b_count		= 2	(P, Q)
--	c_count		= 2	(P, Q)
--	union		= 2	(P, Q)
--	intersect	= 2	(P, Q)
INSERT INTO testbed.s1 (i, b) VALUES (2, 'P');
INSERT INTO testbed.s1 (i, b) VALUES (2, 'P');
INSERT INTO testbed.s1 (i, b) VALUES (2, 'Q');
INSERT INTO testbed.s2 (j, c) VALUES (2, 'P');
INSERT INTO testbed.s2 (j, c) VALUES (2, 'Q');
INSERT INTO testbed.s2 (j, c) VALUES (2, 'Q');

-- Expected result for i = 3:
--	b_count		= 1	(X)
--	c_count		= 2	(Y, Z)
--	union		= 3	(X, Y, Z)
--	intersect	= 0	()
INSERT INTO testbed.s1 (i, b) VALUES (3, 'X');
INSERT INTO testbed.s1 (i, b) VALUES (3, 'X');
INSERT INTO testbed.s1 (i, b) VALUES (3, 'X');
INSERT INTO testbed.s2 (j, c) VALUES (3, 'Y');
INSERT INTO testbed.s2 (j, c) VALUES (3, 'Y');
INSERT INTO testbed.s2 (j, c) VALUES (3, 'Z');



-- CHECK RESULTS --

-- This one works --
SELECT * FROM testbed.result_1;

-- This one doesn't --
SELECT * FROM testbed.result_2;
```

**Comment by derekjn** [comment]
@carter-andrewj this is perfect, thank you so much! We'll try to get a fix and official release update out very soon.

**Comment by derekjn** [comment]
@carter-andrewj this has been fixed and we've published an official release update that contains the patch:

https://github.com/pipelinedb/pipelinedb/releases/tag/0.9.8u4

We can't thank you enough for taking the time to give us such a thoughtful writeup, this really makes things easy on us! Please let us know if you have any more issues here!

**Comment by carter-andrewj** [comment]
No worries :) Glad I could help.

I can confirm the new update is working as expected. Thanks for the prompt fix guys - much appreciated.
