### ISSUE TITLE
How to monitor Pipelinedb status?

### ISSUE THREAD

**Issue by fazlul3003** [pipelinedb/pipelinedb#1901]
Is there a monitoring tool that we can monitor Pipelinedb status (up/down) and usage status?

**Comment by derekjn** [comment]
@fazlul3003 PipelineDB is based on PostgreSQL, so any tools that work with PG will work with PipelineDB. Even simpler than that would be to simply periodically run a simple query against PipelineDB to verify that it's responding as expected.

Does that help?

**Comment by fazlul3003** [comment]
Yep thanks.
