### ISSUE TITLE
Give fancy aggregates/functions more intuitive names

### ISSUE THREAD

**Issue by derekjn** [pipelinedb/pipelinedb#1915]
Some of our aggregates and associated functions are admittedly somewhat cryptically named. We generally have tried to name things closely after the core data structure or algorithm they're based on. However, this doesn't provide much benefit to our users who may not be immediately familiar with how these underlying data structures and algorithms translate to a use case that's relevant to them.

I think we can improve the names here, e.g.:

| Fancy  | Sensible |
| ------------- | ------------- |
| `cmsketch`  | `frequencies`  |
| `fss`  | `top_k`  |
| `tdigest`  | `quantiles`  |

I think `bloom` and `hll` are well-known enough that those names are fine.

**Comment by usmanm** [comment]
You can also renamed `keyed_min(v, k)` to `first(v, k)` and `keyed_max(v, k)` to `last(v, k)`. I think it might also be nice to have versions where you keep track of first or last N elements.
