### ISSUE TITLE
Consider storing fully qualified parse trees instead of queries

### ISSUE THREAD

**Issue by derekjn** [pipelinedb/pipelinedb#1918]
In `pipeline_query`.

This should allow us to re-create objects during binary upgrades without preserving OIDs, which would probably be a good simplification.

Currently it seems like things like UDFs within a CQ's target list could reference nonexistent functions after a binary upgrade, as functions don't get consistent OIDs across binary upgrades...

**Comment by usmanm** [comment]
I think you may need both. When renaming objects, the OIDs are what help the query planner look up the correct objects (since they remain the same). If you don't store the OIDs, then renaming objects becomes a lot more tricky--may potentially involve rewriting all queries in `pipeline_query`.
