### ISSUE TITLE
file_fdw extension

### ISSUE THREAD

**Issue by backend-baron** [pipelinedb/pipelinedb#1934]
Hello,
I would like to use file_fdw extension in pipelinedb. Is there any easy way to install it without manually building whole base from source? I am using Ubuntu 16.04 vm.

**Comment by derekjn** [comment]
Hi @backend-baron!

> I would like to use file_fdw extension in pipelinedb. Is there any easy way to install it without manually building whole base from source? I am using Ubuntu 16.04 vm.

You just need to build the `file_fdw` extension against an existing PipelineDB installation--you don't need to build all of PipelineDB. With PipelineDB installed on your system and the binary directory on your `$PATH`, you should be able to just do this within the `file_fdw` directory:

    make
    make install

You may need to manually specify the `pg_config` path, which extensions need to know about:

   make PG_CONFIG=/path/to/pipelinedb/bin/pg_config
   make PG_CONFIG=/path/to/pipelinedb/bin/pg_config install

Please let us know if you have any issues building/using `file_fdw`!

**Comment by backend-baron** [comment]
Hi,
Unfortunately when I run make from file_fdw directory I get error about Makefile.global and contrib-global.mk files missing. From what I understand I can set those paths manually in Makefile but I can't see any Makefile.global in src directory.

**Comment by derekjn** [comment]
@backend-baron that is most likely because `pg_config` isn't being found. What output do you see when you run the `pg_config` command?

**Comment by backend-baron** [comment]
BINDIR = /usr/lib/pipelinedb/bin
DOCDIR = /usr/lib/pipelinedb/share/doc/pipelinedb
HTMLDIR = /usr/lib/pipelinedb/share/doc/pipelinedb
INCLUDEDIR = /usr/lib/pipelinedb/include
PKGINCLUDEDIR = /usr/lib/pipelinedb/include/pipelinedb
INCLUDEDIR-SERVER = /usr/lib/pipelinedb/include/pipelinedb/server
LIBDIR = /usr/lib/pipelinedb/lib
PKGLIBDIR = /usr/lib/pipelinedb/lib/pipelinedb
LOCALEDIR = /usr/lib/pipelinedb/share/locale
MANDIR = /usr/lib/pipelinedb/share/man
SHAREDIR = /usr/lib/pipelinedb/share/pipelinedb
SYSCONFDIR = /usr/lib/pipelinedb/etc/pipelinedb
PGXS = /usr/lib/pipelinedb/lib/pipelinedb/pgxs/src/makefiles/pgxs.mk
CONFIGURE = 'PIPELINE_VERSION=0.9.7' 'PIPELINE_REVISION=95ab563fac0802c424a269e597ac711de7c0cdce' '--prefix=/usr/lib/pipelinedb' '--with-system-tzdata=/usr/share/zoneinfo' 'CFLAGS=-g -O2' '--disable-rpath'
CC = gcc
CPPFLAGS = -D_GNU_SOURCE
CFLAGS = -Wall -Wmissing-prototypes -Wpointer-arith -Wdeclaration-after-statement -Wendif-labels -Wmissing-format-attribute -Wformat-security -fno-strict-aliasing -fwrapv -fexcess-precision=standard -g -O2
CFLAGS_SL = -fpic
LDFLAGS = -L../../../src/common -Wl,--as-needed
LDFLAGS_EX = 
LDFLAGS_SL = 
LIBS = -lpthread /usr/lib/libzmq.a -lstdc++ -lpgcommon -lpgport -lz -lreadline -lrt -lcrypt -ldl -lm 
VERSION = PostgreSQL 9.5.3


By the way while running make I specified path manually like you mentioned in previous comment.

**Comment by backend-baron** [comment]
With that flag everything worked fine.
Thank you a lot @derekjn .

**Comment by derekjn** [comment]
@backend-baron thanks for following up--we're happy to hear that!
