### ISSUE TITLE
hll_agg(uuid) discrepancy over count(distinct(uuid))

### ISSUE THREAD

**Issue by okrische** [pipelinedb/pipelinedb#1935]
Hello,

i use pipelinedb 0.9.8-1

I created a table with id (type bigint) and uuid (type uuid), pipelinedb 0.9.8-1

Then i run a query over the uuids via hll_agg(uuid) and then via count(distinct(uuid)). And i have a high discrepancy in the cardinalities. Can someone reproduce this or am i doing something wrong here?

(I came to see this issue, when my streaming tables showed also this high error. So i tested this manually via normal tables to reproduce it)

`
pipeline=# SELECT count(id), hll_cardinality(hll_agg(uuid)) FROM ids;
  count  | hll_cardinality 
---------+-----------------
 1722500 |         1737874
(1 row)

pipeline=# SELECT count(id), count(distinct(uuid)) FROM ids;
  count  | count  
---------+--------
 1722500 | 725961
(1 row)
`

Where is the discrepancy coming from?

- http://docs.pipelinedb.com/builtin.html#hll-funcs states, the error margin is 0.2%
- http://docs.pipelinedb.com/probabilistic.html states, the error margin is 0.81%

But the error rate seems to be much higher.

Any ideas?

**Comment by okrische** [comment]
I have created a file one can reproduce the table with:

* https://github.com/okrische/sharedfiles/raw/master/pipelinedb/create.sql.gz

Download the file, unzip it and then import via "pipeline dbname -f create.sql"

It basically does this:

`
DROP TABLE ids;

CREATE TABLE ids (id bigint, uuid uuid);

INSERT INTO ids (id,uuid) VALUES (0,'0c4142ba-6377-45a5-9468-1dacd9295dae'),(1,'a5d4f96e-2b42-4d9d-863b-3a7b9fc1cf6d'),...
...
CREATE UNIQUE INDEX id_idx ON ids (id);
`

**Comment by derekjn** [comment]
Hi @okrische, thank you so much for the detailed writeup! Since you're using `0.9.8`, this may be due to an issue we resolved in `0.9.9` (#1933).

We're taking a look at the repro information you've provided and will report back as soon as we know more.

**Comment by okrische** [comment]
Btw..if i change the data type for column 'uuid' from uuid to something like varchar(40), the hll aggregation works fine. So i think it has to do with how the uuids are funneled into hll. 

(Ugh. That probably also means, that all existing hll's have to be re-created.)

**Comment by okrische** [comment]
And i checked via "pipelinedb-0.9.9-debian9-x86_64.deb" as well.

**Comment by okrische** [comment]
I revisited with postgres 11 + pipelinedb-postgresql-11 (1.0.0-8~debian9)

Same numbers.

**Comment by derekjn** [comment]
@okrische we're looking into this now, there may be something going on with `uuid` uniqueness. We'll report back soon.

**Comment by derekjn** [comment]
@okrische we've found a canonical repor case with just `2` `uuids`:

```sql
CREATE TABLE ids (uuid uuid);
-- Identical uuids
INSERT INTO test (uuid) VALUES ('fe636e28-db82-43af-ac48-df26a4cda1f3');
INSERT INTO test (uuid) VALUES ('fe636e28-db82-43af-ac48-df26a4cda1f3');
```

```sql
SELECT hll_cardinality(hll_agg(uuid)) FROM ids;
 hll_cardinality 
-----------------
               2
(1 row)
```

**Comment by derekjn** [comment]
@okrische we've just pushed a fix for this. If you want, we can publish a release update containing this fix if you don't want to wait until the next official release. Just let us know here, it's no problem for us. Thanks for your persistence on this issue!

**Comment by okrische** [comment]
Thank you very much.

Would you agree, that all existing HLLs are affected (when using uuid) and i have to regenerate them with the same uuids again? Is there a way to zero out existing HLLs in existing continous views (or better: the mrel tables behind?)

In any way, it may surprise people, when they upgrade to a newer version.

**Comment by derekjn** [comment]
> Would you agree, that all existing HLLs are affected (when using uuid) and i have to regenerate them with the same uuids again? Is there a way to zero out existing HLLs in existing continous views (or better: the mrel tables behind?)

@okrische yes you'll want to regenerate them again after picking up this fix. You can zero them out by simply setting the `hyperloglog` column to `NULL`:

```sql
SET pipelinedb.matrels_writable = on;
UPDATE <cv name>_mrel SET <hll column> = NULL;
```

> In any way, it may surprise people, when they upgrade to a newer version.

So this issue only affected `hyperloglog` operations on a specific subset of types: fixed-length types that are passed by reference. Such types are not commonly used in the context of `hyperloglog`. The vast majority of `hyperloglog` usage is on fixed-length, by-value types (e.g. `integer`, `bigint`) or variable-length by-reference types (e.g. `text`) which are not effected by this issue.

Fixed-length by-reference types in PostgreSQL are generally not often used in the context of aggregations. Here they are if you'd like to see them:

```
postgres=# SELECT typname FROM pg_type WHERE typbyval = false AND typlen <> -1 ORDER BY typname;
  typname  
-----------
 aclitem
 box
 circle
 cstring
 interval
 line
 lseg
 macaddr
 macaddr8
 name
 point
 tid
 timetz
 tinterval
 unknown
 uuid
(16 rows)

**Comment by okrische** [comment]
Thank you. Very informative.

**Comment by derekjn** [comment]
@okrische we've just published an official release update containing the fix for this issue:

https://github.com/pipelinedb/pipelinedb/releases/tag/1.0.0-12
