### ISSUE TITLE
Continuous view can't be embeded

### ISSUE THREAD

**Issue by tminglei** [pipelinedb/pipelinedb#1951]
As the standardized new syntax implied,
```sql
CREATE VIEW continuous_view WITH (action=materialize, ...) AS SELECT count(*) FROM s;
```

continuous view as a materialized view is a great idea.

But now it can't be embeddable used yet.

When it will be implemented?

**Comment by derekjn** [comment]
Hi @tminglei, that syntax is in fact supported in the latest version of PipelineDB (`0.9.9`). Are you running an older version?

**Comment by tminglei** [comment]
@derekjn yes, the standardized new syntax can be applied to pipelineDB 0.9.9. I misunderstood it.
_Thanks!_
