### ISSUE TITLE
Show stream fields

### ISSUE THREAD

**Issue by samnegri** [pipelinedb/pipelinedb#1955]
I was looking into the docs searching how to describe the fields from a stream but I couldn't find it. Does this function exist? Is there a possible workaround?

**Comment by derekjn** [comment]
Hi @samnegri! Streams are just foreign tables, so how about this?

```
=# CREATE STREAM s (x integer, y text);
CREATE STREAM
-- Describe the stream
=# \d s
                                  Foreign table "public.s"
      Column       |           Type           | Collation | Nullable | Default | FDW options 
-------------------+--------------------------+-----------+----------+---------+-------------
 x                 | integer                  |           |          |         | 
 y                 | text                     |           |          |         | 
 arrival_timestamp | timestamp with time zone |           |          |         | 
Server: pipelinedb

**Comment by samnegri** [comment]
Hi @derekjn thank you for your reply!

The problem is I'm not using psql CLI, so I was not able to run `\d`. Even though, your answer helped me to search for the query postgres execute when using `\d`. In case other people need:

```
SELECT * FROM information_schema.COLUMNS WHERE TABLE_NAME = '<stream name>';
```

**Comment by derekjn** [comment]
@samnegri I'm happy you discovered an approach that works for your setup! Go ahead and close this issue if you feel that your issue is resolved.

Thanks for reaching out!
