### ISSUE TITLE
ERROR:  set operations within continuous views are currently not supported

### ISSUE THREAD

**Issue by andrew-blake** [pipelinedb/pipelinedb#1964]
Just trying out 1.0.0 and am seeing the following error whilst creating a non-continuous view using a UNION ALL statement.

`ERROR:  set operations within continuous views are currently not supported`

My view definition is

```
CREATE OR REPLACE VIEW test_view as
    SELECT * FROM test_sub_view1
    UNION ALL
    SELECT * FROM test_sub_view2
;
```

This query will fail with the error before getting to the stage of checking whether test_sub_view1 exists or not.

Restarting the DB without the pipelinedb extension allows the query to execute correctly.

**Comment by derekjn** [comment]
@andrew-blake thank you very much for the report! It looks like there's an issue with the analyzer interpreting this view definition as selecting from a stream. Should be a relatively trivial fix, we'll publish a release update that resolves this asap.

**Comment by derekjn** [comment]
@andrew-blake this has been resolved, thanks again for the helpful report. We're going to get this and #1963 into a small release update that we'll publish shortly. I'll reply here once it has been published.

**Comment by derekjn** [comment]
https://github.com/pipelinedb/pipelinedb/releases/tag/1.0.0rev2
