### ISSUE TITLE
PostgreSQL 11 support

### ISSUE THREAD

**Issue by derekjn** [pipelinedb/pipelinedb#1968]
```
pipelinedb-postgresql-11
```

**Comment by cailin-lai** [comment]
waiting for that.... ;-)

**Comment by derekjn** [comment]
PipelineDB now supports PostgreSQL 11. Binaries will be released shortly.

**Comment by derekjn** [comment]
https://github.com/pipelinedb/pipelinedb/releases/tag/1.0.0-5
