### ISSUE TITLE
Performance issue when trigger inserts into stream with active continuous view

### ISSUE THREAD

**Issue by andrew-blake** [pipelinedb/pipelinedb#1971]
If a trigger is configured to insert into a stream, and that stream has an active continuous view, then performance of inserts drops considerably (2ms to 10s for 100 rows inserted).

```
drop table if exists events cascade;
drop foreign table events_stream cascade;
drop function events_insert_func cascade;

create table events (
    id serial,
    timestamp_tz timestamptz,
    event_id int,
    state int
);

create foreign table events_stream ( id serial, timestamp_tz timestamptz, event_id int, state int ) server pipelinedb;

create or replace function events_insert_func() returns trigger as
$body$
begin
    insert into events_stream(id, timestamp_tz, event_id, state) 
    values (new.id, new.timestamp_tz, new.event_id, new.state);
    return new;
end;
$body$
    language plpgsql;

create trigger events_insert_trigger after insert on events for each row execute procedure events_insert_func();

insert into events (timestamp_tz, event_id, state)
select now(), s.*, 0
from generate_series(1, 100) s;
```

```
testdb1=# \timing
Timing is on.
testdb1=# insert into events (timestamp_tz, event_id, state)
testdb1-# select now(), s.*, 0
testdb1-# from generate_series(1, 100) s;

INSERT 0 100
Time: 2.077 ms
```

```
create view events_cv1 with ( action = materialize) as
select max(id) as max_id
from events_stream;

insert into events (timestamp_tz, event_id, state)
select now(), s.*, 0
from generate_series(1, 100) s;
```
```
testdb1=# \timing
Timing is on.
testdb1=# insert into events (timestamp_tz, event_id, state)
testdb1-# select now(), s.*, 0
testdb1-# from generate_series(1, 100) s;

INSERT 0 100
Time: 10282.493 ms (00:10.282)
```

**Comment by derekjn** [comment]
@andrew-blake we're taking a look at this now to see if we can repro. Stream insertion ack strength (`pipelinedb.stream_insert_level`) may be getting defaulted to something unexpected here...

**Comment by derekjn** [comment]
@andrew-blake I can confirm we can easily reproduce this, thank you so much for the writeup. Something is most definitely wrong here, we'll have a fix out shortly.

**Comment by derekjn** [comment]
@andrew-blake we can only repro this when `pipelinedb.stream_insert_level=sync_commit`. What is your `pipelinedb.stream_insert_level` set to?

It's meant to be set at `sync_receive`, with `sync_commit` only really being useful for testing purposes due to increased write latency.

**Comment by andrew-blake** [comment]
Yes, it is set to `sync_commit`.  Apologies if that's only a development setting. If it is, perhaps that could be mentioned in the docs.

I can't recall why that value is a none default value. I can only assume I'd copied from: https://github.com/pipelinedb/pipelinedb/blob/master/bin/run-dev

Would you expect the performance to be a slow as I'd seen with `sync_commit` ? 10s to insert 100 rows seems too slow even for testing.

**Comment by derekjn** [comment]
> Would you expect the performance to be a slow as I'd seen with sync_commit ? 10s to insert 100 rows seems too slow even for testing.

@andrew-blake when called within the context of a trigger function, yes. What's happening is that each worker and combiner process is only reading a single event per execution, and on top of that the stream insert is blocking until the combiner commits the updated result to disk.

You'd see better throughput if you scaled up workers and combiners, but it would still be far from the performance of `sync_receive`, which is the setting the system is optimized for.

We will make a note of that in the docs, since it isn't a very useful setting for production workloads.

**Comment by derekjn** [comment]
@andrew-blake docs have been updated--thank you for the suggestion and our apologies for the confusion.

**Comment by andrew-blake** [comment]
Using the `sync_receive` setting, I see a much better performance - the query can now complete with inserting 100 rows.

Increasing this to 1000 rows, still shows poor performance. 6.794 ms compared to 1821.335 ms.

```
testdb1=# insert into events (timestamp_tz, event_id, state) select now(), s.*, 0 from generate_series(1, 1000) s;
INSERT 0 1000
Time: 6.794 ms
testdb1=#
testdb1=# create view events_cv1 with ( action = materialize) as select max(id) as max_id from events_stream;
CREATE VIEW
Time: 6.709 ms
testdb1=#
testdb1=# insert into events (timestamp_tz, event_id, state) select now(), s.*, 0 from generate_series(1, 1000) s;
INSERT 0 1000
Time: 1821.335 ms (00:01.821)
testdb1=#
```

These are my pipelinedb settings. Any ideas ?

```
select name, setting from pg_settings where name like 'pipeline%' order by 1;
                 name                  |   setting
---------------------------------------+--------------
 pipelinedb.anonymous_update_checks    | on
 pipelinedb.batch_mem                  | 262144
 pipelinedb.batch_size                 | 10000
 pipelinedb.combiner_work_mem          | 262144
 pipelinedb.commit_interval            | 50
 pipelinedb.continuous_queries_enabled | on
 pipelinedb.fillfactor                 | 50
 pipelinedb.ipc_hwm                    | 10
 pipelinedb.matrels_writable           | off
 pipelinedb.max_wait                   | 50
 pipelinedb.num_combiners              | 1
 pipelinedb.num_queues                 | 1
 pipelinedb.num_reapers                | 1
 pipelinedb.num_workers                | 1
 pipelinedb.queue_mem                  | 262144
 pipelinedb.sliding_window_step_factor | 5
 pipelinedb.stream_insert_level        | sync_receive
 pipelinedb.stream_targets             |
 pipelinedb.ttl_expiration_batch_size  | 10000
 pipelinedb.ttl_expiration_threshold   | 5
(20 rows)
```

**Comment by derekjn** [comment]
@andrew-blake we can take a look at this but fundamentally there hasn't yet been any optimizations around inserting individual events from trigger functions. Currently continuous queries are optimized to be executed on batches of events, but what's most likely happening here is that you're getting one CQ plan execution per individual event, which incurs quite a lot of overhead as you can see. PipelineDB is optimized for throughput and not individual write latency.

You may want to increase `pipelinedb.max_wait` to cause workers to wait longer for more events to process.

For these very reasons, we're currently in the early stages of figuring out an integration with TSDB that makes sense and is performant. I don't think that trigger semantics are going to be the solution here, as there is a lot of overhead unnecessary overhead being incurred to execute an entire trigger function for each individual stream event.

We can take a closer look at this specific case to see if there's anything we can do here, but the right solution to this issue will be proper integration with TSDB.

**Comment by andrew-blake** [comment]
Thanks for the explanation. It sounds like we should separately insert data into the stream and event table - which does work quickly. 

I was hoping that the trigger would save effort, but no problem if that's not the use case you've optimised for.
