### ISSUE TITLE
Output deleted tuples from views with TTL

### ISSUE THREAD

**Issue by kurayama** [pipelinedb/pipelinedb#1986]
In our use case we're importing both historical and current data into pipelinedb and downsampling based on the timestamp (e.g. 1m bucket, 5m bucket) of the data, so CV's with TTL on the bucket seemed like a good fit.
But now we need to store the last reported value before the "sliding window" so we can use the last reported value to fill missing data if we are missing values in the beginning of sliding window or it's empty (as a way to emulate continuous queries with `FILL(previous)` in influxdb), so we tried using a output stream, something like:
```sql
CREATE VIEW last_reported_value AS
SELECT keyed_max((old).bucket, value) FROM output_of('downsampled_table') WHERE (new) IS NULL)
```
But we found out that CV's with TTL do not output deleted tuples (`(new) IS NULL`), and using sliding windows would store all data for the duration of the sliding window even if it is outside the window we want as it is based on the `arrival_timestamp` instead of the timestamp/bucket of the data.

cc @derekjn

**Comment by derekjn** [comment]
@kurayama this is something we just recently added, but you can actually specify your own column to use for SWs:

```sql
CREATE FOREIGN TABLE s (x integer, my_ts timestamp) SERVER pipelinedb;
CREATE VIEW sw WITH (sw = '1 day', sw_column = 'my_ts') AS
 SELECT count(*) FROM s;
```

Would that solve you problem here? This capability will be reflected in the docs soon, as I mentioned it's pretty new so it isn't there yet...

**Comment by kurayama** [comment]
@derekjn Works great, thanks 👍
