### ISSUE TITLE
Output stream of unselected row

### ISSUE THREAD

**Issue by nuhamind2** [pipelinedb/pipelinedb#1987]
Continuous transform has output stream and output function for data that is selected . But there is no output stream or function for unselected data.

Use case : 
I want to split a stream of coordinate into one that fall within certain cirle, and another one for outside the circle, say using ST_DWithin().

Alternative method:
Create two continous transform to consume from stream. One transform select coordinate that is inside a cirle, the other select coordinate outside a circle.
Con (that I can think of):
Computation done twice for one data point.
Mutual exclusion is not guaranted.

**Comment by derekjn** [comment]
@nuhamind2 what about including the result of `ST_DWithin` in the transforms target list? e.g.,

```
CREATE VIEW xform WITH (action=transform) AS
  SELECT ST_DWithin(...) AS within, ... FROM stream;
```

Then you can split its output downstream by just filtering with `WHERE within`

Would that work for you?

**Comment by nuhamind2** [comment]
Oh I see, that's interesting method. I seem it will work for me.

Thanks

**Comment by derekjn** [comment]
@nuhamind2 great! Let us know if you have any further questions on this, we're always happy to help. Feel free to close the issue when/if you feel that the question has been resolved.
