### ISSUE TITLE
create view error

### ISSUE THREAD

**Issue by FreeGIS** [pipelinedb/pipelinedb#1992]
![image](https://user-images.githubusercontent.com/8785843/49422377-9c282380-f7ce-11e8-9574-5fd0133affb0.png)
my postgresql.conf:
`shared_preload_libraries = 'pg_pathman,pg_stat_statements,pipelinedb'`

but when i modified the postgreql.conf
`shared_preload_libraries = 'pipelinedb'`
then 
`test=# CREATE VIEW cv1 WITH (action=materialize) AS select order_id, min(ts) min_ts,array_agg(ts||','||st_astext(pos)) as seg from s1 group by order_id; 

CREATE VIEW
I guess if had a bug in the pipelinedb and caused the error?

**Comment by derekjn** [comment]
@FreeGIS can you share the server logs at the time of the connection closing?
