### ISSUE TITLE
dist_merge_agg appears to be missing

### ISSUE THREAD

**Issue by ryan-shaw** [pipelinedb/pipelinedb#1998]
I cannot find it within the functions or in this repo, any reason why it was removed?

**Comment by ryan-shaw** [comment]
It looks to me that it's been replaced with `combine(tdigest)` is this correct?

**Comment by ryan-shaw** [comment]
Sorry for late reply on this one. My issue was solved by finding `combine(tdigest)` function did what I wanted, it appears as if the docs need updating for this?

**Comment by derekjn** [comment]
@ryan-shaw good call, we'll update the docs and close this issue as soon as that's done.

**Comment by derekjn** [comment]
@ryan-shaw docs have been updated, thanks for following up here!
