### ISSUE TITLE
create index not work when store original data onto the disk

### ISSUE THREAD

**Issue by zfz1989** [pipelinedb/pipelinedb#2001]
pipeline=# \di+    
                                      List of relations
 Schema |         Name         | Type  |  Owner   |     Table     |    Size    | Description 
--------+----------------------+-------+----------+---------------+------------+-------------
 public | cdn_bucket_1m_idx    | index | ceresdba | cdn_cv_mrel   | 145 MB     | 
 public | cdn_cv_mrel_expr_idx | index | ceresdba | cdn_cv_mrel   | 201 MB     | 
 public | cdn_cv_mrel_pkey     | index | ceresdba | cdn_cv_mrel   | 145 MB     | 
 public | cdn_user_isp_idx     | index | ceresdba | cdn_cv_mrel   | 148 MB     | 
 public | cdn_user_p_idx       | index | ceresdba | cdn_cv_mrel   | 209 MB     | 
 public | cluster_nodes_pkey   | index | ceresdba | cluster_nodes | 16 kB      | 
 public | dcs_avg_idx          | index | ceresdba | dcs_cv_mrel   | 8192 bytes | 
 public | dcs_call_times_idx   | index | ceresdba | dcs_cv_mrel   | 8192 bytes | 
 public | dcs_cluster_idx      | index | ceresdba | dcs_cv_mrel   | 8192 bytes | 
 public | dcs_cv_mrel_pkey     | index | ceresdba | dcs_cv_mrel   | 8192 bytes | 
 public | dcs_time_idx         | index | ceresdba | dcs_cv_mrel   | 8192 bytes | 
(11 rows)

The cdn_* indexes are based on the continuous view with aggregation，the dcs_* indexes are based on the continuous view without aggregation. The query performance has a big gap between them, and from the size of the index, I think there's something wrong on index when store original data on disk.

**Comment by derekjn** [comment]
@zfz1989 can you share the CV and index definitions here? And can you also explain a bit more about what you mean by this:

> The query performance has a big gap between them

**Comment by zfz1989** [comment]
CV:
create continuous view dcs_cv as select call_times,read_tps,avg_latency,used_mem_rate_max,data_version,dc_name,hit_rate,deal_time,hit_rate_sec,cpu_rate_avg,db_cloud_diff,slave_num,hostAddr,aof_open,master_num,sdk_version,bgs_open,cpu_rate_max,input_byte_per_req,timestamp,cluster_name,business_name,p99_latency,write_tps,rdb_open,used_memory,used_mem_rate,tps_max,output_byte_per_req,master_balance,host_num,tps,logType,top_commands,db_size,fail_times,allocated_memory,read_latency,time_string,hostName,slow_times,write_latency,no_expiration_key_size from dcs_stream;

Index:
create index avg_idx on dcs_cv(avg_latency);
create index dcs_call_times_idx on dcs_cv(call_times);
create index time_idx on dcs_cv(deal_time);
create index cluster_idx on dcs_cv(cluster_name);


"The query performance has a big gap between them"
It means that, when the CV with the right index(cdn_*), the query performance is good, and when the CV with
the bad index(dcs_*), the query performance is bad.


From the comment above, you can see the size of cdn_*_idx looks good, but the size of dcs_*_idx looks bad.
