### ISSUE TITLE
build 1.0.0-8 src/topkfuncs.c:212: error: ‘CacheMemoryContext’ undeclared (first use in this function)

### ISSUE THREAD

**Issue by sangli00** [pipelinedb/pipelinedb#2002]
```
src/topkfuncs.c: In function ‘hashed_topk_agg_weighted_trans’:
src/topkfuncs.c:212: error: ‘CacheMemoryContext’ undeclared (first use in this function)
src/topkfuncs.c:212: error: (Each undeclared identifier is reported only once
src/topkfuncs.c:212: error: for each function it appears in.)
make: *** [src/topkfuncs.o] Error 1
```
lose ```#include "utils/memutils.h"``` in ```src/topkfuncs.c```

https://github.com/pipelinedb/pipelinedb/archive/1.0.0-8.tar.gz

**Comment by derekjn** [comment]
@sangli00 this should be fixed in master.

**Comment by sangli00** [comment]
@derekjn  OK ，but release cannot fixed.

**Comment by derekjn** [comment]
@sangli00 we published a release update earlier today, can you use the latest package revision?

https://github.com/pipelinedb/pipelinedb/releases/tag/1.0.0-9

**Comment by sangli00** [comment]
@derekjn  Thanks
