### ISSUE TITLE
osrelid violate unique constraints "pipeline_cont_query_osrelid_index" when create view use 'output_of(cv)'

### ISSUE THREAD

**Issue by pengyusong** [pipelinedb/pipelinedb#2007]
Platform: centos 6.9
Version: Postgresql 11 + pipelinedb 1.0.0-9

I create a stream use statements as follows:
`
CREATE FOREIGN TABLE mr_raw_stream (
  timestamp varchar(128)
)
SERVER pipelinedb;
`
Then, I create one view from the stream:
`
CREATE VIEW mr_raw_ct AS SELECT timestamp::timestamptz(6) AS timestamp from mr_raw_stream;
`
Finaly, when I try to create view to use following sql, I got an error:
`
create view t_cv as select count(*) from output_of('mr_raw_ct');
`
Error msg : 
> violate unique constraints "pipeline_cont_query_osrelid_index", "osrelid" field value duplicated

Detail msg:
> It says the creating view 't_cv' use the same 'osrelid' value as view 'mr_raw_ct'.

Added: mac osx not found this question, the view 'mr_raw_ct' and 't_cv' use diffrent osrelid, so no questions.

That's strange, any suggestions will be appreciated.
Thanks.

**Updated**
I cancel "pipeline_cont_query_osrelid_index" unique constraints in "pipelinedb.cont_query" table by hand, and i retry to create the "t_cv" view, it success.
And I found that the "osrelid" field value are diffrent, Why is that?
That's terrible strange, please give me some suggestions, Thanks.

**Comment by derekjn** [comment]
@pengyusong this has now been fixed. I'll reply here as soon as an official release update has been published.

**Comment by derekjn** [comment]
@pengyusong 

https://github.com/pipelinedb/pipelinedb/releases/tag/1.0.0-10

**Comment by pengyusong** [comment]
@derekjn  It has been fixed. I confirm it, Thanks.
