### ISSUE TITLE
CREATE VIEW ERROR: unrecognized parameter "action"

### ISSUE THREAD

**Issue by LYJ8899** [pipelinedb/pipelinedb#2008]
2019-01-03 23:42:44.810 CST [11570] ERROR:  unrecognized parameter "action"
2019-01-03 23:42:44.810 CST [11570] STATEMENT:  CREATE VIEW wiki_stats WITH (action=materialize) AS
	SELECT hour, project,
	        count(*) AS total_pages,
	        sum(view_count) AS total_views,
	        min(view_count) AS min_views,
	        max(view_count) AS max_views,
	        avg(view_count) AS avg_views,
	        percentile_cont(0.99) WITHIN GROUP (ORDER BY view_count) AS p99_views,
	        sum(size) AS total_bytes_served
	FROM wiki_stream
	GROUP BY hour, project;
psql:/wiki_table.txt:18: ERROR:  unrecognized parameter "action"

**Comment by derekjn** [comment]
@LYJ8899 you most likely don't have this set in `postgresql.conf`:

```
shared_preload_libraries = 'pipelinedb'
```

See the [installation docs](http://docs.pipelinedb.com/installation.html#creating-the-pipelinedb-extension) for more information.

**Comment by derekjn** [comment]
@LYJ8899 I'm going to go ahead and close this since the `shared_preload_libraries` is the likely cause of this. Please feel free to reopen it if this does not resolve the issue.

**Comment by LYJ8899** [comment]
> @LYJ8899 I'm going to go ahead and close this since the `shared_preload_libraries` is the likely cause of this. Please feel free to reopen it if this does not resolve the issue.

thanks,it works for me.

**Comment by LYJ8899** [comment]
@derekjn 
thanks，it works for me.
