### ISSUE TITLE
Makefile.shlib: No such file or directory

### ISSUE THREAD

**Issue by ar-anvd** [pipelinedb/pipelinedb#2009]
As expected I didn't reveive much attention in SO. 

Any idea why this happens? Already tried with psql 10 and 11

https://stackoverflow.com/questions/54026680/compiling-from-source-pipelinedb

**Comment by derekjn** [comment]
@ar-anvd your question has been answered on SO but I'll include the same answer here:

You should be able to use the official PipelineDB binary packages--they are built for x86.

If you would rather build PipelineDB from source, it looks like you'll want to pass the USE_PGXS=1 option to you make install command:

```
make USE_PGXS=1 install
```

**Comment by ar-anvd** [comment]
@derekjn Ubuntu 14.04 x86

**Comment by ar-anvd** [comment]
@derekjn Currently I had success building from source using ```USE_PGXS=1```.

However now I am getting a "stack smashing detected" when inserting data. Not sure if this is still related with the installation.

![untitled-1](https://user-images.githubusercontent.com/4244340/50671474-0dbfe100-0fca-11e9-8db6-20c230430b02.png)

**Comment by derekjn** [comment]
@ar-anvd we're taking a look at this on this platform. In the meantime, can you post the output of `make USE_PGXS=1`? You'll probably want to `make clean` first...

**Comment by ar-anvd** [comment]
Thanks @derekjn 

I am doing these steps:

```
make USE_PGXS=1 clean
make USE_PGXS=1 install
make USE_PGXS=1 bootstrap
make USE_PGXS=1 run
```

[make_USE_PGXS=1_install.txt](https://github.com/pipelinedb/pipelinedb/files/2728860/make_USE_PGXS.1_install.txt)
[make_USE_PGXS=1_bootstrap.txt](https://github.com/pipelinedb/pipelinedb/files/2728861/make_USE_PGXS.1_bootstrap.txt)

**Comment by ar-anvd** [comment]
@derekjn After doing some more tests, with fresh installs of Ubuntu in multiples environments, currently, I think PipelineDB  is just not working in any Ubuntu 32 bits. Always a Segmentation fault when inserting data.

Tested with:

- Ubuntu 14.04 32 - compiling from source
- Ubuntu 16.04 32 - compiling from source
- Ubuntu 18.04 32 - compiling from source

**Comment by derekjn** [comment]
@ar-anvd after digging into this more it seems that additional work would be required to support PipelineDB on 32-bit architectures. Various core functionality relies on 64-bit architecture.

There has never really been a need or demand to support 32-bit architectures, so we likely will not be able to make this a priority.

Is there any way you can use a 64-bit system?

**Comment by ar-anvd** [comment]
@derekjn No worries, we can migrate our environment to 64bits without major concerns. Nevertheless, I think PipelineDB should state in docs that 32-bit is not supported.

**Comment by derekjn** [comment]
> @derekjn No worries, we can migrate our environment to 64bits without major concerns. Nevertheless, I think PipelineDB should state in docs that 32-bit is not supported.

@ar-anvd fair point, we'll update the docs soon. Let us know if you have any further issues getting up and running!
