### ISSUE TITLE
how to support custom aggregate

### ISSUE THREAD

**Issue by pengyusong** [pipelinedb/pipelinedb#2010]
When I use My aggregate, pipelinedb shows as follows:
> combinefn not set for aggregate function 

So, how to support custom aggregate.
My aggregate is below:
`CREATE OR REPLACE FUNCTION super_agg_accum(jsonb, integer, integer, integer, integer, integer)
RETURNS jsonb AS
$$
BEGIN
	IF $2 is not null THEN 
			$1 := jsonb_set($1, ('{"'||$2||'"}')::TEXT[], to_jsonb(COALESCE(($1->>'{'||$2||'}'), '0')::INTEGER + 1), true);
	END IF;

	IF $3 is not null THEN
			$1 := jsonb_set($1, ('{"'||$3||'"}')::TEXT[], to_jsonb(COALESCE(($1->>'{'||$2||'}'), '0')::INTEGER + 1), true);
	END IF;

	IF $4 is not null THEN
			$1 := jsonb_set($1, ('{"'||$4||'"}')::TEXT[], to_jsonb(COALESCE(($1->>'{'||$2||'}'), '0')::INTEGER + 1), true);
	END IF;

	IF $5 is not null THEN
			$1 := jsonb_set($1, ('{"'||$5||'"}')::TEXT[], to_jsonb(COALESCE(($1->>'{'||$2||'}'), '0')::INTEGER + 1), true);
	END IF;

	IF $6 is not null THEN
			$1 := jsonb_set($1, ('{"'||$6||'"}')::TEXT[], (COALESCE(($1->>'{'||$6||'}'), '0')::INTEGER + 1)::TEXT::jsonb, true);
	END IF;

	return $1;
END;
$$ LANGUAGE plpgsql IMMUTABLE STRICT PARALLEL SAFE;

CREATE OR REPLACE FUNCTION super_agg_final(jsonb)
RETURNS jsonb AS
$$
BEGIN
	return $1;
END;
$$ LANGUAGE plpgsql IMMUTABLE STRICT PARALLEL SAFE;

CREATE AGGREGATE super_agg(integer, integer, integer, integer, integer) (
    SFUNC = super_agg_accum,
    STYPE = jsonb,
    INITCOND = '{}',
    FINALFUNC = super_agg_final,
    PARALLEL = SAFE
);
`
The custom aggregate is used to sum diffrent value count in multi fields. 

Some examples will be appreciated, 
Some examples about how to write combine function will be greatly appreciated.
Thanks.

**Comment by derekjn** [comment]
@pengyusong please see #1990 for this. We're going to go ahead and merge this issue with that one since they're the same.
