### ISSUE TITLE
Using big bloom filters causes temp file errors

### ISSUE THREAD

**Issue by ewestern** [pipelinedb/pipelinedb#2012]
I have a continuous view defined as follows:
```
begin;
  create view views.discover_raw WITH (ttl = '4 months', ttl_column = 'month') as
    select
        date_trunc('month', ("partition.year" || "partition.month" || "partition.day")::timestamp) as month,
        "dataPoints.consumptionType" as consumption_type,
        "dataPoints.consumedResourceUri" as consumed_resource_uri,
        "dataPoints.ids"->0->>'idType' as id_type,
        bloom_agg("dataPoints.ids"->0->>'idValue', 0.05, 400000) as ids
    from datalakerows
    where "dataPoints.consumedResourceUri" is not null
    group by 1, 2, 3, 4;
  create index discover_consumption_type_idx on views.discover_raw (consumption_type);
commit;
```
When inserting at a high enough rate, this view causes a cascade of the following error messages:
```
2019-01-08 20:49:45.869 UTC [31991] WARNING:  temporary file base/pgsql_tmp/pgsql_tmp31991.5 not closed at end-of-transaction
2019-01-08 20:49:46.039 UTC [31993] ERROR:  temporary file 2 is not owned by resource owner WorkerResOwner
```
Note that this appears to be a function of the cardinality of the bloom filter. The problem is manifest for ```
bloom_agg("dataPoints.ids"->0->>'idValue', 0.05, 400000)
```
but not for
```
bloom_agg("dataPoints.ids"->0->>'idValue', 0.05, 100000)
```

**Comment by derekjn** [comment]
@ewestern does this begin to happen immediately or after the write load has been running for a while? e.g. what is the approximate cardinality of the BF when you begin to see this?

**Comment by ewestern** [comment]
This happens more or less immediately after inserts begin.
It's hard to say what the cardinality of the BF is when this happens, as there are 1000-5000 rows (each has a BF with a different cardinality) and several error messages per second.

**Comment by ewestern** [comment]
I should add that I'm able to skirt the issue a bit by setting pipelinedb.batch_mem much bigger -- in this case 1024MB. As you can imagine, this is pretty resource intensive and I'm not sure how scalable it can be.

**Comment by derekjn** [comment]
Simpler repro case:

```sql
CREATE FOREIGN TABLE s (x integer) SERVER pipelinedb;
CREATE VIEW v0 AS
 SELECT x, bloom_agg(random(), 0.05, 400000) AS ids
FROM s GROUP BY x;
INSERT INTO s (x) SELECT generate_series(1, 1000) x;
```

**Comment by derekjn** [comment]
@ewestern we've just fixed this in `master`. Are you able to work around this for the time being or would you like us to push out an official release update containing the fix?

**Comment by ewestern** [comment]
That's great! 
For now, I'm working around it by using a really large work mem. 
I think getting the resource usage down will be a pre-req for promoting this application, but it's not super-urgent.
Do you think there will be a normal release within a few weeks?

**Comment by derekjn** [comment]
> I think getting the resource usage down will be a pre-req for promoting this application, but it's not super-urgent.

This will definitely help with that. Here's what was happening here:

* Worker processes store their CQ plan output in memory up to `pipelinedb.batch_mem`
* As soon as that threshold is crossed, some of the plan output will be spilled to temporary files which have a lifetime of the current transaction
* Workers actually spilling to disk is rare, but in the case of Bloom filters specifically the plan output can get pretty large (`num_groups * bloom_filter_size`)
* You can see your Bloom filter sizes by using `bloom_print(bf_column)`
* Reducing `pipelinedb.batch_size` should also help here, as lowering it will lower the number of output groups
* You can probably increase `pipelinedb.num_workers` to compensate for smaller batches such that you have more workers each executing on smaller input batches, giving you similar throughput at the expense of a bit more CPU

In any case, after you pick up this fix you'll be able to bring `pipelinedb.batch_mem` back down, as temporary files for spillage will work just fine and likely won't affect perf too much.

> Do you think there will be a normal release within a few weeks?

Yes, definitely. No formal release date set but `1.1.0` should definitely be out within weeks, we're on the home stretch with it.

**Comment by ewestern** [comment]
Thanks for the additional help on this, @derekjn .
I wonder if I can belatedly take you up on your offer. Would a patch release containing this fix be too much trouble? I'm going to have to increase the size of my BFs again, and I don't think I can reasonably bump batch_mem anymore.

**Comment by derekjn** [comment]
> Would a patch release containing this fix be too much trouble?

@ewestern not for you! I'll reply here once it's published, no problem.

**Comment by derekjn** [comment]
@ewestern here you go:

https://github.com/pipelinedb/pipelinedb/releases/tag/1.0.0-13

Please don't hesitate to let us know if you still have an issue here after picking up this fix--we want to hear from you if something still isn't right!

**Comment by ewestern** [comment]
Thanks, @derekjn 
It's been running for a few days and haven't seen these issues again.
