### ISSUE TITLE
Clarify error messages on bloom filter operations

### ISSUE THREAD

**Issue by ewestern** [pipelinedb/pipelinedb#2015]
This is a minor issue, but the error messages when bloom operations use mis-matched bloom filters are a little misleading.
https://github.com/pipelinedb/pipelinedb/blob/master/src/bloomfuncs.c#L233
The code assumes that mismatched "m" values imply mismatched "p" values and that mismatched "k" values imply mismatched "n" values.
In fact, in normal bloom filter creation, "k" and "m" are both functions of both "n" and "p".

**Comment by derekjn** [comment]
@ewestern what do you think about an error message such as:

```
ERROR: bloom filters must have identical dimensions
```

**Comment by ewestern** [comment]
Either one seems fine. 
If it's simple, it might be nice to include the operation that is being performed, as well. (I came across this because I had at least 3 different bloom columns, and was doing a union in one place and an intersection in another, and it took a while to track down where it was happening).
If it's non-trivial, then it's no big deal.

**Comment by derekjn** [comment]
> If it's simple, it might be nice to include the operation that is being performed, as well.

@ewestern great idea! We'll definitely do this.

**Comment by derekjn** [comment]
@ewestern we went with these:

```
bloom_union operands must all have the same p and n
bloom_intersection operands must all have the same p and n
```

Thanks for your input!
