### ISSUE TITLE
Compile source failed

### ISSUE THREAD

**Issue by GangLiCN** [pipelinedb/pipelinedb#2017]
Hi,

I hit below error when compiling pipelinedb source code: (OS version: CentOS 7.3 x86-64)
move  <pipelinedb_src_dir> to postgresql source code dir
cd <pipelinedb_src_dir>
make USE_PGXS=1

The output is:
cc -Wall -Wmissing-prototypes -Wpointer-arith -Wdeclaration-after-statement -Wendif-labels -Wmissing-format-attribute -Wformat-security -fno-strict-aliasing -fwrapv -fexcess-precision=standard -O2 -fPIC -shared -o pipelinedb.so src/aggfuncs.o src/analyzer.o src/bloom.o src/bloomfuncs.o src/catalog.o src/cmsketch.o src/combiner.o src/combiner_receiver.o src/commands.o src/compat.o src/config.o src/copy.o src/distfuncs.o src/executor.o src/firstvalues.o src/freqfuncs.o src/fss.o src/hashfuncs.o src/hll.o src/hllfuncs.o src/json.o src/jsonb.o src/kv.o src/matrel.o src/microbatch.o src/miscutils.o src/mutator.o src/physical_group_lookup.o src/pipeline_combine.o src/pipeline_query.o src/pipeline_stream.o src/pipelinefuncs.o src/planner.o src/pzmq.o src/queue.o src/reader.o src/reaper.o src/ruleutils.o src/scheduler.o src/stats.o src/stream_fdw.o src/tdigest.o src/topkfuncs.o src/transform_receiver.o src/tuplestore_scan.o src/update.o src/worker.o -L/home/postgres/pg11/lib/pgxs/src/port -L/home/postgres/pg11/lib/pgxs/src/common    -Wl,--as-needed -Wl,-rpath,'/home/postgres/pg11/lib',--enable-new-dtags  /usr/lib/libzmq.a -lstdc++ 

:
/bin/ld: /usr/lib/libzmq.a(src_libzmq_la-zmq.o): relocation R_X86_64_32 against `_ZSt7nothrow' can not be used when making a shared object; recompile with -fPIC
/usr/lib/libzmq.a: error adding symbols: Bad value

I tried:
1) Downloaded several different zeromq packages(latest package from github, archive files from www.zeromq.org), then compile, no effect, same error hitted;

2) When compiling zeromq, added parameter:  CFLAGS="-O3 -fPIC", no effect,same error;

3) Executed "yum install zeromq-devel" after configued "zeromq" yum repo, but hitted many depedency error, installation failed again;
Error: Package: libzmq5-4.3.0+git20190102-605.2.x86_64 (network_messaging_zeromq_git-stable)
           Requires: libpgm-5.2.so.0()(64bit)
Error: Package: zeromq-devel-4.3.0+git20190102-605.2.x86_64 (network_messaging_zeromq_git-stable)
           Requires: openpgm-devel
Error: Package: zeromq-devel-4.3.0+git20190102-605.2.x86_64 (network_messaging_zeromq_git-stable)
           Requires: pkgconfig(openpgm-5.2) >= 5.2

So,  my questions is :
1) How to  make pipelinedb source to be compiled successfully ?  
2) Is there any obvious compatibility issue between "zeromq" and pipelinedb source ?

Thanks your help in advance.

**Comment by ar-anvd** [comment]
I confirm in my tests the same error when compiling from source to 64 bits (ubuntu).

**Comment by derekjn** [comment]
@GangLiCN @ar-anvd can you guys try compiling ZMQ as specified in this updated gist?

https://gist.github.com/derekjn/14f95b7ceb8029cd95f5488fb04c500a

**Comment by GangLiCN** [comment]
Cool ! This solution works ! pipelinedb source compile succeeded !

**Comment by derekjn** [comment]
@GangLiCN great to hear! We're going to close this issue for now, feel free to reopen it if you feel that there is still an issue.
