### ISSUE TITLE
WARNING:  pipelinedb must be loaded via shared_preload_libraries

### ISSUE THREAD

**Issue by emretufekci** [pipelinedb/pipelinedb#2022]
I've just installed PipelineDB 
I've changed already file in /etc/postgresql/11/main/postgresql.conf here,
but still in every query it is asking for "WARNING:  pipelinedb must be loaded via shared_preload_libraries".

While installation of PostgreSQL 
"pg_ctl -D  /var/lib/postgresql/11/main -l postgresql.log start" this line gave an error to me as a "pg_ctl: command not found" is it related I'm not quite sure.

If this is not issue just my installation bad, please close issue, thanks.

**Comment by derekjn** [comment]
@emretufekci yes, you need to set `shared_preload_libraries='pipelinedb'` in your `postgresql.conf`. Please see the docs for more information:

http://docs.pipelinedb.com/installation.html#creating-the-pipelinedb-extension

**Comment by derekjn** [comment]
@emretufekci we're going to go ahead and close this for now, but please feel free to reopen it if you feel that the issue has not been resolved.
