### ISSUE TITLE
upgrade postgresql with pipelinedb using pglogical

### ISSUE THREAD

**Issue by devsschmidt** [pipelinedb/pipelinedb#2040]
is it possible to perform a major upgrade for PostgreSQL with pglogical for zero downtime?

**Comment by cailin-lai** [comment]
What I can answer is that pipelinedb works with pglogical extension very well. I even used the extension to sync data to PG10 from pipelinedb 0.9.x. Regarding the zero downtime, did you mean w/o restarting after installed pglogical extension? Frankly, I've never tried to reload the necessary changes from postgresql.conf and pg_dba.conf on a running instance to enable pglogical without restarting.  But I think you can try it with "pg_ctl reload" or "select pg_reload_conf()".

**Comment by devsschmidt** [comment]
thanks for your answer. i wasn't specific enough. i actually  meant almost zero downtime, which wokrs pretty good, once you have pglogical in place. i just wasn't sure how pglogical works with the foreign tables aka streams created by the pipelinedb extension.
