### ISSUE TITLE
how to slove question like topn

### ISSUE THREAD

**Issue by Mrseven** [pipelinedb/pipelinedb#2049]
query like select id,count(*) from table group by id order by 2 desc limit 10; and if table has 10 billion rows and require the query finished less than 100ms each time. can pp support cms_topn function https://github.com/remzicanaksoy/cms_topn ?

**Comment by cailin-lai** [comment]
As I recall, pipelinedb has already similar alg functions which called topk_agg/topk_values. Have tries.

**Comment by Mrseven** [comment]
thx
