### ISSUE TITLE
Use NOTIFY channels to push to external systems

### ISSUE THREAD

**Issue by derekjn** [pipelinedb/pipelinedb#393]
e.g.:

    NOTIFY 'kafka://host/topic', 'payload'
    NOTIFY 'database = db user = user', 'payload'

It would also be nice to have configurable channels:

    NOTIFY channel.conf, 'payload'

Then in the config:

    format = kafka
    host = host
    ...

**Comment by dtheodor** [comment]
I want to use Postgres' `LISTEN` command to pick up updates in continuous views to forward real-time updates to my frontend (whatever the frontend may be). Is this issue related to this, or is this possible already? Also is this a valid use case for continuous views or do you advocate polling?

**Comment by mwarnock** [comment]
I have a similar use case. +1

**Comment by usmanm** [comment]
This is kind of related. But not exactly. Right now the only way to get changes from continuous views is by polling, but adding a push based changes support to continuous views is a feature that we want to get in soon.
