### ISSUE TITLE
Make client tab completion work with Pipeline-specific stuff

### ISSUE THREAD

**Issue by derekjn** [pipelinedb/pipelinedb#458]

**Comment by usmanm** [comment]
Things left:
- `CREATE/DROP STREAM`
- `EXPLAIN CONTINUOUS VIEW`
- `TRUNCATE CONTINUOUS VIEW`

Done:
- `CREATE/DROP CONTINUOUS VIEW`
- `ACTIVATE/DEACTIVATE`

@derekjn, @loadzero: Anything else?

**Comment by derekjn** [comment]
`ALTER STREAM`
